from __future__ import annotations

import base64
import importlib.util
import json
from pathlib import Path
from typing import Any

import pytest
from evidence_lane_plugin.cli import main as cli_main
from evidence_lane_plugin.constants import ENGINE_VERSION
from evidence_lane_plugin.errors import EvidenceLaneError
from evidence_lane_plugin.models import HostKind, normalize_host_kind
from evidence_lane_plugin.persistence import (
    InMemoryPersistence,
    PVSyncService,
    route_persistence,
)
from evidence_lane_plugin.redaction import contains_secret, redact
from evidence_lane_plugin.sealing import (
    deterministic_archive,
    seal_archive,
    unseal_archive,
)
from evidence_lane_plugin.service import EvidenceLaneService

from .conftest import build_and_approve_pv1


def test_secret_redaction_covers_common_tokens() -> None:
    payload = {
        "github": "github_pat_abcdefghijklmnopqrstuvwxyz123456",
        "openai": "sk-proj-abcdefghijklmnopqrstuvwxyz123456",
        "header": "Authorization: Bearer-super-secret-value",
    }
    safe = redact(payload)
    assert safe != payload
    assert contains_secret(safe) is False


def test_host_persistence_matrix() -> None:
    assert route_persistence(HostKind.CODEX_DESKTOP, ephemeral=False).mode == "local"
    assert route_persistence(HostKind.CODEX_CLI, ephemeral=False).mode == "local"
    assert route_persistence(HostKind.CODEX_VM, ephemeral=True).mode == "google_drive"
    assert (
        route_persistence(
            HostKind.CHATGPT,
            ephemeral=False,
            server_has_durable_filesystem=True,
        ).mode
        == "local"
    )
    assert route_persistence(HostKind.CHATGPT, ephemeral=False).mode == "google_drive"
    assert (
        route_persistence(
            HostKind.CHATGPT,
            ephemeral=False,
            server_has_durable_filesystem=False,
        ).mode
        == "google_drive"
    )
    assert route_persistence(HostKind.PUBLIC_AI, ephemeral=False).mode == "google_drive"


def test_host_aliases_are_actionable() -> None:
    assert normalize_host_kind("codex") == HostKind.CODEX_DESKTOP
    assert normalize_host_kind("Codex Desktop") == HostKind.CODEX_DESKTOP
    assert normalize_host_kind("chatgpt") == HostKind.CHATGPT
    with pytest.raises(EvidenceLaneError) as error:
        normalize_host_kind("unknown-host")
    assert error.value.code == "HOST_KIND_INVALID"
    assert "CODEX_DESKTOP" in error.value.details["supported_values"]


def test_remote_host_fails_closed_without_drive(service) -> None:
    with pytest.raises(EvidenceLaneError) as error:
        service.boot_session(
            project_id="book-faires",
            user_id="user-test",
            workspace_id="workspace-test",
            host="CHATGPT_WORK",
            agent_id="chatgpt-agent",
            sandbox_id="remote-sandbox",
            ephemeral=True,
            runtime_context={},
        )
    assert error.value.code == "DURABLE_PERSISTENCE_NOT_CONFIGURED"


def test_bootstrap_installs_self_contained_noneditable_runtime() -> None:
    root = Path(__file__).resolve().parents[1]
    bootstrap = (
        root / "plugins" / "evidence-lane-plugin" / "scripts" / "bootstrap.py"
    ).read_text(encoding="utf-8")
    requirements = (root / "requirements.in").read_text(encoding="utf-8")
    lock = (
        root / "plugins" / "evidence-lane-plugin" / "requirements.lock.txt"
    ).read_text(encoding="utf-8")

    assert '"--force-reinstall"' in bootstrap
    assert '"--no-build-isolation"' in bootstrap
    assert '"--no-deps"' in bootstrap
    assert '"-e"' not in bootstrap
    assert '"activate-installation"' in bootstrap
    assert 'project = plugin_root / "pyproject.toml"' in bootstrap
    assert "str(plugin_root)" in bootstrap
    assert "plugin_root.parents" not in bootstrap

    runner = (
        root / "plugins" / "evidence-lane-plugin" / "scripts" / "run_mcp.py"
    ).read_text(encoding="utf-8")
    assert "_bootstrap_runtime(plugin_root)" in runner

    mcp_config = json.loads(
        (root / "plugins" / "evidence-lane-plugin" / ".mcp.json").read_text(
            encoding="utf-8"
        )
    )
    server = mcp_config["mcpServers"]["evidence-lane"]
    assert server["startup_timeout_sec"] >= 600
    assert server["tool_timeout_sec"] >= 300
    assert "setuptools==83.0.0" in requirements
    assert "wheel==0.46.3" in requirements
    assert "numpy==2.4.6" in requirements
    assert "# This file is autogenerated by pip-compile with Python 3.11" in lock
    assert "numpy==2.4.6" in lock
    assert "numpy==2.5.1" not in lock
    assert 'pywin32==312 ; sys_platform == "win32"' in lock


def test_bootstrap_cleans_only_generated_in_root_metadata(tmp_path: Path) -> None:
    root = Path(__file__).resolve().parents[1]
    bootstrap_path = (
        root / "plugins" / "evidence-lane-plugin" / "scripts" / "bootstrap.py"
    )
    spec = importlib.util.spec_from_file_location(
        "evidence_lane_bootstrap_cleanup_test",
        bootstrap_path,
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    plugin_root = tmp_path / "plugin"
    build_file = plugin_root / "build" / "lib" / "generated.py"
    egg_file = plugin_root / "src" / "evidence_lane_plugin.egg-info" / "SOURCES.txt"
    source_file = plugin_root / "src" / "evidence_lane_plugin" / "__init__.py"
    for path in (build_file, egg_file, source_file):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("test\n", encoding="utf-8")

    module._cleanup_generated_build_artifacts(plugin_root)

    assert not (plugin_root / "build").exists()
    assert not (plugin_root / "src" / "evidence_lane_plugin.egg-info").exists()
    assert source_file.read_text(encoding="utf-8") == "test\n"


def test_installation_activation_updates_a_stale_version(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    store = tmp_path / "persistent-store"
    store.mkdir(parents=True)
    (store / "installation.json").write_text(
        json.dumps(
            {
                "schema": "evidence-lane.plugin-installation.v1",
                "plugin_id": "evidence-lane-plugin",
                "display_name": "Evidence Lane Plugin",
                "version": "0.3.0",
                "state": "INSTALLED_UNTIL_USER_REMOVES_PLUGIN",
                "installed_at": "2026-07-26T20:33:04.325482Z",
                "session_boot_context_inside_pv": False,
                "session_flash_required": True,
                "session_flash_inside_pv": False,
                "hil_approval_inferred": False,
            }
        )
        + "\n",
        encoding="utf-8",
    )
    monkeypatch.setenv("EVIDENCE_LANE_DATA_ROOT", str(store))

    assert cli_main(["activate-installation"]) == 0

    result = json.loads(capsys.readouterr().out)
    persisted = json.loads((store / "installation.json").read_text(encoding="utf-8"))
    assert result["version"] == ENGINE_VERSION
    assert persisted["version"] == ENGINE_VERSION
    assert persisted["installed_at"] == "2026-07-26T20:33:04.325482Z"
    assert persisted["hil_approval_inferred"] is False
    service = EvidenceLaneService(data_root=store)
    flash = service.session_flash_status()
    assert flash["flash_state"] == "FLASHED_UNTIL_PLUGIN_REMOVED"
    assert flash["receipt"]["inside_pv"] is False
    assert flash["receipt"]["hil_approval_inferred"] is False


def test_private_pv_is_encrypted_for_drive(service) -> None:
    _session_id, _ = build_and_approve_pv1(service)
    package = service.store.accepted_path("book-faires", "PV1")
    archive, metadata = deterministic_archive(package)
    key = base64.urlsafe_b64encode(bytes(range(32))).decode("ascii")
    sealed, sealed_metadata, extension = seal_archive(
        archive,
        metadata,
        key_value=key,
        require_encryption=True,
    )
    assert extension == ".pv.enc.json"
    assert sealed_metadata["encryption"] == "AES-256-GCM"
    unsealed, recovered = unseal_archive(sealed, key_value=key)
    assert unsealed == archive
    assert recovered == metadata

    backend = InMemoryPersistence()
    sync = PVSyncService(
        store=service.store,
        backend=backend,
        drive_encryption_key=key,
    )
    receipt = sync.sync_pv("book-faires", "PV1", category="accepted")
    assert receipt["persistence"]["sha256"] == receipt["sealed"]["sealed_sha256"]
    assert list(backend.objects) == [("book-faires", "accepted", "PV1.pv.enc.json")]

    pointer = sync.sync_pointer("book-faires")
    pointer_key = (
        "book-faires",
        "receipts",
        "active-pointer-gen-00000001-PV1.json",
    )
    assert pointer["pointer"]["accepted_pv"] == "PV1"
    assert pointer["pointer"]["generation"] == 1
    assert backend.objects[pointer_key]["sha256"] == pointer["pointer_sha256"]


def test_durable_local_lifecycle_never_calls_configured_drive_backend(service) -> None:
    class ForbiddenDriveBackend:
        def __init__(self) -> None:
            self.calls = 0

        def put(
            self,
            *,
            project_id: str,
            category: str,
            name: str,
            content: bytes,
            mime_type: str,
            metadata: dict[str, Any],
        ) -> dict[str, Any]:
            del project_id, category, name, content, mime_type, metadata
            self.calls += 1
            raise AssertionError("Durable local lifecycle called Drive persistence.")

    backend = ForbiddenDriveBackend()
    service.sync_service = PVSyncService(store=service.store, backend=backend)

    session_id, _candidate = build_and_approve_pv1(service)

    assert session_id
    assert backend.calls == 0
    assert service.store.pointer("book-faires").accepted_pv == "PV1"


def test_remote_push_prepare_does_not_push_and_wrong_token_fails(service) -> None:
    build_and_approve_pv1(service)
    prepared = service.remote_git.prepare_push(
        "book-faires",
        requested_by="human-test",
        remote="origin",
        local_ref="main",
        remote_branch="evidence-lane-test",
    )
    assert prepared["action"]["status"] == "PREPARED_AWAITING_EXACT_CONFIRMATION"
    with pytest.raises(EvidenceLaneError) as error:
        service.remote_git.execute_push(
            "book-faires",
            action_id=prepared["action"]["action_id"],
            confirmation_token="WRONG",
            confirmed_by="human-test",
        )
    assert error.value.code == "REMOTE_ACTION_CONFIRMATION_INVALID"
