import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import type * as Three from 'three';
import type {Snapshot} from '../types';
import {Icon} from '../ui';
import {useObserver} from './ObserverContext';
import {buildObservationGraph,type ObservationGraph} from './observation-graph';
import {interpolatePose,smoothProgress,type MorphPose,type Point3} from './morph-state';
import {ProjectCover} from './ProjectCover';
import type {Project} from '../types';
import {createHomeOpticalRoute} from './website/home-optical-routes';
import {useWorkspaceSelection} from './WorkspaceSelection';
import {ViewRecordPanel} from './ViewRecordPanel';

export function ObservationScene({view,data,connected}:{view:string;data:Snapshot;connected:boolean}){
 const workspace=useWorkspaceSelection();
 const graph=useMemo(()=>buildObservationGraph(view,data,workspace?.selected??null,workspace?.section,workspace?.subjects),[view,data,workspace?.selected,workspace?.section,workspace?.subjects]);const{paused,inspectSubject}=useObserver();
 const live=useRef({graph,paused,view});live.current={graph,paused,view};const host=useRef<HTMLDivElement>(null),mount=useRef<HTMLDivElement>(null),buttons=useRef<(HTMLButtonElement|null)[]>([]);
 const[shown,setShown]=useState(graph),[ready,setReady]=useState(false),[fallback,setFallback]=useState(false);
 useEffect(()=>{const element=host.current,canvas=mount.current;if(!element||!canvas)return;let gone=false,dispose=()=>{};
 const begin=async()=>{const[T,{RoomEnvironment}]=await Promise.all([import('three'),import('three/examples/jsm/environments/RoomEnvironment.js')]);if(gone)return;let renderer:Three.WebGLRenderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'})}catch{setFallback(true);setReady(true);return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;canvas.append(renderer.domElement);
 const scene=new T.Scene(),root=new T.Group(),camera=new T.OrthographicCamera(-4,4,4,-4,.1,40);camera.position.z=16;scene.add(root);const room=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=1.5;room.dispose();pmrem.dispose();scene.add(new T.HemisphereLight(0xc8efff,0x141c38,2));const key=new T.DirectionalLight(0xe7fbff,3),rim=new T.DirectionalLight(0xbda7ff,2);key.position.set(-3,4,5);rim.position.set(4,-1,4);scene.add(key,rim);
 const maxEdges=9,opticalRoutes=Array.from({length:maxEdges},()=>createHomeOpticalRoute(T,root,112,1.35));element.dataset.connectionStyle='home-optical-ribbons';
 const orbGeometry=new T.SphereGeometry(1,36,24);
 const orbMaterials=Array.from({length:10},()=>new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{uTint:{value:new T.Color('#9ac5e6')},uOpacity:{value:1},uLight:{value:new T.Vector3(-3,4,5)},uRim:{value:new T.Vector3(4,-2,4)}},vertexShader:`varying vec3 worldPosition;varying vec3 worldNormal;void main(){vec4 w=modelMatrix*vec4(position,1.);worldPosition=w.xyz;worldNormal=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`uniform vec3 uTint,uLight,uRim;uniform float uOpacity;varying vec3 worldPosition,worldNormal;void main(){vec3 n=normalize(worldNormal),v=normalize(cameraPosition-worldPosition),l=normalize(uLight-worldPosition),r=normalize(uRim-worldPosition);float facing=max(0.,dot(n,v));float fresnel=pow(1.-facing,3.1);float edge=pow(1.-facing,11.);float glint=pow(max(0.,dot(n,normalize(l+v))),115.);float rimGlint=pow(max(0.,dot(n,normalize(r+v))),92.);float reflection=pow(max(0.,dot(reflect(-v,n),normalize(vec3(-.6,.9,.5)))),15.)*.15;float alpha=.018+fresnel*.29+edge*.36+glint*.84+rimGlint*.42+reflection;vec3 tint=mix(uTint*.78,vec3(.95,.99,1.),clamp(glint+rimGlint+edge*.62,0.,1.));gl_FragColor=vec4(tint,clamp(alpha,0.,.93)*uOpacity);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`}));
 const glassSubjects=orbMaterials.map(material=>{const sphere=new T.Mesh(orbGeometry,material);sphere.frustumCulled=false;sphere.renderOrder=3;root.add(sphere);return sphere});
 let w=1,h=1,ww=8,frame=0,last=0,time=0,to:ObservationGraph=live.current.graph,mix=1,switched=true,yaw=0,pitch=0,drag=false,px=0,py=0,previousView=live.current.view,announced=false,resized=false,wasPaused=false;
 const resize=()=>{w=Math.max(1,element.clientWidth);h=Math.max(1,element.clientHeight);ww=8*w/h;camera.left=-ww/2;camera.right=ww/2;camera.updateProjectionMatrix();renderer.setSize(w,h,false);resized=true};const ro=new ResizeObserver(resize);ro.observe(element);resize();
 const down=(e:PointerEvent)=>{if(live.current.paused||(e.target instanceof Element&&e.target.closest('button')))return;drag=true;px=e.clientX;py=e.clientY;element.setPointerCapture(e.pointerId)};const move=(e:PointerEvent)=>{if(!drag)return;yaw=Math.max(-.16,Math.min(.16,yaw+(e.clientX-px)*.001));pitch=Math.max(-.1,Math.min(.1,pitch-(e.clientY-py)*.001));px=e.clientX;py=e.clientY};const up=()=>{drag=false};element.addEventListener('pointerdown',down);element.addEventListener('pointermove',move);element.addEventListener('pointerup',up);element.addEventListener('pointercancel',up);
 const vec=(n:{x:number;y:number})=>{const x=Math.max(52,Math.min(w-52,n.x/100*w)),y=Math.max(40,Math.min(h-48,n.y/100*h));return new T.Vector3((x/w-.5)*ww,(.5-y/h)*8,0)};
 const curve=(g:ObservationGraph,i:number)=>{const edge=g.edges[i];if(!edge){const p=vec({x:50,y:50});return new T.CubicBezierCurve3(p,p.clone(),p.clone(),p.clone())}const a=vec(g.nodes[edge[0]]),b=vec(g.nodes[edge[1]]),direction=b.clone().sub(a).normalize(),radius=Math.min(22*8/h,a.distanceTo(b)*.22);a.addScaledVector(direction,radius);b.addScaledVector(direction,-radius);const c=a.clone().lerp(b,.33),d=a.clone().lerp(b,.68),bend=Math.min(1.1,a.distanceTo(b)*.28);c.x-=direction.y*bend;d.y-=direction.x*bend;return new T.CubicBezierCurve3(a,c,d,b)};
 const pose=(g:ObservationGraph):MorphPose=>({nodes:Array.from({length:10},(_,i)=>vec(g.nodes[i]??{x:50,y:50}).toArray() as Point3),nodeOpacity:Array.from({length:10},(_,i)=>g.nodes[i]?1:0),curves:Array.from({length:maxEdges},(_,i)=>{const c=curve(g,i);return[c.v0.toArray() as Point3,c.v1.toArray() as Point3,c.v2.toArray() as Point3,c.v3.toArray() as Point3]}),edgeOpacity:Array.from({length:maxEdges},(_,i)=>g.edges[i]?1:0)});
 const curvesFor=(value:MorphPose)=>value.curves.map(c=>new T.CubicBezierCurve3(...c.map(p=>new T.Vector3(...p)) as [Three.Vector3,Three.Vector3,Three.Vector3,Three.Vector3]));
 let origin=pose(to),destination=origin,ca=curvesFor(origin),cb=ca;resized=false;
 const a=new T.Vector3(),b=new T.Vector3(),p=new T.Vector3(),q=new T.Vector3(),projected=new T.Vector3();
 const lost=(e:Event)=>{e.preventDefault();cancelAnimationFrame(frame);for(const button of buttons.current){if(!button)continue;button.style.removeProperty('left');button.style.removeProperty('top');button.style.removeProperty('opacity');button.style.removeProperty('visibility');button.disabled=false;button.tabIndex=0}element.style.setProperty('--observer-label-opacity','1');setFallback(true);setReady(true)};renderer.domElement.addEventListener('webglcontextlost',lost);
 const tick=(now:number)=>{frame=requestAnimationFrame(tick);if(document.hidden){last=now;return}if(now-last<32)return;const dt=Math.min(.05,(now-last)/1000);last=now;const state=live.current;if(state.paused&&wasPaused&&!resized&&to===state.graph&&mix===1)return;wasPaused=state.paused;if(resized){origin=pose(to);destination=origin;ca=curvesFor(origin);cb=ca;mix=1;resized=false}if(to!==state.graph){const changed=previousView!==state.view||JSON.stringify([to.nodes.map(n=>[n.id,n.x,n.y]),to.edges])!==JSON.stringify([state.graph.nodes.map(n=>[n.id,n.x,n.y]),state.graph.edges]);if(changed){origin=interpolatePose(origin,destination,smoothProgress(mix));destination=pose(state.graph);ca=curvesFor(origin);cb=curvesFor(destination);mix=0;switched=false}to=state.graph;if(!changed&&switched)setShown(to)}if(previousView!==state.view){previousView=state.view;yaw=0;pitch=0}if(!state.paused)time+=dt;mix=state.paused?1:Math.min(1,mix+dt/ .48);const blend=smoothProgress(mix);if(!switched&&mix>=.5){setShown(to);switched=true}root.rotation.set(pitch,yaw,0);root.updateMatrixWorld(true);key.position.x=-2+Math.sin(time*.35)*1.5;rim.position.y=-1+Math.cos(time*.27);element.dataset.transition=blend.toFixed(3);element.style.setProperty('--observer-label-opacity',String(Math.pow(Math.abs(blend-.5)*2,2)));element.dataset.manualRotation=(Math.abs(yaw)+Math.abs(pitch)).toFixed(3);
 for(let i=0;i<maxEdges;i++){const alpha=origin.edgeOpacity[i]*(1-blend)+destination.edgeOpacity[i]*blend;opticalRoutes[i].update(time,(t,target)=>{ca[i].getPoint(t,a);cb[i].getPoint(t,b);target.copy(a).lerp(b,blend)},alpha)}

 for(let i=0;i<10;i++){const e=buttons.current[i];if(!e)continue;const nb=to.nodes[i],alpha=origin.nodeOpacity[i]*(1-blend)+destination.nodeOpacity[i]*blend;p.set(...origin.nodes[i]).lerp(q.set(...destination.nodes[i]),blend);const sphere=glassSubjects[i];const photo=nb?.icon==='projects'&&nb.value&&typeof nb.value==='object'&&'project_id' in nb.value; sphere.visible=alpha>.01&&!photo;sphere.position.copy(p);sphere.position.z=.04;sphere.scale.setScalar(Math.min(38,Math.max(27,w*.05))*8/h);orbMaterials[i].uniforms.uTint.value.lerp(new T.Color(nb?.color??'#9bc6df'),.06);orbMaterials[i].uniforms.uOpacity.value=alpha;orbMaterials[i].uniforms.uLight.value.copy(key.position);orbMaterials[i].uniforms.uRim.value.copy(rim.position);projected.copy(p).applyMatrix4(root.matrixWorld).project(camera);e.style.left=((projected.x*.5+.5)*w)+'px';e.style.top=((-projected.y*.5+.5)*h)+'px';e.style.opacity=String(alpha);e.style.visibility=alpha>.01?'visible':'hidden';e.disabled=mix<.95||!nb;e.tabIndex=e.disabled?-1:0}renderer.render(scene,camera);if(!announced){announced=true;setReady(true)}};frame=requestAnimationFrame(tick);
 dispose=()=>{cancelAnimationFrame(frame);ro.disconnect();element.removeEventListener('pointerdown',down);element.removeEventListener('pointermove',move);element.removeEventListener('pointerup',up);element.removeEventListener('pointercancel',up);renderer.domElement.removeEventListener('webglcontextlost',lost);opticalRoutes.forEach(route=>route.dispose());orbGeometry.dispose();orbMaterials.forEach(m=>m.dispose());env.dispose();renderer.dispose();renderer.domElement.remove()};};void begin().catch(()=>{if(!gone){setFallback(true);setReady(true)}});return()=>{gone=true;dispose()};
 },[]);
 useEffect(()=>{if(fallback)setShown(graph)},[fallback,graph]);
 return <aside data-view={view} data-node-count={shown.nodes.length} className="observer-relationship-panel" aria-label="Observation relationships"><header><span>AT A GLANCE</span><h2>{shown.title}</h2><small>{connected?'Received records':'Last received records'}</small></header><div ref={host} className="observer-scene" data-ready={ready} data-static={fallback} data-physical-glass={ready&&!fallback}><div ref={mount} className="observer-ribbon-canvas" aria-hidden="true"/>{Array.from({length:10},(_,i)=>{const n=shown.nodes[i];return <button ref={e=>{buttons.current[i]=e}} key={i} className="observer-scene-node" style={{'--node-x':(n?.x??50)+'%','--node-y':(n?.y??50)+'%','--node-color':n?.color} as CSSProperties} hidden={!n} aria-label={n?'Inspect '+n.label:undefined} data-subject-key={n?.subject.key} onClick={()=>{if(n)workspace?workspace.open(n.subject):inspectSubject(n.subject)}}>{n?.icon==='projects'&&n.value&&typeof n.value==='object'&&'project_id' in n.value&&'source_root' in n.value?<ProjectCover project={n.value as Project} compact/>:<Icon name={n?.icon??'evidence'} size={52} identity={n?.subject.kind==='tool'?n.subject.id:undefined}/>}<span>{n?.label}</span>{n?.note&&<small>{n.note}</small>}</button>})}{!shown.nodes.length&&<p className="observer-graph-empty">No subjects in this observation.</p>}</div><ViewRecordPanel/><p>{shown.note}</p>{!!shown.omitted&&<p>{shown.omitted} additional records remain available in the list.</p>}<small className="observer-graph-help">Select a subject for its recorded details. The full records remain in the main view.</small></aside>;
}
