import type {Snapshot,Task,RecordData} from '../types';

// Development-only observations. api.ts loads this module only behind import.meta.env.DEV.
const projects=[{project_id:'preview-coastal',source_root:'C:/Example/Coastal Study',state_root:'C:/ExampleState/Coastal Study',read_only:true},{project_id:'preview-notes',source_root:'C:/Example/Research Notes',state_root:'C:/ExampleState/Research Notes',read_only:true},{project_id:'preview-product',source_root:'C:/Example/Product Analysis',state_root:'C:/ExampleState/Product Analysis',read_only:true}];
const tasks:Task[]=Array.from({length:105},(_,i)=>({position:i+1,state:i<8?'completed':i===8?'active':'pending',contract_digest:'illustrative-contract-'+(i+1),definition:{task_id:'TASK-'+String(i+1).padStart(3,'0'),title:i===8?'Inspect source coverage':['Identify selected sources','Check extraction coverage','Compare evidence references','Review the recorded output'][i%4]+' · '+(i+1),requested_outcome:'Inspect the selected evidence and disclose its coverage and limits.',profile:'source_read',dependencies:i?[`TASK-${String(i).padStart(3,'0')}`]:[],permitted_paths:['selected-source-scope'],permitted_tools:['Python','SQLite'],allowed_actions:['source_read'],acceptance_checks:['source identity','bounded coverage'],budget:{items:20},stop_condition:'Stop when the recorded source identity no longer matches.'}}));
const observed='2026-09-20T14:24:00Z';
const tools=['Python','Git','SQLite','PDF parser','Word reader','OCR runtime'].map((name,i)=>({tool_id:name,name,description:'Illustrative catalogue entry for visual review.',kind:i<2?'native_tool':'library',layer:'operation',lifecycle:'retained',lanes:[i<2?'local_code':'docs'],action_classes:['read'],readiness:i%3===0?'observed':i%3===1?'package_not_detected':'connection_unverified',execution_state:i===0?'verified':'not_observed',v4_operation_qualification:'not_verified_by_preview',primary:['selected operation'],fallback:[],action_order:1,implementation_owner:'illustrative fixture'}));
const lesson={version_id:'preview-lesson-1',version:1,state:'active',observation:{summary:'Preserve the source identity before comparing a refreshed extract.',scope:{action:'source_read',checks:['source identity','bounded coverage']}}};
export function previewSnapshot(projectId:string,state:string):Snapshot{
 const project=projects.find(p=>p.project_id===projectId);if(projectId&&!project)throw new Error('Choose a project from the illustrative preview list.');
 return{observed_at:observed,engine:{version:'design-preview',phase:'ILLUSTRATIVE_DATA',previous_shutdown:'not_observed'},projects:state==='empty'?[]:projects,
 project:project&&state!=='empty'?{project_id:project.project_id,jobs:{counts:{running:1,queued:1,checkpointed:1,uncertain:1,succeeded:1},recent:[{job_id:'preview-job-1',action:'source_read',phase:'reading',state:'running',updated_at:observed},{job_id:'preview-job-2',action:'pdf_render',phase:'recorded',state:'succeeded',updated_at:observed},{job_id:'preview-job-3',action:'code_query',phase:'checkpoint',state:'checkpointed',updated_at:observed},{job_id:'preview-job-4',action:'research_web_capture',phase:'reconcile',state:'uncertain',updated_at:observed},{job_id:'preview-job-5',action:'source_read',phase:'admitted',state:'queued',updated_at:observed}]},evidence:{object_count:18,total_bytes:262144,receipts:[{receipt_id:'preview-receipt-1',kind:'source_observation',created_at:observed,source_id:'illustrative-source-1'},{receipt_id:'preview-receipt-2',kind:'verification_record',created_at:observed},...Array.from({length:6},(_,i)=>({receipt_id:'preview-receipt-'+(i+3),kind:i%2?'verification_record':'source_observation',created_at:observed,...(i%2?{}:{source_id:'illustrative-source-'+(i+2)}),illustrative:true}))]},plan:{state:'current',title:project.source_root.split('/').at(-1)+' — illustrative Plan',revision:12,total_tasks:tasks.length,truncated:true,counts:{completed:8,active:1,pending:96},tasks:tasks.slice(0,100)},control:{paused:false},accelerator:{revision:1,config:{preference:'cpu',illustrative:true}},plugins:[],learning:{lessons:[lesson,{...lesson,version_id:'preview-lesson-2',version:2,state:'revoked'}],truncated:false},lineage:{events:[{event_id:'preview-event-1',kind:'prompt',provenance:'illustrative_capture'}],total_events:1},memory:{locators:[{locator_id:'preview-locator-1',source_state:'current',source_client_id:'preview-client-1',suppressed:false,locator:{label:'Selected source coverage',reference:{kind:'source',revision:1}}}],truncated:false,head:'illustrative-memory-head'},linked_projects:{links:[],last_project_id:null,truncated:false},continuity:{offers:[],truncated:false},canon:{participants:[],contracts:[],exchanges:[],last_sequence:0,truncated:false,participants_truncated:false,contracts_truncated:false}}:null,
 workers:{state:'observed',accepting:true,initialized_workers:[{pid:101,state:'ready',startup:'acknowledged'},{pid:102,state:'busy',startup:'acknowledged'},{pid:103,state:'ready',startup:'acknowledged'}],outstanding:2,succeeded_operations:18},connections:[{client_id:'preview-client-1',label:'Desktop Stable · illustrative',project_ids:project?[project.project_id]:[],expires_at:'2026-09-20T18:24:00Z',host_observation:{client:{protocol:'MCP',configured_profile:'codex_desktop_stable'}}},{client_id:'preview-client-2',label:'Desktop Beta · illustrative',project_ids:[],expires_at:'2026-09-20T19:24:00Z',host_observation:{client:{protocol:'MCP',configured_profile:'codex_desktop_beta'}}}],inventory:{devices:[{device_id:'preview-device',name:'Illustrative graphics device',vendor:'Example device',total_vram_mib:8192,used_vram_mib:null,temperature_c:null,driver_version:'not_observed',observed_at:observed}],providers:[{runtime_id:'cpu-provider',state:'observed',execution_state:'not_verified_by_preview'}]},active_executions:[{job_id:'preview-job-1',task_id:'TASK-009',plan_revision:12,worker_operations_pending:2}],actions:[{name:'source_read',description:'Read selected source metadata.',workflow:'manage-project-sources',profile:'source_read',permission:'read',mutates:false,required_tools:['Python','SQLite'],worker_operations:[],requires_delta:false,studio_read:true},{name:'plan_read',description:'Read a bounded page of the current Plan.',workflow:'manage-project-plan',profile:'read',permission:'read',mutates:false,required_tools:['SQLite'],worker_operations:[],requires_delta:false,studio_read:true}],plugin_scopes:{lanes:['local_code','docs'],actions:['source_read','plan_read'],hosts:['codex_desktop_stable','codex_desktop_beta']},lane_views:[],tool_catalog:{base_entry_count:tools.length,counts:{retained:tools.length},entries:tools}};
}
export async function previewRead(route:string,payload?:unknown):Promise<unknown>{
 const state=new URLSearchParams(location.search).get('state')??'populated';
 if(state==='loading')return new Promise(()=>{});
 if(state==='error')throw new Error('Design preview: the illustrative connection failed. No engine was contacted.');
 if(route==='session')return{csrf:'illustrative-only'};
 if(route.startsWith('snapshot'))return previewSnapshot(new URLSearchParams(route.split('?')[1]).get('project_id')??'',state);
 if(route!=='read')throw new Error('The design preview never submits state-changing operations.');
 const p=payload as {project_id?:string;action?:string;arguments?:RecordData};const value=previewSnapshot(p?.project_id??'',state),project=value.project;
 switch(p?.action){
  case 'plan_read':{if(!project)return null;const offset=Math.max(0,Number(p.arguments?.offset)||0),limit=Math.min(100,Number(p.arguments?.limit)||100);return{...project.plan,tasks:tasks.slice(offset,offset+limit),truncated:offset+limit<tasks.length}}
  case 'memory_read':return{...project?.memory,locators:project?.memory.locators.filter(v=>JSON.stringify(v).toLowerCase().includes(String(p.arguments?.query??'').toLowerCase()))??[]};
  case 'task_evidence_read':return project?.canon;
  default:throw new Error('This read is not modelled in the design fixture. No engine request was sent.');
 }
}
