'use client';
import {useState} from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'framer-motion';
import {OriginalGlassIconOrb as Orb,OriginalGlassPill as Pill} from './original-glass';
import {SemanticIcon,semanticIconColors,type SemanticIconName} from './semantic-icon';
import {ToolBrowser} from './tool-browser';
import {StudioViewDetail} from './studio-view-detail';
const roles:[string,string,SemanticIconName][]=[['sources','Sources','sources'],['plan','Plan','plan'],['work','Work','work'],['result','Results','results'],['memory','Context','memory']];
const stages=[['Start from the Plan','Read the current task, its intent and scope.','plan'],['Bring the evidence','Select the relevant project material and its references.','sources'],['Choose the tools','Match the task to the appropriate tools and configured connections.','tools'],['Carry out the work','Keep execution inside the selected task and permissions.','work'],['Inspect the result','Record what was produced and what the checks observed.','checks'],['Keep what comes next','Update the project records and return to the current Plan.','memory']] as const;
export function HomeDetailStory({kind,onNavigate,initialView,initialResult,single=false}:{kind:string;onNavigate:(id:string)=>void;initialView?:string;initialResult?:number;single?:boolean}){
 const [step,setStep]=useState(0),[view,setView]=useState(initialView??'Plan'),[result,setResult]=useState(initialResult??0);const reduced=useReducedMotion();
 if(kind==='project')return <div className="detail-project-map"><p className="detail-example-label">EXPLORE THE CONNECTIONS</p><div>{roles.map(([id,label,icon])=><button key={id} onClick={()=>onNavigate(id)}><Orb size={65} color={semanticIconColors[icon]} decorative><SemanticIcon name={icon} size={34}/></Orb><strong>{label}</strong><span>Explore ↗</span></button>)}</div></div>;
 if(kind==='plan'||kind==='work')return <div className="detail-work-story"><p className="detail-example-label">ILLUSTRATIVE WORK SEQUENCE · SELECT A STEP</p><div className="detail-work-steps">{stages.map(([title,,icon],i)=><button key={title} onClick={()=>setStep(i)} aria-pressed={i===step}><Orb size={43} color={semanticIconColors[icon]} decorative><SemanticIcon name={icon}/></Orb><span>{String(i+1).padStart(2,'0')}</span></button>)}</div><AnimatePresence mode="wait"><motion.div key={step} className="detail-step-explanation" initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-15}} transition={{duration:reduced?0:.2}}><span>STEP {step+1} OF {stages.length}</span><h3>{stages[step][0]}</h3><p>{stages[step][1]}</p><div className="detail-signal-track"><motion.i key={step} initial={{scaleX:0}} animate={{scaleX:1}} transition={{duration:reduced?0:.8}}/></div></motion.div></AnimatePresence><Pill onClick={()=>setStep((step+1)%stages.length)} trailing="→">{step===stages.length-1?'Return to the Plan':'Follow the next step'}</Pill></div>;
 if(kind==='result')return <div className="detail-result-story"><p className="detail-example-label">INSPECT AN ILLUSTRATIVE RESULT</p><div className="flow-records">{(['results','sources','checks'] as const).map((icon,i)=><Pill key={icon} leading={<Orb size={43} color={semanticIconColors[icon]} decorative><SemanticIcon name={icon}/></Orb>} active={result===i} aria-pressed={result===i} onClick={()=>setResult(i)}>{['Output','Source trail','Checks'][i]}</Pill>)}</div><AnimatePresence mode="wait"><motion.div className="detail-step-explanation" key={result} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}} transition={{duration:reduced?0:.2}}><h3>{['What was produced','What informed it','What was verified'][result]}</h3><p>{['A report, changed code, prepared data or another deliverable. Its result reference belongs to the task that created it.','The result can retain references to selected code, documents, data, research and other source material. Open the owning source to inspect its identity and snapshot.','Recorded checks state their scope and observations. An unrun check remains unrun; an uncertain result stays visible.'][result]}</p><div className="detail-evidence-links">{(result===0?['Task','Output']:result===1?['Source','Snapshot','Result']:['Check','Observation','Limit']).map((label,i)=><span key={label}><b>{String(i+1).padStart(2,'0')}</b>{label}</span>)}</div></motion.div></AnimatePresence></div>;
 if(kind==='studio')return <div className="detail-studio-story">{!single&&<><header><span>Evidence Lane Studio</span><small>READ-ONLY VIEW GUIDE</small></header><nav aria-label="Studio preview">{['Plan','Jobs','Workers','Evidence','Toolchains','Connections','Learning','Compute','Diagnostics'].map(p=><button key={p} aria-pressed={view===p} onClick={()=>setView(p)}>{p}</button>)}</nav></>}<StudioViewDetail key={view} view={view}/><span className="detail-observer-line">View here · Direct changes through Codex</span></div>;

 return null;
}
