'use client';
import {productRecords} from '../data/product-story';
import workflows from '../data/workflows.json';
import catalogue from '../data/tool-browser.json';
import {ToolBrowser} from './tool-browser';
import {ToolIdentity,ToolLogoRow,toolName} from './tool-identity';
import {SemanticIcon,type SemanticIconName} from './semantic-icon';
import {OriginalGlassIconOrb as Orb,OriginalGlassPill as Pill} from './original-glass';

export const subjectInfo:Record<string,{name:string;icon:SemanticIconName;summary:string;items:string[];steps:string[]}>={
 'steer-plan':{name:'Steer the Plan',icon:'plan',summary:'Change the affected future work while retaining what the project has already completed.',items:['State the changed outcome or requirement through Codex.','Preview the relevant scope and checkpoint affected work safely.','Replace only the affected active or queued task contracts in the current Plan.','Keep completed history and reject completion from a superseded task.'],steps:['Describe the change','Safe checkpoint','Revised future work']},
 'source-scope':{name:'Source scope',icon:'sources',summary:'The selected material and references the current operation is allowed to use.',items:['Source selection identifies the relevant project material.','The operation uses its declared files, snapshots and lane references.','Permissions and freshness are checked for the selected route.','Adding a source does not automatically prepare every file or grant unlimited access.'],steps:['Selected material','Declared scope','Attributed evidence']},
 intent:{name:'Intent',icon:'workflow',summary:'The outcome you ask Codex to help achieve. Evidence Lane uses the selected project, sources and permissions to determine what the request needs.',items:['State the result you want and the material it concerns.','An informational question reads project evidence without changing the Plan.','A change in direction updates affected future work while preserving completed history.','Execution follows the selected task and records the outcome and its checks.'],steps:['Your request','Project context','Read, steer or execute']},
 worker:{name:'Worker',icon:'worker',summary:'An engine-owned OS process carrying out bounded tool operations for project work.',items:['Workers receive an allowed operation and its bounded inputs.','The operation declares its tools, file scope, output limits and error handling.','The engine coordinates queued work and records the returned result.','A worker is a tool process. The current catalogue does not establish that a process is running.'],steps:['Scoped operation','Tool process','Returned result']},
 engine:{name:'Local engine',icon:'engine',summary:'The persistent local service that connects Codex, project records, tools and the Studio observer.',items:['The engine exposes the product operations through the local API, SDK and MCP.','It selects the operation route and manages bounded worker processes.','Each project keeps its separate records; one writer owns project changes.','Studio reads the engine’s observations. Project changes are directed through Codex.'],steps:['Codex request','Engine operation','Recorded observations']},
 plugin:{name:'Plugin',icon:'plugin',summary:'The Codex-managed Evidence Lane package provides the public workflows, native connection and supported hooks.',items:['24 public skills describe meaningful project intentions.','295 declared actions connect those workflows to the engine.','First detection provisions the shared engine, Studio and required local toolchain.','The 12 supported hook events contain 48 separate stage rows. Hooks are disabled by default and are enabled by the user.'],steps:['Select a workflow','Connect the engine','Run the scoped action']},
 resume:{name:'Return',icon:'resume',summary:'Resume the explicitly selected project using its current Plan and attributed saved context.',items:['Resolve the selected project and exact session references.','Read the current Plan and relevant source and evidence state.','Keep conversation history, project memory and lessons in their own records.','Choose the next eligible task or direct a new steer through Codex.'],steps:['Select project','Check saved context','Continue work']},
 recovery:{name:'Recovery',icon:'recovery',summary:'Recover a coherent state of the project’s separate records through the declared recovery workflow.',items:['Backups coordinate the separate lane databases and files.','Recorded lane heads and references describe the coherent snapshot.','Recovery preserves original project bytes and uses an explicitly selected destination.','Recovery availability and verification must be checked for the selected snapshot.'],steps:['Selected snapshot','Coherent records','Verified recovery']},
 records:{name:'Inspect records',icon:'records',summary:'Inspect the separate records that keep the project understandable over time.',items:['The Plan owns ordered work. Conversation history owns attributed dialogue references.','Task exchanges retain sender and receiver ownership.','Project memory retains context; Learning retains lessons from verified work.','Sources, receipts and project links preserve their own evidence and references.'],steps:['Choose a record','Inspect its evidence','Follow its references']},
 'host:stable':{name:'Codex Desktop Stable',icon:'studio',summary:'The stable desktop host profile for Evidence Lane on a persistent local Windows PC.',items:['The host connects through the supported native plugin route.','The shared engine, Studio and toolchain serve the selected project.','Project and client identities are verified through the supported connection.','This profile description is not proof of an installed or connected session.'],steps:['Stable host','Native plugin','Shared local engine']},
 'host:beta':{name:'Codex Desktop Beta',icon:'studio',summary:'The beta desktop host profile for Evidence Lane on a persistent local Windows PC.',items:['The beta profile retains its own exact client identity.','It connects to the same shared local runtime model.','Supported host connection and compatibility are checked before work.','The beta label distinguishes the profile; it does not imply different project permissions.'],steps:['Beta host','Native plugin','Shared local engine']}
};
export function SubjectDetail({id,onNavigate}:{id:string;onNavigate:(id:string)=>void}){
 const subject=subjectInfo[id];if(!subject)return null;
 return <section className="subject-detail"><div className="subject-mini-flow" aria-label="Illustrative sequence">{subject.steps.map((step,i)=><span key={step}><b>{String(i+1).padStart(2,'0')}</b>{step}</span>)}</div><ul className="subject-facts">{subject.items.map(item=><li key={item}>{item}</li>)}</ul>{id==='worker'&&<ToolBrowser initialMode="workers"/>}{id==='records'&&<div className="subject-records">{productRecords.map(record=><Pill key={record.id} leading={<Orb color={record.color} decorative><SemanticIcon name={record.icon}/></Orb>} onClick={()=>onNavigate('record:'+record.id)}>{record.name}</Pill>)}</div>}{id==='intent'&&<blockquote>“Use the selected source material to prepare the next deliverable, and show what was checked.”</blockquote>}{id==='plugin'&&<Pill onClick={()=>onNavigate('workflows')}>Explore the 24 public workflows ↗</Pill>}</section>
}
export function RecordDetail({id}:{id:string}){const record=productRecords.find(r=>r.id===(id==='network'?'links':id));if(!record)return null;return <section className="subject-detail"><h3>What this record owns</h3><div className="subject-mini-flow">{record.contains.map((item,i)=><span key={item}><b>{String(i+1).padStart(2,'0')}</b>{item}</span>)}</div><p>{record.boundary}</p><blockquote>{record.prompt}</blockquote></section>}
export function WorkflowDetail({id,onNavigate}:{id:string;onNavigate:(id:string)=>void}){const workflow=workflows.find(w=>w.id===id);if(!workflow)return <p>This workflow is not in the current public catalogue.</p>;return <section className="subject-detail"><p className="flow-detail-lead">{workflow.outcome}</p><blockquote>{workflow.example}</blockquote><h3>What this workflow does</h3><ol className="subject-action-list">{workflow.stages.map(stage=><li key={stage.action}><strong>{stage.action.replaceAll('_',' ')}</strong><p>{stage.description}</p><small>{stage.mutates?'Changes state within its permitted scope':'Reads without changing project state'}</small></li>)}</ol><p className="atlas-detail-note">{workflow.limitation}</p><Pill onClick={()=>onNavigate('workflows')}>Browse other workflows ↗</Pill></section>}
export function SingleToolDetail({id,onNavigate}:{id:string;onNavigate:(id:string)=>void}){const tool=catalogue.tools.find(t=>t.id===id);if(!tool)return <p>This item is a source or route grouping. Open the tools catalogue to inspect its declared members.</p>;const actions=catalogue.operations.filter(a=>tool.operations.includes(a.id));return <section className="subject-detail"><p className="flow-detail-lead">{toolName(id)} is a {tool.kind.replaceAll('_',' ')} in the shared toolchain. {tool.provisioning}.</p><div className="subject-mini-flow"><span>Selected operation</span><span><ToolIdentity id={id}/>{toolName(id)}</span><span>Scoped result</span></div><h3>Packages and delivery</h3><ul className="subject-facts">{tool.packages.length?tool.packages.map(p=><li key={p}>{p}</li>):<li>Provided by the declared native tool, internal code or adapter.</li>}<li>{tool.required?'Part of the required shared Windows bundle.':tool.external?'Requires explicit external service configuration.':'Available through its declared operation-specific route.'}</li></ul><h3>Where it is used</h3><div className="subject-action-list">{actions.map(a=><article key={a.id}><h4>{a.id.replaceAll('_',' ')}</h4><p>{a.description}</p><small>{a.profile} · {a.mutates?'Changes state':'Read only'}</small>{a.routes.filter(r=>r.tools.includes(id)).map(r=><p className="atlas-detail-note" key={r.id}>{r.reason} · {r.fidelity}</p>)}</article>)}{!actions.length&&<p>Retained in the shared catalogue; no direct action route references this entry in this source projection.</p>}</div><p className="atlas-detail-note">These are declared capabilities. Installation, service access and execution are checked when the operation runs.</p><Pill onClick={()=>onNavigate('tools')}>Inspect the full tool catalogue ↗</Pill></section>}
