'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'framer-motion';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import knowledge from '../data/home-knowledge.json';
import {GlassPopup} from './glass';
import{SourceLaneIcon}from'./source-lane-icon';
import {SemanticIcon,semanticIconColors,type SemanticIconName} from './semantic-icon';
import {InteractiveBrainOrb} from './interactive-brain-orb';
import {useMotion} from './experience';
import styles from './home-universe.module.css';
const Scene=dynamic(()=>import('./project-universe-scene').then(m=>m.ProjectUniverseScene),{ssr:false,loading:()=> <img className="universe-poster" src="/home-current/project-nexus.png" alt=""/>});
const brands:Record<string,{name:string;file:string;ids:string[]}>={git:{name:'Git',file:'git.svg',ids:['Git','GitPython']},github:{name:'GitHub',file:'github.png',ids:['Git']},python:{name:'Python',file:'python.svg',ids:['Python']},nodejs:{name:'Node.js',file:'nodejs.svg',ids:['NodeJS_TypeScript']},word:{name:'Word',file:'word.svg',ids:['DOCX_OpenXML']},excel:{name:'Excel',file:'excel.svg',ids:['openpyxl','LibreOffice','python_calamine']},powerpoint:{name:'PowerPoint',file:'powerpoint.svg',ids:['PPTX_OpenXML']}};
const workflowIcons:Record<string,SemanticIconName>={'evidence-lane':'project','open-project-session':'project','execute-project-plan':'work','manage-project-plan':'plan','manage-project-sources':'sources','exchange-task-evidence':'connections','manage-project-memory':'memory','manage-project-lessons':'memory','inspect-project-instructions':'plan','configure-project-workflow':'workflow','classify-project-work':'workflow','retrieve-project-evidence':'sources','refresh-project-evidence':'sources','inspect-project-connectors':'connections','configure-project-connector':'connections','revoke-project-connector':'connections','select-project-tools':'tools','select-project-storage':'sources','inspect-project-evidence-map':'project','link-project-evidence-network':'connections','handoff-project-work':'connections','recover-project-state':'results','close-project-session':'project','run-project-lifecycle':'workflow'};
const acts=[
 {short:'Intent',title:'The whole project. Still connected.',summary:'Evidence Lane connects Codex to persistent project work: selected sources, explicit plans, scoped tools and inspectable results.',icon:'project' as const,details:['The public registry contains 24 first-class workflows. Each owns its actual actions; the product is not limited to three example use cases.','One typed operation registry connects the skills, SDK and MCP surface to the persistent engine.','The website describes inspected source contracts. It is not a live project client or evidence that installation has been qualified.']},
 {short:'Enter',title:'Your request finds its project.',summary:'Start with the host, the selected project and the current operating context. The engine verifies the route before work moves.',icon:'workflow' as const,details:['The Windows plugin-first contract provisions the shared engine, Studio and required local toolchain after actual detection.','Boot or Resume checks the exact project/session references and locked operating policy. Host labels do not independently attest a native task.','The supported host is persistent local Windows Codex Desktop, in Stable or Beta.','The selected project state remains on persistent local storage.']},
 {short:'Evidence',title:'Many sources. Distinct responsibilities.',summary:'Bring in the sources your project actually needs. Each source sector and project record keeps its own identity, database and files.',icon:'sources' as const,details:['The current source registry implements 13 sectors, including local/GitHub code, Word, Excel, PowerPoint, structured data, Tableau, Power BI, PDF/OCR, images/media, research/web, artifacts and custom sources.','Custom-source instances can be explicitly selected more than once. Connector grants remain a separate concern.','Plan, conversation history, task exchange, Project Memory, Learning, Sources, Receipts and the project evidence map retain separate ownership.','Session records are owned through Receipts; the additional sessions source family is not a ninth business authority.','Registration, preparation, indexing, query and refresh are different operations. A source being registered does not establish content-index completeness.']},
 {short:'Orchestrate',title:'The Plan meets the right tools.',summary:'The current task and its operation determine the route. Scope, source identity, permissions, readiness and budgets are checked before work is admitted.',icon:'tools' as const,details:['The current operation map contains 297 registered operations and 103 retained tools/services. An operation selects its primary route and declared alternatives before invocation.','The engine owns one writer per project and coordinates bounded OS worker processes. Workers are not AI subagents.','The work loop reads the current Plan, admits the eligible task, performs bounded queries/tool work, verifies the result and records its effects.','Project-selected validation follows that project’s revision and changed paths. Plugin maintainer CI is not imposed on unrelated projects.','CPU, CUDA, ROCm and DirectML environments have specific operation coverage and measured compatibility/readiness requirements. Catalog membership does not prove execution.']},
 {short:'Verify',title:'A result with a trail you can open.',summary:'Outputs, checks and source references stay inspectable. Verified work updates its owning records and the context for what comes next.',icon:'results' as const,details:['Verified exit checks the task revision, contract, effect confirmations and recorded verification. Stale worker completion is rejected.','Receipts, result references, Learning and bounded Project Memory references update through their respective owners.','A read-only question does not change the Plan. A semantic steer checkpoints affected work and replaces the affected active/queued contracts.','Historical receipts describe recorded checks. They do not reverify current source bytes or imply native Goal completion.']},
 {short:'Continue',title:'See the work. Keep the context.',summary:'Studio gives a read-only view of the project. Exact session, task and evidence references support continuation, handoff and recovery.',icon:'memory' as const,details:['Studio’s current views include Plan, Jobs, Workers, Evidence, Toolchains, client Connections, Learning, Compute and Diagnostics. Humans inspect; Codex requests mutations.','Session resume, client handoff and task evidence exchange have separate ownership and exact references. A title or process ID cannot establish native continuity.','Coherent backup preserves the separate project lanes. Recovery uses the declared safe boundary and fresh destinations; it does not revive the removed accepted-version rollback workflow.','The next eligible task is selected from the current Plan after verified work. Uncertain effects remain explicit rather than being relabeled successful.']}
];
function Orb({name,size=32}:{name:SemanticIconName;size?:number}){return <span className={styles.semanticOrb} style={{'--orb-tone':semanticIconColors[name],width:size+18,height:size+18} as CSSProperties}><SemanticIcon name={name} size={size}/></span>}
function Brand({id,size=34}:{id:string;size?:number}){const b=brands[id];return <img className={styles.brand} src={`/brands/${b.file}`} alt={b.name} width={size} height={size}/>}
export function HomeUniverse(){
 const {paused,toggle}=useMotion();const systemReduced=useReducedMotion();const [staticView,setStaticView]=useState(false);const still=Boolean(systemReduced)||staticView;const root=useRef<HTMLDivElement>(null);const[phase,setPhase]=useState(0);const[modal,setModal]=useState<'workflows'|'sources'|'tools'|'act'|'tool'|null>(null);const[detail,setDetail]=useState(0);const[workflowIndex,setWorkflowIndex]=useState(0);const[search,setSearch]=useState('');const[operation,setOperation]=useState('');const[hovered,setHovered]=useState<string|null>(null);const[tool,setTool]=useState('python');const[record,setRecord]=useState(0);const[panel,setPanel]=useState('Plan');
 const active=Math.min(5,Math.floor(phase));const workflow=knowledge.workflows[workflowIndex];const action=operation&&workflow.ownedActions.includes(operation)?operation:workflow.ownedActions[0];const route=knowledge.operations[action as keyof typeof knowledge.operations];const selectedAct=acts[detail];
 useEffect(()=>{let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const nodes=root.current?.querySelectorAll<HTMLElement>('[data-act]');if(!nodes)return;let value=0;const line=innerHeight*.43;nodes.forEach((node,i)=>{const r=node.getBoundingClientRect();if(r.top<=line)value=i+Math.max(0,Math.min(.999,(line-r.top)/r.height));});setPhase(Math.min(5.999,value));});};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[]);
 const openAct=(i:number)=>{setDetail(i);setModal('act')};const showTool=(id:string)=>{setTool(id);setModal('tool')};const go=(i:number)=>document.getElementById(`universe-act-${i}`)?.scrollIntoView({behavior:still?'instant':'smooth'});const enter={initial:{opacity:0,y:35},whileInView:{opacity:1,y:0},viewport:{amount:.2},transition:{duration:still?0:.65,ease:'easeOut' as const}};
 const filtered=knowledge.workflows.filter(w=>`${w.title} ${w.description} ${w.outcome}`.toLowerCase().includes(search.toLowerCase()));
 return <main id="main" className={`${styles.home} home-universe`} data-static={still}>
  <div className={styles.story} ref={root}><div className={styles.sceneLayer}>{!still&&<Scene phase={Math.min(5,phase)} paused={paused||modal!==null} hovered={hovered} onTool={showTool} onProject={()=>openAct(active)} onUnavailable={()=>setStaticView(true)}/>}</div>
   <nav className={styles.chapterNav} aria-label="Project story chapters">{acts.map((a,i)=><a key={a.short} href={`#universe-act-${i}`} aria-current={active===i?'step':undefined} onClick={e=>{e.preventDefault();go(i)}}><span>{String(i+1).padStart(2,'0')}</span><i/><b>{a.short}</b></a>)}</nav>
   <section id="universe-act-0" data-act className={`${styles.act} ${styles.hero}`}><motion.div {...enter} className={styles.heroCopy}><p className={styles.eyebrow}>EVIDENCE LANE / A PERSISTENT PROJECT FOR CODEX</p><h1>The whole project.<br/><em>Still connected.</em></h1><p className={styles.lead}>Sources. Plans. Tools. Results.<br/>A project that can continue beyond the conversation.</p><div className={styles.heroActions}><motion.button whileHover={still?{}:{y:-5,scale:1.025}} whileTap={still?{}:{scale:.98}} className={styles.primary} onClick={()=>{setSearch('');setModal('workflows')}}><Orb name="workflow" size={24}/><span>Explore all {knowledge.counts.workflows} workflows</span><b>↗</b></motion.button><button className={styles.secondary} onClick={()=>go(1)}>Follow the full lifecycle <span>↓</span></button></div><div className={styles.scopeStrip}><button onClick={()=>setModal('sources')}><strong>{knowledge.counts.sourceLanes}</strong><span>source sectors</span></button><button onClick={()=>setModal('tools')}><strong>{knowledge.counts.tools}</strong><span>retained tools & services</span></button><button onClick={()=>openAct(3)}><strong>{knowledge.counts.operations}</strong><span>registered operations</span></button></div><p className={styles.sourceNote}>Current source contracts · Installation and runtime readiness are separate.</p></motion.div>{still&&<img className={styles.staticArt} src="/home-current/project-nexus.png" alt="Original Blender project instrument."/>}</section>
   <section id="universe-act-1" data-act className={`${styles.act} ${styles.left}`}><motion.div {...enter} className={styles.copy}><p className={styles.eyebrow}>01 / INTENT, HOST AND PROJECT</p><h2>Your request<br/><em>finds its project.</em></h2><p>Start through the appropriate public workflow. Establish the host route, selected project and current operating context before work begins.</p><div className={styles.hostDocks}>{['Codex Desktop Stable','Codex Desktop Beta'].map((h,i)=><motion.button key={h} whileHover={still?{}:{y:-4}} onClick={()=>openAct(1)}><SemanticIcon name={i===0?'studio':i===1?'work':'connections'} size={24}/><span>{h}</span></motion.button>)}</div><button className={styles.connectionButton} onClick={()=>openAct(1)}><Orb name="project" size={25}/><span><strong>Plugin-first entry</strong><small>Shared engine, Studio and toolchain</small></span><b>↗</b></button><p className={styles.note}>Windows has the visible Studio observer, with Codex Desktop Stable and Beta host profiles.</p></motion.div>{still&&<img className={styles.staticArt} src="/home-current/project-nexus.png" alt="The persistent project entry instrument."/>}</section>
   <section id="universe-act-2" data-act className={`${styles.act} ${styles.right}`}><motion.div {...enter} className={styles.copy}><p className={styles.eyebrow}>02 / SOURCES AND SEPARATE RECORDS</p><h2>Many sources.<br/><em>Clear ownership.</em></h2><p>Bring in the material your project needs. Its origin, current snapshot and recorded coverage stay visible. Each owning lane keeps its own database and files.</p><div className={styles.sourceOrbitButtons}>{knowledge.sources.map(s=><motion.button key={s.id} whileHover={still?{}:{y:-3,scale:1.025}} onClick={()=>setModal('sources')}>{s.id==='docs'?<Brand id="word" size={24}/>:s.id==='data_excel'?<Brand id="excel" size={24}/>:s.id==='ppt'?<Brand id="powerpoint" size={24}/>:s.id==='github_code'?<Brand id="github" size={24}/>:s.id==='local_code'?<Brand id="git" size={24}/>:<SourceLaneIcon lane={s.id} size={23} decorative/>}<span>{s.title}</span></motion.button>)}</div><button className={styles.detailButton} onClick={()=>openAct(2)}>Inspect the separate project records <span>↗</span></button></motion.div>{still&&<img className={styles.staticArt} src="/home-current/project-nexus.png" alt="Separate evidence records connected to one project."/>}</section>
   <section id="universe-act-3" data-act className={`${styles.act} ${styles.left}`}><motion.div {...enter} className={styles.copy}><p className={styles.eyebrow}>03 / PLAN, SCOPE AND TOOL ROUTING</p><h2>The next task.<br/><em>The right route.</em></h2><p>The Plan sets the work boundary. The engine checks the exact operation, source, permissions, tools and budgets before admitting it.</p><button className={styles.selectedWorkflow} onClick={()=>{setSearch('');setModal('workflows')}}><Orb name={workflowIcons[workflow.id]} size={26}/><span><small>SELECTED PUBLIC WORKFLOW</small><strong>{workflow.title}</strong></span><b>↗</b></button><ol className={styles.workLoop}>{['Current Plan','Bounded admission','Selected tools','Execute','Verify','Record & learn'].map((s,i)=><li key={s}><button onClick={()=>openAct(i<2?3:i<4?3:4)}><span>{String(i+1).padStart(2,'0')}</span>{s}<i>↗</i></button></li>)}</ol><button className={styles.detailButton} onClick={()=>setModal('tools')}>Inspect actual operation tool routes <span>↗</span></button></motion.div>{still&&<img className={styles.staticArt} src="/home-current/project-nexus.png" alt="An operation is selected within the current project scope."/>}</section>
   <section id="universe-act-4" data-act className={`${styles.act} ${styles.right}`}><motion.div {...enter} className={styles.copy}><p className={styles.eyebrow}>04 / VERIFICATION AND RECORDED RESULTS</p><h2>Open the result.<br/><em>Follow its evidence.</em></h2><p>Verification connects the output to the task and the checks that actually ran. The resulting records remain distinct and inspectable.</p><div className={styles.recordTabs} aria-label="Inspect result responsibilities">{[['results','Results'],['sources','Sources'],['checks','Checks']].map(([icon,label],i)=><motion.button key={label} onClick={()=>setRecord(i)} aria-pressed={record===i} whileHover={still?{}:{y:-3}}><Orb name={icon as SemanticIconName} size={24}/>{label}</motion.button>)}</div><AnimatePresence mode="wait"><motion.div className={styles.recordContent} key={record} initial={{opacity:0,x:22}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-22}} transition={{duration:still?0:.25}}><h3>{['Addressed output','Attributed sources','Recorded verification'][record]}</h3><p>{['The output stays associated with its owning task and result reference. Inspect it without inferring that every possible check was run.','Follow the original source and snapshot references. Recorded evidence does not silently become a fresh observation of changed files.','Inspect the actual operation-specific checks, scope and limitations. Failed or uncertain effects remain visible.'][record]}</p></motion.div></AnimatePresence><button className={styles.detailButton} onClick={()=>openAct(4)}>How verified exit updates the project <span>↗</span></button></motion.div>{still&&<img className={styles.staticArt} src="/home-current/project-nexus.png" alt="Recorded output, source and verification relationships."/>}</section>
   <section id="universe-act-5" data-act className={`${styles.act} ${styles.right}`}><motion.div {...enter} className={styles.copy}><p className={styles.eyebrow}>05 / OBSERVE, CONTINUE AND RECOVER</p><h2>See the work.<br/><em>Keep the context.</em></h2><p>Studio is the read-only observatory. Exact saved references support the next session, a selected handoff or a coherent recovery.</p><div className={styles.studioWindow}><header><Orb name="studio" size={22}/><span>Windows Studio</span><small>Read-only</small></header><div className={styles.studioPills}>{knowledge.studioPanels.map(p=><button key={p} aria-pressed={panel===p} onClick={()=>setPanel(p)}>{p}</button>)}</div><AnimatePresence mode="wait"><motion.div key={panel} className={styles.studioReadout} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:still?0:.2}}><strong>{panel}</strong><p>{panel==='Connections'?'Inspect host client sessions connected to the engine. Connector grants remain separate.':`Inspect the project’s ${panel.toLowerCase()} observations through its owning read-only view.`}</p><span>Illustrative view · No fabricated live metrics</span></motion.div></AnimatePresence></div><button className={styles.detailButton} onClick={()=>openAct(5)}>Explore continuity, handoff and recovery <span>↗</span></button></motion.div>{still&&<img className={styles.staticArt} src="/home-current/project-nexus.png" alt="The project retains its evidence across sessions."/>}</section>
  </div>
  <section className={styles.close}><p className={styles.eyebrow}>EVIDENCE LANE / YOUR WORK, WITH ITS CONTEXT</p><h2>Choose an intention.<br/><em>Keep the whole project in view.</em></h2><button className={styles.primary} onClick={()=>{setSearch('');setModal('workflows')}}><Orb name="workflow" size={25}/>Explore all 24 public workflows <span>↗</span></button><div className={styles.brandRow}>{Object.keys(brands).map(id=><button key={id} onClick={()=>showTool(id)} onMouseEnter={()=>setHovered(id)} onMouseLeave={()=>setHovered(null)} aria-label={`Inspect ${brands[id].name} role`}><Brand id={id}/></button>)}</div><p className={styles.note}>Source candidate {knowledge.version}. Full installed qualification remains separate from the source registry.</p></section>
  <div className={styles.controls}><span>{acts[active].short}</span><button onClick={toggle} aria-pressed={paused}>{paused?'Play motion':'Pause motion'}</button><button onClick={()=>setStaticView(!staticView)} disabled={Boolean(systemReduced)}>{systemReduced?'Reduced motion':staticView?'3D view':'Static view'}</button><button onClick={()=>openAct(active)}>Chapter details ↗</button></div>
  <GlassPopup open={modal==='workflows'} onClose={()=>setModal(null)} title="24 ways into your project" kicker="CURRENT PUBLIC WORKFLOW REGISTRY" description="Choose the actual user-intent workflow. Each retains its owned actions and boundaries." leading={<Orb name="workflow" size={44}/>}><label className={styles.searchLabel}>Find a workflow<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Session, Plan, sources, memory, tools, recovery…"/></label><div className={styles.workflowGrid}>{filtered.map(w=><motion.button key={w.id} whileHover={still?{}:{y:-4}} onClick={()=>{setWorkflowIndex(knowledge.workflows.findIndex(x=>x.id===w.id));setOperation('');setModal('tools')}}><Orb name={workflowIcons[w.id]} size={25}/><span><strong>{w.title}</strong><small>{w.actionCount} owned actions</small></span><i>↗</i></motion.button>)}</div>{!filtered.length&&<p>No matching workflow. Try a broader term.</p>}</GlassPopup>
  <GlassPopup open={modal==='sources'} onClose={()=>setModal(null)} title="Sources and their owning records" kicker="CURRENT IMPLEMENTED SOURCE SECTORS" description="The selected source set determines what is prepared and processed. Each owning lane remains separate." leading={<Orb name="sources" size={44}/>}><div className={styles.sourceDetailGrid}>{knowledge.sources.map(s=><article key={s.id}><SourceLaneIcon lane={s.id} size={26} decorative/><h3>{s.title}</h3><p>Registered source sector with its own current contract, database and files.</p><code>{s.id}</code></article>)}</div><h3 className={styles.subhead}>Distinct project records</h3><div className={styles.authorityRow}>{knowledge.authorities.map(a=><span key={a.id}>{a.title}</span>)}</div><p className={styles.note}>{knowledge.technicalSessionOwner}</p><InteractiveBrainOrb icons={[]}/></GlassPopup>
  <GlassPopup open={modal==='tools'} onClose={()=>setModal(null)} title={workflow.title} kicker="EXACT SOURCE-REGISTERED OPERATION ROUTES" description={workflow.outcome} leading={<Orb name={workflowIcons[workflow.id]} size={44}/>}><div className={styles.toolInspector}><section><label className={styles.searchLabel}>Owned operation<select value={action} onChange={e=>setOperation(e.target.value)}>{workflow.ownedActions.map(a=><option key={a} value={a}>{a.replaceAll('_',' ')}</option>)}</select></label><p>{workflow.limitation}</p><h3>Registered route members</h3>{route.routes.map(r=><article key={r.id}><strong>{r.id}</strong><div className={styles.toolChips}>{r.tools.map(t=><span key={t}>{t}</span>)}</div><p>{r.systems.join(' · ')} · Provider: {r.provider}</p></article>)}</section><aside><InteractiveBrainOrb icons={[]}/><p className={styles.note}>This inspection reads a source projection. It does not test current grants, hardware or installed readiness. Listed tools are route members, not a claim that they all execute.</p><p className={styles.note}>{knowledge.counts.tools} retained tools/services · {knowledge.counts.operations} registered operations · {knowledge.counts.providers} provider environments</p></aside></div><button className={styles.detailButton} onClick={()=>{setSearch('');setModal('workflows')}}>Choose another public workflow ↗</button></GlassPopup>
  <GlassPopup open={modal==='act'} onClose={()=>setModal(null)} title={selectedAct.title} kicker="THE CURRENT PLUGIN AND STUDIO STORY" description={selectedAct.summary} leading={<Orb name={selectedAct.icon} size={44}/>}><div className={styles.detailGrid}><section><h3>What the implementation does</h3><ol>{selectedAct.details.map(d=><li key={d}>{d}</li>)}</ol><p className={styles.note}>Grounded in the current plugin/Studio source and its registered contracts.</p></section><aside><InteractiveBrainOrb icons={[]}/></aside></div></GlassPopup>
  <GlassPopup open={modal==='tool'} onClose={()=>setModal(null)} title={brands[tool].name} kicker="TOOL OR APPLICATION IDENTITY" description={['word','excel','powerpoint'].includes(tool)?'This product mark identifies the supported application format. The owning operation selects the actual processing tools.':'The actual branded tool identity, shown within the project’s source and tool story.'} leading={<Brand id={tool} size={58}/>}><div className={styles.detailGrid}><section><h3>Current related tool entries</h3>{knowledge.tools.filter(t=>brands[tool].ids.includes(t.id)).map(t=><article className={styles.toolEntry} key={t.id}><h3>{t.id}</h3><p>Kind: {t.kind.replaceAll('_',' ')}</p><p>Provisioning: {t.provisioning.replaceAll('_',' ')}</p><p>Source-reported installation: {t.installation.replaceAll('_',' ')} · Execution: {t.execution.replaceAll('_',' ')}</p></article>)}<p>Use the selected public workflow and exact operation to inspect its route. A logo does not establish a live connection or current readiness.</p><button className={styles.detailButton} onClick={()=>setModal('tools')}>Inspect operation routes ↗</button></section><aside><InteractiveBrainOrb icons={[]}/></aside></div></GlassPopup>
 </main>;
}
