'use client';
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {useMotion} from './experience';
import {motion,AnimatePresence} from 'framer-motion';
import {InteractiveBrainOrb} from './interactive-brain-orb';
import {GlassPopup} from './glass';
import styles from './home-cinematic.module.css';
const World=dynamic(()=>import('./evidence-current-scene').then(m=>m.EvidenceCurrentScene),{ssr:false,loading:()=> <img className="scene-poster" src="/home-current/gather.png" alt=""/>});
const brands:Record<string,{label:string;file:string}>={git:{label:'Git',file:'git.svg'},github:{label:'GitHub',file:'github.png'},python:{label:'Python',file:'python.svg'},nodejs:{label:'Node.js',file:'nodejs.svg'},word:{label:'Word',file:'word.svg'},excel:{label:'Excel',file:'excel.svg'},powerpoint:{label:'PowerPoint',file:'powerpoint.svg'}};
const examples=[
 {name:'Develop a feature',kind:'CODE PROJECT',icons:['git','github','python','nodejs'],sources:['Selected repository','Feature requirements','Project checks'],plan:['Understand the selected code','Implement the bounded change','Run the relevant checks'],tools:[['git','Inspect selected history'],['python','Read and validate source'],['nodejs','Run project-selected checks']],result:'A bounded code change',resultBody:'The changed files, the task scope and the checks that actually ran remain connected.',artifact:['Selected source paths','Change and output references','Recorded verification']},
 {name:'Build a report',kind:'RESEARCH & DATA PROJECT',icons:['excel','word','python'],sources:['Selected workbook','Research material','Previous report'],plan:['Inspect the selected evidence','Develop the report','Check the output and references'],tools:[['excel','Selected workbook format'],['python','Inspect and transform data'],['word','Document output format']],result:'A source-linked report',resultBody:'The report keeps its data and research references alongside the recorded output checks.',artifact:['Workbook and research references','Addressed document output','Rendering and content checks']},
 {name:'Create a presentation',kind:'PRESENTATION PROJECT',icons:['powerpoint','excel','python'],sources:['Selected brief','Supporting spreadsheet','Reference presentation'],plan:['Read the brief and evidence','Create the presentation','Render and inspect the slides'],tools:[['excel','Supporting workbook format'],['python','Structured content tools'],['powerpoint','Presentation output format']],result:'An inspectable presentation',resultBody:'The slides can be reviewed together with their source material, rendering and declared limitations.',artifact:['Brief and evidence bindings','Presentation artifact','Render and output observations']}
];
const chapters=[
 {name:'Begin',title:'Keep moving. Keep the evidence.',summary:'Evidence Lane connects selected sources, a current Plan and recorded results in a persistent project for Codex.',facts:['Start with a request in Codex. The relevant public workflow routes that intent through the typed engine operations.','On the supported Windows path, plugin first detection provisions the shared engine, Studio and required local toolchain.','Codex requests project changes. Studio gives humans a visible, read-only view of the work.','The source contracts distinguish installation, configuration and measured execution. This interactive website does not establish any of those runtime states.']},
 {name:'Gather',title:'Choose what belongs.',summary:'Select the sources for one project. Keep their identity and origin as they enter the work.',facts:['Source files retain their selected source location.','Project state has a separate durable root and separately owned records.','Registration is followed by bounded preparation and source work; registration alone is not indexing.']},
 {name:'Plan',title:'Give the next step a shape.',summary:'Turn the requested outcome into ordered tasks with explicit scope, tools and acceptance checks.',facts:['One current Plan determines task order and eligibility.','Each task has its own source route, scope and verification requirements.','A change of direction checkpoints affected work and updates the relevant contracts while preserving completed history.']},
 {name:'Work',title:'The right route through the work.',summary:'The persistent engine checks the selected task and chooses an eligible tool route before carrying out bounded work.',facts:['The current task revision, source binding and permissions are checked before admission.','The owning operation selects required local tools or explicitly configured adapters.','Owned operating-system workers execute the tools. They are not additional AI agents.','A failed or uncertain effect is handled through its real recovery path, not a silent retry.']},
 {name:'Verify',title:'Open the result. Follow its trail.',summary:'Inspect the output together with its sources and the checks that were recorded.',facts:['The output remains addressed and associated with the task that produced it.','Verification records describe the checks that actually ran and their limits.','Historical verification is not a fresh check of today’s source bytes.']},
 {name:'Continue',title:'A new conversation. Your project, continued.',summary:'Return to the selected project with its Plan, evidence and useful context still available.',facts:['Resume checks the exact saved project and session context.','Project Memory keeps attributed references; verified work supplies project-local lessons.','Instructions, conversation records, source evidence, task exchanges and lessons keep separate ownership.','Changed sources need the owning refresh workflow; changed intent needs a safe Plan steer.']}
];
function BrandIcon({name,size=30}:{name:string;size?:number}){const b=brands[name];return <img src={`/brands/${b.file}`} alt={b.label} width={size} height={size} className={styles.brandIcon}/>}
export function HomeCinematic(){
 const {paused,toggle}=useMotion();const root=useRef<HTMLDivElement>(null);const [progress,setProgress]=useState(0);const [mode,setMode]=useState(0);const [inspection,setInspection]=useState(0);const [detail,setDetail]=useState<number|null>(null);const [task,setTask]=useState(0);const [resumed,setResumed]=useState(false);const [reduced,setReduced]=useState(false);const [credits,setCredits]=useState(false);const [manualStatic,setManualStatic]=useState(false);const staticMode=reduced||manualStatic;
 const current=examples[mode];const active=Math.min(5,Math.floor(progress*5));const selected=chapters[detail??active];
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const updateMedia=()=>setReduced(media.matches);updateMedia();media.addEventListener('change',updateMedia);let raf=0;const update=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const nodes=root.current?.querySelectorAll<HTMLElement>('[id^="home-chapter-"]');if(nodes){const line=innerHeight*.4;let chapter=0;let fraction=0;nodes.forEach((node,i)=>{const r=node.getBoundingClientRect();if(r.top<=line){chapter=i;fraction=Math.max(0,Math.min(1,(line-r.top)/r.height));}});setProgress(Math.max(0,Math.min(1,(chapter+fraction)/5)));}})};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{cancelAnimationFrame(raf);media.removeEventListener('change',updateMedia);window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[]);
 const go=(i:number)=>document.getElementById(`home-chapter-${i}`)?.scrollIntoView({behavior:reduced?'instant':'smooth'});
 return <main id="main" className={`${styles.home} home-cinematic`} data-reduced={staticMode}>
  <div className={styles.story} ref={root}>
   <div className={styles.worldPin} aria-hidden={staticMode||undefined}>{!staticMode?<World progress={progress} mode={mode} paused={paused} inspection={inspection} onInspect={()=>setDetail(active)} onUnavailable={()=>setManualStatic(true)}/>:null}<div className={styles.worldShade}/></div>
   <nav className={styles.chapterRail} aria-label="Home story chapters">{chapters.map((c,i)=><button key={c.name} onClick={()=>go(i)} aria-current={active===i?'step':undefined}><span>{String(i+1).padStart(2,'0')}</span><i/><b>{c.name}</b></button>)}</nav>
   <section id="home-chapter-0" className={`${styles.chapter} ${styles.intro}`}>
    <div className={styles.introCopy}><p className={styles.overline}>EVIDENCE LANE / A PROJECT THAT CONTINUES</p><h1>Keep moving.<br/><em>Keep the evidence.</em></h1><p className={styles.introLead}>Your sources, the next step, and the result behind you.<br className={styles.desktopBreak}/> Connected in a persistent project for Codex.</p></div>
    <div className={styles.intentionDock}><span>EXPLORE A PROJECT STORY</span><div className={styles.intentions}>{examples.map((example,i)=><motion.button whileHover={reduced?{}:{y:-5,scale:1.025}} whileTap={reduced?{}:{scale:.97}} key={example.name} aria-pressed={mode===i} onClick={()=>setMode(i)}><BrandIcon name={example.icons[0]} size={25}/>{example.name}<span aria-hidden="true">↗</span></motion.button>)}</div><button className={styles.scrollPrompt} onClick={()=>go(1)}>Follow the current <span aria-hidden="true">↓</span></button></div>
    {staticMode&&<img className={styles.staticScene} src="/home-current/gather.png" alt="An original three-dimensional evidence ribbon surrounded by source fragments."/>}
   </section>
   <section id="home-chapter-1" className={`${styles.chapter} ${styles.left}`}>
    <div className={styles.storyCopy}><p className={styles.overline}>01 / SELECTED SOURCES</p><h2>Choose<br/><em>what belongs.</em></h2><p>Bring in the material for this project. Keep where it came from, what was read and what still needs attention.</p><div className={styles.sourceTray}>{current.icons.map(icon=><button key={icon} aria-label={`Inspect ${brands[icon].label} source role`} onClick={()=>setDetail(1)}><BrandIcon name={icon} size={42}/><span>{brands[icon].label}</span></button>)}</div><ul className={styles.sourceList}>{current.sources.map(s=><li key={s}>{s}</li>)}</ul><button className={styles.detailLink} onClick={()=>setDetail(1)}>Inside source intake <span>↗</span></button><span className={styles.exampleLabel}>{current.kind} · ILLUSTRATIVE SELECTION</span></div>
    {staticMode&&<img className={styles.staticScene} src="/home-current/gather.png" alt="Selected source fragments gather into a project path."/>}
   </section>
   <section id="home-chapter-2" className={`${styles.chapter} ${styles.right}`}>
    <div className={styles.storyCopy}><p className={styles.overline}>02 / A CURRENT PLAN</p><h2>Give the next step<br/><em>a shape.</em></h2><p>The outcome becomes a sequence with clear scope. Select a task in this example to inspect the boundary around the work.</p><div className={styles.planCard}><header><span>{current.name}</span><small>Illustrative Plan</small></header>{current.plan.map((p,i)=><button key={p} aria-pressed={task===i} onClick={()=>{setTask(i);setDetail(2)}}><span>{String(i+1).padStart(2,'0')}</span><strong>{p}</strong><i aria-hidden="true">↗</i></button>)}</div><button className={styles.detailLink} onClick={()=>setDetail(2)}>How scope and checks stay connected <span>↗</span></button></div>
    {staticMode&&<img className={styles.staticScene} src="/home-current/flow.png" alt="The evidence ribbon straightens into an ordered path."/>}
   </section>
   <section id="home-chapter-3" className={`${styles.chapter} ${styles.left}`}>
    <div className={styles.storyCopy}><p className={styles.overline}>03 / THE PERSISTENT ENGINE</p><h2>The right route<br/><em>through the work.</em></h2><p>The engine checks the task, access and measured readiness. It coordinates the selected operation and the tools it needs.</p><div className={styles.toolRoute}>{current.tools.map(([icon,role])=><button key={icon} onClick={()=>setDetail(3)}><BrandIcon name={icon} size={36}/><span><strong>{brands[icon].label}</strong><small>{role}</small></span><i aria-hidden="true">↗</i></button>)}</div><p className={styles.microcopy}>Illustrated roles. Application icons identify file formats where shown; the registered operation determines the actual adapter.</p><button className={styles.detailLink} onClick={()=>setDetail(3)}>What makes a tool eligible <span>↗</span></button></div>
    {staticMode&&<img className={styles.staticScene} src="/home-current/flow.png" alt="Selected tools align along the project’s working path."/>}
   </section>
   <section id="home-chapter-4" className={`${styles.chapter} ${styles.right}`}>
    <div className={styles.storyCopy}><p className={styles.overline}>04 / AN INSPECTABLE RESULT</p><h2>Open the result.<br/><em>Follow its trail.</em></h2><p>{current.resultBody}</p><div className={styles.resultCard}><div className={styles.resultTabs} aria-label="Inspect the illustrative result">{['Result','Sources','Checks'].map((s,i)=><button key={s} aria-pressed={inspection===i} onClick={()=>setInspection(i)}>{s}</button>)}</div><AnimatePresence mode="wait"><motion.div key={`${mode}-${inspection}`} className={styles.resultBody} aria-live="polite" initial={{opacity:0,x:15}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-15}} transition={{duration:reduced?0:.22}}><span>{['OUTPUT','INPUT REFERENCES','RECORDED VERIFICATION'][inspection]}</span><h3>{[current.result,'The selected evidence','What was actually checked'][inspection]}</h3><ul>{(inspection===0?current.artifact:inspection===1?current.sources:['Task-specific acceptance conditions','Actual observations and result references','Disclosed coverage and limitations']).map(a=><li key={a}>{a}</li>)}</ul></motion.div></AnimatePresence><footer>Illustrative record · No live project execution</footer></div><button className={styles.detailLink} onClick={()=>setDetail(4)}>Read the verification boundary <span>↗</span></button></div>
    {staticMode&&<img className={styles.staticScene} src="/home-current/flow.png" alt="A result is connected back to the source and work path."/>}
   </section>
   <section id="home-chapter-5" className={`${styles.chapter} ${styles.outro}`}>
    <div className={styles.outroCopy}><p className={styles.overline}>05 / CONTINUITY</p><h2>A new conversation.<br/><em>Your project, continued.</em></h2><p>Return to the Plan, selected evidence and recorded results.<br className={styles.desktopBreak}/> Refresh what changed. Keep the next step intentional.</p><button className={styles.resumeButton} onClick={()=>setResumed(!resumed)} aria-pressed={resumed}>{resumed?'Return to this session':'Preview the next session'}<span>↗</span></button><div className={styles.sessionWindow} key={String(resumed)}><span>{resumed?"NEXT CONVERSATION":"CURRENT CONVERSATION"} · ILLUSTRATION</span><p>{resumed?"Resume this project with its saved context.":"Continue the next eligible task in this project."}</p><small>Project: {current.name} · Sources, Plan and result references stay with the project</small></div><div className={styles.resumeStrip} aria-live="polite"><span>{resumed?'NEW SESSION / PROJECT CONTEXT RETAINED':'CURRENT SESSION / PROJECT CONTEXT'}</span><div>{['Selected sources','Current Plan','Recorded result'].map((s,i)=><button key={s} onClick={()=>setDetail(i===0?1:i===1?2:4)}>{s}<b>↗</b></button>)}</div><small>Illustrative continuity · Actual resume checks the exact saved context</small></div><button className={styles.detailLink} onClick={()=>setDetail(5)}>What carries forward <span>↗</span></button></div>
    {staticMode&&<img className={styles.staticScene} src="/home-current/gather.png" alt="The persistent project path gathers its context for continuation."/>}
   </section>
  </div>
  <section className={styles.landingClose}><div><p className={styles.overline}>YOUR NEXT STEP</p><h2>Start with your work.</h2><p>Explore the product, find the appropriate workflow, or read the installation requirements when the release is qualified.</p><div className={styles.closeLinks}><Link href="/product">Explore the product ↗</Link><Link href="/workflows">Find a workflow ↗</Link><button onClick={()=>setDetail(0)}>About this illustration ↗</button></div></div><div className={styles.closeBrandRow}>{['git','github','python','nodejs','word','excel','powerpoint'].map(b=><BrandIcon key={b} name={b} size={32}/>)}<button onClick={()=>setCredits(true)}>Icon sources & attribution</button></div></section>
  <div className={styles.viewerControls}><span>{String(active+1).padStart(2,'0')} / {chapters[active].name}</span><button onClick={toggle} aria-pressed={paused}>{paused?'Play motion':'Pause motion'}</button><button onClick={()=>setManualStatic(!manualStatic)} disabled={reduced}>{reduced?"Reduced motion":manualStatic?"3D view":"Static view"}</button><button onClick={()=>setDetail(active)}>Chapter details ↗</button></div>
  <GlassPopup open={detail!==null} onClose={()=>setDetail(null)} title={selected.title} kicker="EVIDENCE LANE / INSIDE THE STORY" description={selected.summary} color="#64c5e2"><div className={styles.dossier}><section><h3>What happens</h3><ol>{selected.facts.map(f=><li key={f}>{f}</li>)}</ol>{detail===2&&<p className={styles.selectedTask}>Selected example task: <strong>{current.plan[task]}</strong></p>}<h3>Your example</h3><p>{current.name}: {current.resultBody}</p></section><aside><p className={styles.overline}>RELEVANT FORMATS & TOOLS</p><div className={styles.dossierBrands}>{current.icons.map(i=><div key={i}><BrandIcon name={i} size={42}/><span>{brands[i].label}</span></div>)}</div>{detail!==null&&<InteractiveBrainOrb icons={current.icons.map(i=>brands[i])}/>}<p>This is an interactive product explanation. Availability and execution are checked through the connected project runtime.</p></aside></div></GlassPopup>
  <GlassPopup open={credits} onClose={()=>setCredits(false)} title="The actual tool identities" kicker="ICON ATTRIBUTION" description="Original branded assets identify tools and supported application formats. Their presence does not imply endorsement or a live connection."><div className={styles.attribution}><p>Git logo by Jason Long, licensed under CC BY 3.0. Python is a Python Software Foundation trademark. Node.js is an OpenJS Foundation trademark. GitHub and Microsoft product marks belong to their respective owners.</p><ul><li><a href="https://git-scm.com/community/logos">Git logo downloads</a></li><li><a href="https://www.python.org/community/logos/">Python logo and usage policy</a></li><li><a href="https://nodejs.org/en/about/branding">Node.js branding</a></li><li><a href="https://github.com/logos">GitHub logos</a></li><li><a href="https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/online/branding">Microsoft product branding</a></li></ul></div></GlassPopup>
 </main>;
}
