'use client';
import {useState,useEffect,type CSSProperties} from 'react';
import {useSceneFocus} from './scene-focus';
import {DetailControlCompanion} from './detail-control-companion';
import {subjectInfo,SubjectDetail,RecordDetail,WorkflowDetail,SingleToolDetail} from './home-subject-detail';
import {productRecords} from '../data/product-story';
import {ToolBrowser} from './tool-browser';
import {ToolIdentity,ToolLogoRow,toolName} from './tool-identity';
import Link from 'next/link';
import {OriginalGlassIconOrb as Orb,OriginalGlassPill as Pill} from './original-glass';
import {OriginalGlassPopup} from './original-popup';
import {SemanticIcon,semanticIconColors,type SemanticIconName} from './semantic-icon';
import {SourceLaneIcon} from './source-lane-icon';
import {InteractiveBrainOrb} from './interactive-brain-orb';
import {HomeDetailStory} from './home-detail-stories';
import {records,sourceGroups,atlasSections,chapterNodes,type SceneNode} from '../data/home-atlas-story';
import workflows from '../data/workflows.json';
import catalogue from '../data/tool-browser.json';

export function AtlasIcon({name,size=42,color}:{name:SemanticIconName;size?:number;color?:string}){return <Orb size={size} color={color??semanticIconColors[name]} decorative><SemanticIcon name={name} size={28}/></Orb>}
export function SourceGroupIcon({index,size=42}:{index:number;size?:number}){const s=sourceGroups[index];return <Orb size={size} color={s.color} decorative>{s.brand?<img src={`/brands/${s.brand}`} alt=""/>:s.lane?<SourceLaneIcon lane={s.lane} size={28} decorative/>:<SemanticIcon name={s.icon}/>}</Orb>}
const headings:Record<string,[string,string,SemanticIconName]>={project:['The connected project','Explore how the parts work together.','project'],entry:['Start a project','First entry and returning to an existing project have different starting points.','project'],sources:['Source preparation','Choose a material group and follow its path into project evidence.','sources'],work:['Coordinate the work','Follow the work loop, from the current Plan to the recorded result.','work'],plan:['The current Plan','A task starts with an outcome, scope and a place in the plan.','plan'],tools:['Tools selected for the task','The source and requested operation determine the relevant tool route.','tools'],compute:['Compute with a purpose','Compatibility and measured readiness determine which compute can be used.','tools'],connections:['Connections with a scope','Project connections are configured, used and revoked through their own workflow.','connections'],result:['Inspect a recorded result','Output, source references and checks remain separately inspectable.','results'],memory:['Continue the project','Keep context, completed work and the next task connected without merging their records.','memory'],studio:['The Studio observer','Explore the read-only project views. Direct changes through Codex.','studio'],workflows:['Find a workflow','Choose the intention that matches what you want to do.','workflow']};
export function HomeAtlasDetails({selected,source,onSource,onClose,onNavigate,nodes}:{selected:string|null;source:number;onSource:(value:number)=>void;onClose:()=>void;onNavigate:(id:string)=>void;nodes?:SceneNode[]}){
 const {state:focus}=useSceneFocus();
 useEffect(()=>{if(selected){const panel=document.getElementById('atlas-detail');panel?.focus({preventScroll:true});const scroll=panel?.querySelector('.flowPopupScroll');if(scroll)scroll.scrollTop=0}},[selected]);
 const [kind,...args]=selected?.split(':')??[];const arg=args.join(':');
 const record=kind==='record'?productRecords.find(r=>r.id===(arg==='network'?'links':arg)):undefined;
 const workflow=kind==='workflow'?workflows.find(w=>w.id===arg):undefined;
 const subject=subjectInfo[selected??''];const sourceItem=kind==='source'?sourceGroups[Number(arg)]:undefined;
 const actualKind=kind==='source'?'sources':kind;const heading=headings[actualKind]??headings.project;
 const identity=focus.identity;
 const fallbackTitle=record?.name??workflow?.title??subject?.name??sourceItem?.title??(kind==='tool'?toolName(arg):kind==='studio'&&arg?arg:heading[0]);
 const title=identity?.title||fallbackTitle;
 const icon=(identity?.icon&&identity.icon in semanticIconColors?identity.icon:record?.icon??subject?.icon??sourceItem?.icon??heading[2]) as SemanticIconName;
 const color=identity?.color||record?.color||sourceItem?.color||semanticIconColors[icon];
 const description=kind==='chapter'?atlasSections[Number(arg)]?.body:record?.purpose??workflow?.description??subject?.summary??sourceItem?.operation??(kind==='tool'?'The selected tool, its delivery role and declared operations.':kind==='studio'&&arg?'This Studio view and the information it presents.':heading[1]);
 return <OriginalGlassPopup companion={<DetailControlCompanion onSelect={onNavigate}/>} open={Boolean(selected)} onClose={onClose} labelledBy="atlas-detail-title" panelId="atlas-detail" size="wide">{selected&&<><header className="flow-detail-heading" style={{'--item-color':color} as CSSProperties}>
 {kind==='tool'?<ToolIdentity id={arg} size={72}/>:sourceItem?<SourceGroupIcon index={Number(arg)} size={72}/>:identity?.image?<Orb size={72} color={color} decorative><img src={identity.image} alt=""/></Orb>:<AtlasIcon name={icon} color={color} size={72}/>}
 <div><p className="flow-kicker">EVIDENCE LANE / {kind.toUpperCase()}</p><h2 id="atlas-detail-title">{title}</h2><p>{description}</p></div></header><div className="atlas-detail-content" key={selected}>
 {subject&&<SubjectDetail id={selected} onNavigate={onNavigate}/>}
 {kind==='chapter'&&<section className="subject-detail"><h3>{atlasSections[Number(arg)]?.label}</h3><p>Explore each part of this connection and the role it plays in this stage of the project.</p><div className="subject-records">{(nodes??chapterNodes(Number(arg),source,'tools','Plan')).filter(n=>n.id!=='project').map(n=><Pill key={n.id} leading={<Orb color={n.color} decorative>{n.brand?<img src={'/brands/'+n.brand} alt=""/>:n.lane?<SourceLaneIcon lane={n.lane} decorative/>:<SemanticIcon name={n.icon}/>}</Orb>} onClick={()=>onNavigate(n.action)}>{n.label}</Pill>)}</div></section>}
 {kind==='tool'&&<SingleToolDetail id={arg} onNavigate={onNavigate}/>}
 {kind==='record'&&<RecordDetail id={arg}/>}
 {kind==='workflow'&&<WorkflowDetail id={arg} onNavigate={onNavigate}/>}
 {actualKind==='project'&&<><p className="flow-detail-lead">Codex receives the intent. Evidence Lane connects the project, its plan and selected material to coordinated work. Studio makes the project observable, while results and their evidence stay linked.</p><HomeDetailStory kind="project" onNavigate={onNavigate}/></>}
 {actualKind==='entry'&&<EntryStory/>}
 {actualKind==='sources'&&<SourceStory index={kind==='source'?Number(arg):source} onChange={onSource} single={kind==='source'} onNavigate={onNavigate}/>}
 {actualKind==='plan'&&<RecordDetail id="plan"/>}
 {actualKind==='work'&&<HomeDetailStory kind="work" onNavigate={onNavigate}/>}
 {actualKind==='tools'&&<ToolBrowser/>}
 {actualKind==='compute'&&<ComputeStory/>}
 {actualKind==='connections'&&<ConnectionStory/>}
 {actualKind==='result'&&<HomeDetailStory kind="result" initialResult={arg==='sources'?1:arg==='checks'?2:0} onNavigate={onNavigate}/>}
 {actualKind==='memory'&&<ContinuityStory/>}
 {actualKind==='studio'&&<HomeDetailStory kind="studio" initialView={arg||undefined} single={Boolean(arg)} onNavigate={onNavigate}/>}
 {actualKind==='workflows'&&<WorkflowStory/>}
 </div></>}</OriginalGlassPopup>;
}

function EntryStory(){const[mode,setMode]=useState<'first'|'resume'>('first');const sequence=mode==='first'?[['Install the plugin','Add Evidence Lane to Codex Desktop.'],['Connect the local runtime','Plugin detection provisions and connects the shared local engine, Studio and required tools.'],['Select a project','Establish the project and persistent local state.'],['Open the current Plan','Begin with the project’s selected work and context.']]:[['Select the project','Return to the explicitly selected project.'],['Check the saved context','Check the project and session references before continuation.'],['Read what changed','Inspect the current Plan and relevant source/evidence state.'],['Choose the next task','Continue or steer from the current project state.']];return <><div className="atlas-segment"><Pill active={mode==='first'} aria-pressed={mode==='first'} onClick={()=>setMode('first')}>First entry</Pill><Pill active={mode==='resume'} aria-pressed={mode==='resume'} onClick={()=>setMode('resume')}>Resume a project</Pill></div><ol className="atlas-entry-track">{sequence.map(([title,description],i)=><li key={title}><AtlasIcon name={(mode==='first'?['download','connections','project','plan'] as const:['project','memory','sources','plan'] as const)[i]} size={57}/><span className="atlas-step-number">0{i+1}</span><h3>{title}</h3><p>{description}</p></li>)}</ol><p className="atlas-detail-note">Host profiles: Codex Desktop Stable and Codex Desktop Beta on a persistent local Windows PC. This is an illustrated sequence, not a live installation.</p></>}
function SourceStory({index,onChange,single=false,onNavigate}:{index:number;onChange:(i:number)=>void;single?:boolean;onNavigate:(id:string)=>void}){const[active,setActive]=useState(Math.max(0,Math.min(5,index)));const s=sourceGroups[active];const profiles=[['code'],['document','presentation'],['spreadsheet','data','tableau','power_bi'],['pdf_ocr'],['images_ocr'],['research','artifacts','custom']][active];const tools=Array.from(new Set(catalogue.operations.filter(a=>profiles.includes(a.profile)).flatMap(a=>a.tools)));return <>{!single&&<div className="atlas-source-selector">{sourceGroups.map((group,i)=><button key={group.id} aria-pressed={active===i} onClick={()=>{setActive(i);onChange(i)}}><SourceGroupIcon index={i}/><span>{group.title}</span></button>)}</div>}<section className="atlas-source-operation" key={s.id}><div><SourceGroupIcon index={active} size={72}/><h3>{s.operation}</h3><p>{s.note}</p><ToolLogoRow tools={s.members}/></div><ol>{s.stages.map((stage,i)=><li key={stage}><span>0{i+1}</span>{stage}</li>)}</ol></section><div className="atlas-tool-members"><strong>Relevant tools and format readers</strong><ToolLogoRow tools={tools} onSelect={id=>onNavigate('tool:'+id)}/></div><p className="atlas-detail-note">The selected operation chooses its exact route. Tool availability, connection scope and execution checks are evaluated when work runs.</p></>}
function ComputeStory(){const[active,setActive]=useState(0);const options=[['CPU','The general local execution path for operations that use CPU tools.'],['NVIDIA CUDA','For declared accelerator operations on compatible NVIDIA hardware with the required environment.'],['AMD ROCm','For declared operations with a supported AMD runtime and compatible hardware.'],['DirectML','For operations with a declared DirectML route on supported Windows hardware.']];return <><div className="atlas-source-selector">{options.map(([name],i)=><button key={name} aria-pressed={active===i} onClick={()=>setActive(i)}><AtlasIcon name="tools" color={['#70cdf1','#8ddd73','#f09c92','#bba1f6'][i]}/><span>{name}</span></button>)}</div><div className="atlas-spotlight"><AtlasIcon name="checks" size={74}/><h3>{options[active][0]}</h3><p>{options[active][1]}</p><div className="atlas-member-tags"><span>Declared operation</span><span>Compatible device</span><span>Environment readiness</span><span>Measured checks</span></div></div><p className="atlas-detail-note">Selecting a compute profile in this illustration does not configure or verify your device.</p></>}
function ConnectionStory(){const[stage,setStage]=useState(0);const steps=[['Configure','Choose the project connection and the access it needs.'],['Scope','Bound the grant to the purpose, allowed actions and relevant project or path.'],['Use','Use the configured connection only where the selected operation permits it.'],['Revoke','Withdraw access while preserving its recorded history.']];return <><div className="atlas-connection-track">{steps.map(([title],i)=><Pill key={title} active={stage===i} aria-pressed={stage===i} leading={<AtlasIcon name="connections"/>} onClick={()=>setStage(i)}>{title}</Pill>)}</div><div className="atlas-spotlight"><AtlasIcon name={stage===3?'checks':'connections'} size={78}/><h3>{steps[stage][0]} the connection</h3><p>{steps[stage][1]}</p><div className="atlas-member-tags"><span>Purpose</span><span>Allowed actions</span><span>Project / path</span><span>Expiry</span></div></div><p className="atlas-detail-note">Ordinary project source and service connections remain distinct from the local project’s storage location.</p></>}
function ContinuityStory({initialRecord}:{initialRecord?:string}){const[record,setRecord]=useState(records.findIndex(r=>r[0]===initialRecord)>=0?records.findIndex(r=>r[0]===initialRecord):3);const[mode,setMode]=useState(0);return <><div className="atlas-segment">{['Return','Steer','Recover'].map((label,i)=><Pill key={label} active={mode===i} aria-pressed={mode===i} onClick={()=>setMode(i)}>{label}</Pill>)}</div><p className="flow-detail-lead">{['Resume the selected project with its current Plan and exact context references.','Checkpoint affected work and replace the relevant future tasks while preserving completed history.','Use a coherent backup of the separate project records and the declared recovery workflow.'][mode]}</p><div className="atlas-continuity"><div className="atlas-record-grid">{records.map(([id,label],i)=><button key={id} aria-pressed={record===i} onClick={()=>setRecord(i)}><AtlasIcon name={id==='plan'?'plan':id==='memory'?'memory':id==='learning'?'learning':id==='chat'?'chat':id==='exchange'||id==='network'?'connections':id==='receipts'?'results':'sources'}/><span>{label}</span></button>)}</div><div><h3>{records[record][1]}</h3><p>{records[record][2]}</p>{record===3?<InteractiveBrainOrb icons={[]}/>:<div className="atlas-record-links"><span>Owning record</span><i>↔</i><span>Explicit references</span></div>}<p className="atlas-detail-note">Each owner keeps its own records and files. A link does not merge the stores.</p></div></div></>}
function WorkflowStory({initial}:{initial?:string}){const[query,setQuery]=useState('');const[selected,setSelected]=useState(initial??'');const visible=workflows.filter(w=>(w.title+' '+w.description).toLowerCase().includes(query.toLowerCase()));const chosen=workflows.find(w=>w.id===selected);return <div className="atlas-workflow-browser"><label>Find a workflow<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Plan, sources, memory, connections, recovery…" type="search"/></label><div className="atlas-workflow-layout"><div className="atlas-workflow-list">{visible.map(w=><button key={w.id} aria-pressed={selected===w.id} onClick={()=>setSelected(w.id)}><span>{w.title}</span><b>↗</b></button>)}{visible.length===0&&<p>No matching workflow.</p>}</div><div className="atlas-workflow-inspector">{chosen?<><AtlasIcon name="workflow" size={70}/><h3>{chosen.title}</h3><p>{chosen.id==='select-project-storage'?'Inspect or register the persistent local location for this project and its separate records.':chosen.outcome}</p><blockquote>{chosen.example}</blockquote><Link href="/workflows" className="flow-link-pill">Read the workflow guide <span>↗</span></Link></>:<><AtlasIcon name="workflow" size={70}/><h3>Choose an intention</h3><p>Select a workflow to see what it does and an example request.</p></>}</div></div></div>}
