'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import type * as THREE from 'three';
import {OriginalGlassIconOrb} from './original-glass';
import {SemanticIcon} from './semantic-icon';
import{createProceduralGalaxy}from'./procedural-galaxy';
import{createInteractiveStarfield}from'./interactive-starfield';
import{useSceneFocus}from'./scene-focus';
import type{SceneNode}from'../data/home-atlas-story';
import{SourceLaneIcon}from'./source-lane-icon';

type Props={progress:number;paused:boolean;showAssembly:boolean;nodes:SceneNode[];focus?:string;onSelect:(id:string)=>void;onUnavailable:()=>void};

export function InfinityFlowScene(props:Props){
 const {state:detailScene}=useSceneFocus();const items=props.nodes;const mount=useRef<HTMLDivElement>(null),live=useRef({...props,detailScene}),anchors=useRef<(HTMLButtonElement|null)[]>([]);const[ready,setReady]=useState(false);const hover=useRef<string|null>(null);
 useEffect(()=>{live.current={...props,detailScene}},[props,detailScene]);
 useEffect(()=>{const element=mount.current;if(!element)return;const host=element;let disposed=false,cleanup=()=>{};
 async function start(){try{
  const T=await import('three');const [{GLTFLoader},{RoomEnvironment}]=await Promise.all([import('three/examples/jsm/loaders/GLTFLoader.js'),import('three/examples/jsm/environments/RoomEnvironment.js')]);if(disposed)return;
  const renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.setClearColor(0x000000,0);host.appendChild(renderer.domElement);
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,140),root=new T.Group();scene.add(root);camera.position.set(0,0,15);const galaxy=createProceduralGalaxy(T);scene.add(galaxy.display);
  const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=1.7;room.dispose();pmrem.dispose();scene.add(new T.HemisphereLight(0xbce5ff,0x1a143a,2));const key=new T.DirectionalLight(0xe8f6ff,4);key.position.set(-2,4,7);scene.add(key);const rim=new T.DirectionalLight(0xa68fff,3);rim.position.set(5,-2,-2);scene.add(rim);
  const geometries:THREE.BufferGeometry[]=[],materials:THREE.Material[]=[];let model:THREE.Group|undefined;const ribbonTime={value:0};const g=<X extends THREE.BufferGeometry>(x:X)=>{geometries.push(x);return x};const m=<X extends THREE.Material>(x:X)=>{materials.push(x);return x};
  const point=(t:number)=>new T.Vector3(4.25*Math.cos(t*Math.PI*2),1.62*Math.sin(t*Math.PI*4),-.75*Math.sin(t*Math.PI*2));
  const glow=m(new T.ShaderMaterial({transparent:true,depthWrite:false,vertexColors:true,blending:T.NormalBlending,uniforms:{time:{value:0}},vertexShader:'attribute float size;varying vec3 tint;varying float phase;void main(){tint=color;phase=position.x*7.;vec4 p=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*p;gl_PointSize=clamp(size*25./-p.z,1.,12.);}',fragmentShader:'varying vec3 tint;varying float phase;uniform float time;void main(){float r=length(gl_PointCoord-.5)*2.;if(r>1.)discard;gl_FragColor=vec4(tint,exp(-r*r*3.6)*(1.-smoothstep(.65,1.,r))*.64);\n#include <colorspace_fragment>\n}'}));const starfield=createInteractiveStarfield(T,host.clientWidth<740?1200:3600);scene.add(starfield.group);
  const trailCount=90,trailGeo=g(new T.BufferGeometry()),trailPos=new Float32Array(trailCount*3),trailColors=new Float32Array(trailCount*3),trailSizes=new Float32Array(trailCount);for(let i=0;i<trailCount;i++){const c=new T.Color(i%4===0?0xd89a52:i%3===0?0xa9c3d6:0x5eafe0);trailColors.set([c.r,c.g,c.b],i*3);trailSizes[i]=i%13===0?4.5:1.8}trailGeo.setAttribute('position',new T.BufferAttribute(trailPos,3));trailGeo.setAttribute('color',new T.BufferAttribute(trailColors,3));trailGeo.setAttribute('size',new T.BufferAttribute(trailSizes,1));const trail=new T.Points(trailGeo,glow);root.add(trail);
  const beams:THREE.Line[]=[];for(let j=0;j<7;j++){const path=[];for(let i=0;i<=260;i++){const p=point(i/260);p.y+=(j-3)*.055*Math.sin(i/260*Math.PI*2);p.z+=(j-3)*.08;path.push(p)}const b=new T.Line(g(new T.BufferGeometry().setFromPoints(path)),m(new T.LineBasicMaterial({color:j%3===0?0xffdfac:j%2?0x89dfff:0xb8aaff,transparent:true,opacity:.35,blending:T.AdditiveBlending})));root.add(b);beams.push(b)}
  let frame=0,last=0,time=0,progress=0,detailBlend=0,mx=0,my=0,yaw=0,pitch=0,viewYaw=0,viewPitch=0,drag=false,lastX=0,lastY=0,visible=true;const world=new T.Vector3();
  const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();galaxy.resize(host.clientWidth,host.clientHeight)};resize();const ro=new ResizeObserver(resize);ro.observe(host);const observer=new IntersectionObserver(e=>{visible=e[0].isIntersecting});observer.observe(host);
  const pointer=(e:PointerEvent)=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5;starfield.pointer(mx*2,-my*2);if(drag){yaw+=(e.clientX-lastX)*.0015;pitch=Math.max(-.25,Math.min(.25,pitch+(e.clientY-lastY)*.001));lastX=e.clientX;lastY=e.clientY}};
  const down=(e:PointerEvent)=>{if(e.pointerType!=='mouse')return;drag=true;lastX=e.clientX;lastY=e.clientY;host.setPointerCapture(e.pointerId)};const up=()=>{drag=false};const keydown=(e:KeyboardEvent)=>{if(e.key.startsWith('Arrow')){e.preventDefault();yaw+=e.key==='ArrowLeft'?-.1:e.key==='ArrowRight'?.1:0;pitch+=e.key==='ArrowUp'?-.05:e.key==='ArrowDown'?.05:0}};
  const resumeStory=()=>{yaw=0;pitch=0;drag=false};window.addEventListener('scroll',resumeStory,{passive:true});window.addEventListener('blur',starfield.leave);document.addEventListener('pointerleave',starfield.leave);window.addEventListener('pointermove',pointer,{passive:true});host.addEventListener('pointerdown',down);host.addEventListener('pointerup',up);host.addEventListener('pointercancel',up);host.addEventListener('keydown',keydown);const lost=(e:Event)=>{e.preventDefault();live.current.onUnavailable()};renderer.domElement.addEventListener('webglcontextlost',lost);
  cleanup=()=>{cancelAnimationFrame(frame);ro.disconnect();observer.disconnect();window.removeEventListener('scroll',resumeStory);window.removeEventListener('blur',starfield.leave);document.removeEventListener('pointerleave',starfield.leave);window.removeEventListener('pointermove',pointer);host.removeEventListener('pointerdown',down);host.removeEventListener('pointerup',up);host.removeEventListener('pointercancel',up);host.removeEventListener('keydown',keydown);renderer.domElement.removeEventListener('webglcontextlost',lost);model?.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(x=>x.dispose())}});geometries.forEach(x=>x.dispose());materials.forEach(x=>x.dispose());env.dispose();galaxy.dispose();starfield.dispose();renderer.dispose();renderer.domElement.remove()};
  const loaded=await new GLTFLoader().loadAsync('/home-current/optical-infinity.glb?v=atlas8-liquid');if(disposed){loaded.scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(x=>x.dispose())}});return}model=loaded.scene;model.traverse(o=>{if(o instanceof T.Mesh&&o.name.startsWith('OpticalRibbon')){const old=o.material;o.material=new T.MeshPhysicalMaterial({color:o.name.endsWith('0')?0x8bd5fa:o.name.endsWith('1')?0xb7a1ed:0xf0d4ab,metalness:.08,roughness:.055,transparent:true,opacity:.48,transmission:.6,thickness:.16,ior:1.42,clearcoat:1,clearcoatRoughness:.04,side:T.DoubleSide,depthWrite:false,envMapIntensity:1.3,iridescence:.65,iridescenceIOR:1.3});o.material.onBeforeCompile=(shader:Parameters<THREE.Material["onBeforeCompile"]>[0])=>{shader.uniforms.flowTime=ribbonTime;shader.vertexShader='uniform float flowTime;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <project_vertex>','transformed.y += sin(transformed.x*1.9 + flowTime*.9)*.10; transformed.z += cos(transformed.x*1.4-flowTime*.7)*.14;\n#include <project_vertex>');};(Array.isArray(old)?old:[old]).forEach(x=>x.dispose())}else if(o instanceof T.Mesh&&o.name.startsWith('Edge_')){const old=o.material;const color=o.name.includes('Edge_0')?0x70d8fa:o.name.includes('Edge_1')?0xb7a5ed:0xe4c095;o.visible=false;o.material=new T.MeshBasicMaterial({color,transparent:true,opacity:.62,depthWrite:false,toneMapped:false});(Array.isArray(old)?old:[old]).forEach(x=>x.dispose())}});root.add(model);setReady(true);host.dataset.scene='optical-infinity';host.dataset.universe='home-blue-rift';
  const fields=(t:number,section:number)=>{const chapter=[0,4,1,2,3,5,6,0][section]??0;const a=t*Math.PI*2;if(chapter===4)return new T.Vector3(4.1*Math.cos(a),1.25*Math.sin(2*a),-.9*Math.sin(a));if(chapter===5)return new T.Vector3(3.45*Math.cos(a),2.45*Math.sin(a),-.7*Math.sin(2*a));if(chapter===6)return new T.Vector3(4.15*Math.sign(Math.cos(a))*Math.sqrt(Math.abs(Math.cos(a))),1.8*Math.sign(Math.sin(a))*Math.sqrt(Math.abs(Math.sin(a))),-.65*Math.sin(2*a));if(chapter===1)return new T.Vector3(4.55*Math.cos(a),2.1*Math.sin(2*a),-1.2*Math.sin(a));if(chapter===2)return new T.Vector3((t-.5)*9,.4*Math.sin(a*1.5),-.45*Math.sin(a));if(chapter===3)return new T.Vector3(4.3*Math.cos(a),1.6*Math.sin(2*a)*(Math.cos(a)>0?1.2:.48),-.8*Math.sin(a));return point(t)};
  const flow=(t:number,p:number)=>{const c=Math.min(7,Math.floor(p)),n=Math.min(7,c+1),f=p-c;const mix=smooth((f-.55)/.45);return fields(t,c).lerp(fields(t,n),mix)};
  const smooth=(x:number)=>{x=Math.max(0,Math.min(1,x));return x*x*(3-2*x)};
  let spacingKey='',spaced=new Map<string,number>();
  function spaceNodes(nodes:SceneNode[],chapter:number){
    const key=chapter+':'+nodes.map(n=>n.id).join(',');if(key===spacingKey)return;spacingKey=key;spaced=new Map();
    const members=nodes.filter(n=>n.t>=0);
    const distribute=(group:SceneNode[],start:number,end:number,closed=false)=>{
      const samples=160,lengths=[0];let previous=fields(((start%1)+1)%1,chapter);
      for(let k=1;k<=samples;k++){const t=start+(end-start)*k/samples,current=fields(chapter===3?t:((t%1)+1)%1,chapter);lengths.push(lengths[k-1]+previous.distanceTo(current));previous=current;}
      group.forEach((node,i)=>{const fraction=closed?(i+.5)/group.length:(i+1)/(group.length+1);const target=fraction*lengths[samples];let k=1;while(k<samples&&lengths[k]<target)k++;const f=(target-lengths[k-1])/(lengths[k]-lengths[k-1]||1);spaced.set(node.id,((start+(end-start)*(k-1+f)/samples)%1+1)%1)});
    };
    if(chapter===3){const left=members.filter(n=>n.t<.5),right=members.filter(n=>n.t>=.5);distribute(left,0,.43);distribute(right,.57,1)}
    else if(chapter===5||chapter===6)distribute(members,0,1,true);
    else{distribute(members.filter(n=>n.t>=.25&&n.t<=.75),.25,.75);distribute(members.filter(n=>n.t<.25||n.t>.75),.75,1.25)}
  }
  function tick(now:number){if(disposed)return;frame=requestAnimationFrame(tick);const dt=Math.min(.04,(now-last)/1000);last=now;if(!visible||document.hidden)return;const s=live.current;root.visible=s.showAssembly&&!(s.detailScene.active&&s.detailScene.companion?.kind==='controls');const still=s.paused||matchMedia('(prefers-reduced-motion: reduce)').matches;if(!still)time+=dt;const desiredProgress=s.detailScene.active?Math.floor(s.progress):s.progress;progress+=(desiredProgress-progress)*.09;if(s.detailScene.active){yaw=0;pitch=0;}const chapter=Math.min(7,Math.floor(progress)),f=progress-chapter,b=smooth((f-.62)/.38);const xs=[4.15,-3.8,3.95,-3.8,3.95,-3.8,3.9,-3.8],scales=[1.02,.94,.91,.94,.95,.88,.91,.94],angles=[-.08,.16,-.2,.13,-.18,.22,-.12,.05];const n=Math.min(7,chapter+1);const mobile=host.clientWidth<=1000;detailBlend+=((s.detailScene.active?1:0)-detailBlend)*(still&&matchMedia('(prefers-reduced-motion: reduce)').matches?1:.075);const slot=mobile?document.querySelector(`#flow-chapter-${chapter} .atlas-mobile-scene-slot`)?.getBoundingClientRect():undefined;const mobileY=slot?(.5-(slot.top+slot.height/2-host.getBoundingClientRect().top)/host.clientHeight)*(2*15*Math.tan(19*Math.PI/180)):-.7;root.position.set(mobile?0:T.MathUtils.lerp(xs[chapter],xs[n],b),mobile?mobileY:-Math.sin(b*Math.PI)*1.7,0);if(!mobile)root.position.y-=Math.max(0,(parseFloat(document.documentElement.style.getPropertyValue('--site-header-height'))||116)-scrollY)/host.clientHeight*(2*15*Math.tan(19*Math.PI/180));root.scale.setScalar(mobile?Math.min(.7,Math.max(.36,host.clientWidth/1100)):T.MathUtils.lerp(scales[chapter],scales[n],b));if(!mobile&&detailBlend>.001){const halfH=15*Math.tan(19*Math.PI/180);root.position.x=T.MathUtils.lerp(root.position.x,((s.detailScene.dock.x*innerWidth-host.getBoundingClientRect().left)/host.clientWidth-.5)*halfH*2*camera.aspect,detailBlend);root.position.y=T.MathUtils.lerp(root.position.y,(.5-(s.detailScene.dock.y*innerHeight-host.getBoundingClientRect().top)/host.clientHeight)*halfH*2,detailBlend);root.scale.multiplyScalar(T.MathUtils.lerp(1,(s.detailScene.layout==='above'||s.detailScene.layout==='below')?.35:host.clientWidth<1400?.43:.55,detailBlend));}viewYaw+=(yaw-viewYaw)*.1;viewPitch+=(pitch-viewPitch)*.1;root.rotation.set(viewPitch+Math.sin(time*.17)*.035,viewYaw+T.MathUtils.lerp(angles[chapter],angles[n],b)+Math.sin(time*.12)*.025,Math.sin(time*.13)*.02);camera.position.set(still||s.detailScene.active?0:mx*.38,still||s.detailScene.active?0:-my*.24,15-Math.sin(f*Math.PI)*.55);if(!still){key.position.set(-2+Math.sin(time*.21)*1.1+mx,4+Math.cos(time*.17)*.5,7);rim.position.set(5+Math.cos(time*.19),-2+Math.sin(time*.23),-2);}camera.lookAt(0,0,0);camera.updateMatrixWorld();root.updateMatrixWorld(true);
   const transferAmount=Math.sin(Math.PI*smooth((f-.35)/.65))**2*(1-detailBlend);const displacement=starfield.update(dt,camera,progress,still,{amount:transferAmount,matrix:root.matrixWorld,point:(t)=>flow(t,progress)});host.dataset.particleTransfer=transferAmount.toFixed(3);host.dataset.particleDisplacement=displacement.toFixed(4);glow.uniforms.time.value=time;ribbonTime.value=time;
   for(let i=0;i<trailCount;i++){const p=flow((i/trailCount+time*.08)%1,progress);p.y+=Math.sin(i*13.7)*.075;p.z+=Math.cos(i*5.1)*.08;trailPos.set([p.x,p.y,p.z],i*3)}trailGeo.attributes.position.needsUpdate=true;beams.forEach((beam,j)=>{const a=beam.geometry.attributes.position as THREE.BufferAttribute;for(let k=0;k<a.count;k++){const t=k/(a.count-1),p=flow(t,progress);p.y+=(j-3)*.09*Math.sin(t*Math.PI*2+time*.55);p.z+=(j-3)*.08*Math.cos(t*Math.PI*4+time*.3);a.setXYZ(k,p.x,p.y,p.z)}a.needsUpdate=true;(beam.material as THREE.LineBasicMaterial).opacity=(hover.current?.length||s.focus)?.8:.45+Math.sin(time*.8+j)*.18});
   model?.traverse(o=>{if(o instanceof T.Mesh&&o.morphTargetInfluences){o.morphTargetInfluences.fill(0);const c=Math.min(7,Math.floor(progress)),n=Math.min(7,c+1),m=smooth(((progress-c)-.55)/.45);const keys=['','Entry','Gather','Work','Evidence','Records','Studio',''];if(keys[c]&&o.morphTargetDictionary)o.morphTargetInfluences[o.morphTargetDictionary[keys[c]]]=1-m;if(keys[n]&&o.morphTargetDictionary)o.morphTargetInfluences[o.morphTargetDictionary[keys[n]]]=m;}});host.dataset.chapter=String(chapter);host.dataset.detailDock=s.detailScene.active?s.detailScene.layout:'none';host.dataset.detailSettled=String(s.detailScene.active?detailBlend>.995:detailBlend<.005);host.dataset.detailReady=String(s.detailScene.active&&detailBlend>.995);host.dataset.objectSet=s.nodes.map(x=>x.id).join(',');host.dataset.manualRotation=`${viewYaw.toFixed(3)},${viewPitch.toFixed(3)}`;host.dataset.morph=String(progress.toFixed(2));
   spaceNodes(s.nodes,Math.min(7,Math.floor(s.progress)));
   s.nodes.forEach((item,i)=>{const e=anchors.current[i];if(!e)return;world.copy(item.t<0?new T.Vector3(0,0,0):flow(spaced.get(item.id)??item.t,progress));root.localToWorld(world);world.project(camera);const x=(world.x*.5+.5)*host.clientWidth,y=(-world.y*.5+.5)*host.clientHeight;e.style.transform=`translate3d(${x}px,${y}px,0) translate(-50%,-50%)`;e.style.visibility=world.z<1?'visible':'hidden';if(!still){e.style.setProperty('--orb-light-x',`${30+Math.sin(time*.25+i*.6)*12+mx*12}%`);e.style.setProperty('--orb-light-y',`${18+Math.cos(time*.22+i*.7)*7}%`);e.style.setProperty('--orb-glint-angle',`${125+Math.sin(time*.2+i)*25}deg`)}});
   galaxy.uniforms.uTime.value=time;galaxy.uniforms.uProgress.value=progress;galaxy.uniforms.uPointer.value.set(still?0:mx,still?0:my);galaxy.render(renderer);renderer.render(scene,camera);
  }frame=requestAnimationFrame(tick);
 }catch{cleanup();live.current.onUnavailable()}}void start();return()=>{disposed=true;cleanup()};},[]);
 return <div className="flow-render" data-assembly-visible={props.showAssembly}><div className="flow-vignette"/><div ref={mount} className="flow-webgl" tabIndex={0} role="group" aria-label="Infinity flow. Drag or use arrow keys to adjust the view."/>{ready&&<div className="flow-object-layer">{items.map((item,i)=><button ref={e=>{anchors.current[i]=e}} key={item.id} style={{'--item-color':item.color} as CSSProperties} data-scene-label={item.label} data-scene-action={item.action} data-scene-centre={item.id==='project'?'true':undefined} className={`flow-object flow-object--${item.id}${props.focus===item.id?' is-focused':''}`} onClick={()=>props.onSelect(item.action)} onMouseEnter={()=>{hover.current=item.id}} onMouseLeave={()=>{hover.current=null}} onFocus={()=>{hover.current=item.id}} onBlur={()=>{hover.current=null}} aria-label={`Explore ${item.label}`}><OriginalGlassIconOrb size={item.id==='project'?94:item.id==='result'?76:66} color={item.color} decorative>{item.id==='project'?<img src="/evidence-lane-icon.png" alt=""/>:item.brand?<img src={`/brands/${item.brand}`} alt=""/>:item.lane?<SourceLaneIcon lane={item.lane} size={30} decorative/>:<SemanticIcon name={item.icon} size={35}/>}</OriginalGlassIconOrb><span className="flow-object-label">{item.label}</span></button>)}</div>}</div>;
}
