'use client';
import {useState} from 'react';
import {motion,useMotionValue,useSpring,useReducedMotion,AnimatePresence} from 'framer-motion';
import {useMotion} from './experience';
import{SemanticIcon}from'./semantic-icon';
import{PulsatingBrain}from'./brain-core';
import styles from './interactive-brain-orb.module.css';
const topics=[['Sources','The original source identities and their recorded snapshots.','#66dafa'],['Plan','The current task order, scope and exact revision.','#c2a3ff'],['Results','Addressed outputs and the checks that were recorded.','#f6c878']];
export function InteractiveBrainOrb({icons}:{icons:{file:string;label:string}[]}){const[active,setActive]=useState(0);const{paused}=useMotion();const reduce=useReducedMotion();const x=useMotionValue(0),y=useMotionValue(0);const rx=useSpring(x,{stiffness:100,damping:18}),ry=useSpring(y,{stiffness:100,damping:18});const still=paused||reduce;return <section className={styles.component} aria-label="Interactive project context orb"><motion.div className={styles.stage} style={{rotateX:still?0:rx,rotateY:still?0:ry,'--tone':topics[active][2]} as never} onPointerMove={e=>{if(still)return;const r=e.currentTarget.getBoundingClientRect();x.set(-((e.clientY-r.top)/r.height-.5)*14);y.set(((e.clientX-r.left)/r.width-.5)*18)}} onPointerLeave={()=>{x.set(0);y.set(0)}}><div className={styles.halo}/><motion.div className={styles.outerRing} animate={still?{rotate:0}:{rotate:360}} transition={{duration:42,ease:'linear',repeat:Infinity}}/><motion.div className={styles.innerRing} animate={still?{rotate:0}:{rotate:-360}} transition={{duration:30,ease:'linear',repeat:Infinity}}/><svg className={styles.connections} viewBox="0 0 320 290" aria-hidden="true"><path d="M60 76 Q90 100 160 145 Q210 142 273 111 M160 145 Q180 211 159 251"/></svg><div className={styles.brainAnchor}><motion.button className={styles.brain} aria-label={`Project context: ${topics[active][0]}. Select the next context layer.`} onClick={()=>setActive((active+1)%3)} whileHover={still?{}:{scale:1.04}} whileTap={still?{}:{scale:.97}}><span className="brain-core-host"><PulsatingBrain size={245} color={topics[active][2]} active={!still} intensity={1.35} decorative/></span></motion.button></div>{[0,1,2].map(i=><motion.button key={i} className={`${styles.satellite} ${styles[`satellite${i}`]}`} aria-label={`Inspect ${topics[i][0]} context`} aria-pressed={i===active} onClick={()=>setActive(i)} whileHover={still?{}:{scale:1.15,y:-3}}><SemanticIcon name={(["sources","plan","results"] as const)[i]} size={25}/><span>{topics[i][0]}</span></motion.button>)}</motion.div><div className={styles.caption} aria-live="polite"><AnimatePresence mode="wait"><motion.div key={active} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}} transition={{duration:still?0:.18}}><strong>{topics[active][0]}</strong><p>{topics[active][1]}</p></motion.div></AnimatePresence></div></section>}
