"use client";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
const colors=[0x71cfee,0x6fbdff,0x83dbbf,0xe5c084,0xb5a0f5,0xe4aacb];
const radii=[2.15,2.60,3.05,3.50,3.95,4.40];
const phase=[.5,2.1,4.0,5.5,1.15,3.8];

export default function OrchestrationSystem({paused,reset,selected,onSelect}:{paused:boolean;reset:number;selected:number;onSelect:(n:number)=>void}){
 const hostRef=useRef<HTMLDivElement>(null),live=useRef({paused,reset,selected,onSelect});const[fallback,setFallback]=useState(false);
 useEffect(()=>{live.current={paused,reset,selected,onSelect};},[paused,reset,selected,onSelect]);
 useEffect(()=>{
  const host=hostRef.current;if(!host)return;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{setFallback(true);return;}
  renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor(0,0);host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,80);camera.position.set(0,5.2,12.2);camera.lookAt(0,0,0);
  const root=new THREE.Group();root.rotation.set(.05,0,-.18);scene.add(root);
  scene.add(new THREE.AmbientLight(0x9ebdda,.55));root.add(new THREE.PointLight(0x68cfff,70,30,1.45));const edgeLight=new THREE.DirectionalLight(0xe1ecff,1.8);edgeLight.position.set(4,6,8);scene.add(edgeLight);
  const geometries:THREE.BufferGeometry[]=[],materials:THREE.Material[]=[];const geo=<T extends THREE.BufferGeometry>(v:T)=>{geometries.push(v);return v;};const mat=<T extends THREE.Material>(v:T)=>{materials.push(v);return v;};
  const coreMat=mat(new THREE.ShaderMaterial({uniforms:{time:{value:0}},vertexShader:`varying vec3 p;varying vec3 n;varying vec3 eye;void main(){p=position;vec4 mv=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);eye=normalize(-mv.xyz);gl_Position=projectionMatrix*mv;}`,fragmentShader:`varying vec3 p;varying vec3 n;varying vec3 eye;uniform float time;
   float hash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}float fbm(vec3 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*noise(p);p=p*2.03+2.1;a*=.5;}return v;}
   void main(){vec3 q=p*3.4+vec3(time*.028,time*.012,0);float f=fbm(q+fbm(q*1.7));float plasma=pow(1.-abs(sin(f*17.+time*.12)),3.);float grain=noise(q*12.);float rim=pow(1.-max(dot(n,eye),0.),2.3);vec3 color=mix(vec3(.012,.12,.40),vec3(.34,.78,1.),f*.9+plasma*.7);color+=vec3(.48,.77,1.)*plasma*.62+vec3(.28,.62,.9)*rim;color+=grain*.035;gl_FragColor=vec4(color,1.);}`}));
  const core=new THREE.Mesh(geo(new THREE.SphereGeometry(1.28,80,64)),coreMat);root.add(core);
  const haloMat=mat(new THREE.ShaderMaterial({vertexShader:`varying vec3 n;varying vec3 eye;void main(){vec4 mv=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);eye=normalize(-mv.xyz);gl_Position=projectionMatrix*mv;}`,fragmentShader:`varying vec3 n;varying vec3 eye;void main(){float f=pow(1.-abs(dot(n,eye)),3.);gl_FragColor=vec4(.22,.68,1.,f*.5);}`,side:THREE.BackSide,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));root.add(new THREE.Mesh(geo(new THREE.SphereGeometry(1.39,64,48)),haloMat));
  const glowMat=mat(new THREE.ShaderMaterial({vertexShader:`varying vec2 uvp;void main(){uvp=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec2 uvp;void main(){float r=length(uvp-.5)*2.;float a=exp(-r*r*9.)*.32;gl_FragColor=vec4(.06,.44,1.,a);}`,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}));const glow=new THREE.Mesh(geo(new THREE.PlaneGeometry(7.5,7.5)),glowMat);glow.quaternion.copy(camera.quaternion);root.add(glow);
  const nodes:THREE.Mesh[]=[],orbits:THREE.LineBasicMaterial[]=[],groups:THREE.Group[]=[],routes:THREE.Line[]=[],pulses:THREE.Mesh[]=[];
  for(let i=0;i<6;i++){
   const group=new THREE.Group();group.rotation.set(i*.08,(i-2)*.065,i*.17);root.add(group);groups.push(group);
   const r=.25+(i%3)*.065;const ng=geo(new THREE.SphereGeometry(r,48,32));const nm=mat(new THREE.MeshPhysicalMaterial({color:colors[i],roughness:.24,metalness:.35,clearcoat:1,clearcoatRoughness:.2,emissive:colors[i],emissiveIntensity:.035}));const node=new THREE.Mesh(ng,nm);node.userData.layer=i;group.add(node);nodes.push(node);
   const pts=Array.from({length:241},(_,n)=>new THREE.Vector3(Math.cos(n/240*Math.PI*2)*radii[i],0,Math.sin(n/240*Math.PI*2)*radii[i]));const lineMat=mat(new THREE.LineBasicMaterial({color:colors[i],transparent:true,opacity:.19}));orbits.push(lineMat);group.add(new THREE.Line(geo(new THREE.BufferGeometry().setFromPoints(pts)),lineMat));
   const pathGeo=geo(new THREE.BufferGeometry());pathGeo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(33*3),3));const line=new THREE.Line(pathGeo,mat(new THREE.LineBasicMaterial({color:0x79d9ff,transparent:true,opacity:0})));root.add(line);routes.push(line);
   const pulse=new THREE.Mesh(geo(new THREE.SphereGeometry(.036,12,8)),mat(new THREE.MeshBasicMaterial({color:0xb3ecff})));root.add(pulse);pulses.push(pulse);
  }
  let seed=313;const random=()=>{seed=seed*16807%2147483647;return(seed-1)/2147483647;};const dustCount=innerWidth<700?1200:2700;const dustPos=new Float32Array(dustCount*3);
  for(let i=0;i<dustCount;i++){const a=random()*Math.PI*2,r=1.65+random()*2.8;dustPos.set([Math.cos(a)*r,(random()-.5)*.14,Math.sin(a)*r],i*3);}
  const dustGeo=geo(new THREE.BufferGeometry());dustGeo.setAttribute('position',new THREE.BufferAttribute(dustPos,3));const dust=new THREE.Points(dustGeo,mat(new THREE.PointsMaterial({color:0x7ba5c5,size:.012,transparent:true,opacity:.32,depthWrite:false,blending:THREE.AdditiveBlending})));root.add(dust);
  const reduce=matchMedia('(prefers-reduced-motion: reduce)');let time=0,last=0,frame=0,visible=true,lastReset=0,targetX=.05,targetY=0,drag=false,px=0,py=0,moved=false;
  const resize=()=>{const r=host.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.position.z=r.width<500?17.5:12.2;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(host);resize();const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;});io.observe(host);
  const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),temp=new THREE.Vector3(),localPoint=new THREE.Vector3();
  const down=(e:PointerEvent)=>{if(e.pointerType==='touch')return;drag=true;moved=false;px=e.clientX;py=e.clientY;host.setPointerCapture(e.pointerId);};
  const move=(e:PointerEvent)=>{if(!drag)return;const dx=e.clientX-px,dy=e.clientY-py;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;targetY+=dx*.003;targetX=Math.max(-.6,Math.min(.6,targetX+dy*.003));px=e.clientX;py=e.clientY;};
  const up=(e:PointerEvent)=>{drag=false;if(moved)return;const r=host.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(nodes,false)[0];if(hit)live.current.onSelect(hit.object.userData.layer);};const cancel=()=>{drag=false;};
  const key=(e:KeyboardEvent)=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();if(e.key==='ArrowLeft')targetY-=.15;if(e.key==='ArrowRight')targetY+=.15;if(e.key==='ArrowUp')targetX-=.15;if(e.key==='ArrowDown')targetX+=.15;};const lost=(e:Event)=>{e.preventDefault();setFallback(true);};
  host.addEventListener('pointerdown',down);host.addEventListener('pointermove',move);host.addEventListener('pointerup',up);host.addEventListener('pointercancel',cancel);host.addEventListener('keydown',key);renderer.domElement.addEventListener('webglcontextlost',lost);
  const render=(now:number)=>{frame=requestAnimationFrame(render);const dt=Math.min((now-last)/1000,.05);last=now;if(!visible||document.hidden||renderer.getContext().isContextLost())return;if(!live.current.paused&&!reduce.matches)time+=dt;if(lastReset!==live.current.reset){time=0;targetX=.05;targetY=0;lastReset=live.current.reset;}const ease=reduce.matches?1:.045;root.rotation.x+=(targetX-root.rotation.x)*ease;root.rotation.y+=(targetY-root.rotation.y)*ease;coreMat.uniforms.time.value=time;core.rotation.y=time*.026;dust.rotation.y=time*.013;
   for(let i=0;i<6;i++){const a=phase[i]+time*(.085-i*.008);nodes[i].position.set(Math.cos(a)*radii[i],0,Math.sin(a)*radii[i]);nodes[i].rotation.y=time*.08;const active=i===live.current.selected;orbits[i].opacity+=((active?.60:.17)-orbits[i].opacity)*.06;nodes[i].scale.setScalar(active?1.22:1);groups[i].updateMatrix();localPoint.copy(nodes[i].position).applyMatrix4(groups[i].matrix);const attr=routes[i].geometry.attributes.position as THREE.BufferAttribute;for(let j=0;j<33;j++){const t=j/32;temp.copy(localPoint).multiplyScalar(t);temp.y+=Math.sin(t*Math.PI)*.70;attr.setXYZ(j,temp.x,temp.y,temp.z);}attr.needsUpdate=true;(routes[i].material as THREE.LineBasicMaterial).opacity=active?.4:.04;const t=(time*.16+i*.17)%1;pulses[i].position.copy(localPoint).multiplyScalar(t);pulses[i].position.y+=Math.sin(t*Math.PI)*.70;pulses[i].visible=active;pulses[i].scale.setScalar(1+Math.sin(t*Math.PI));}
   renderer.render(scene,camera);};frame=requestAnimationFrame(render);
  return()=>{cancelAnimationFrame(frame);observer.disconnect();io.disconnect();host.removeEventListener('pointerdown',down);host.removeEventListener('pointermove',move);host.removeEventListener('pointerup',up);host.removeEventListener('pointercancel',cancel);host.removeEventListener('keydown',key);renderer.domElement.removeEventListener('webglcontextlost',lost);geometries.forEach(v=>v.dispose());materials.forEach(v=>v.dispose());renderer.dispose();renderer.domElement.remove();};
 },[]);
 return <div ref={hostRef} tabIndex={0} role="group" aria-label="Interactive plugin orchestration. Drag or use arrow keys to rotate. Choose a layer below." style={{width:'100%',height:'100%',cursor:'grab',touchAction:'pan-y'}}>{fallback?<div style={{display:'grid',placeContent:'center',height:'100%',textAlign:'center',color:'#b9d6e8'}}>The 3D view requires WebGL.<br/>Use the layer controls to explore the system.</div>:null}</div>;
}
