'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import type * as THREE from 'three';
import {OriginalGlassIconOrb as Orb} from './original-glass';
import {SemanticIcon} from './semantic-icon';
import {SourceLaneIcon} from './source-lane-icon';
import {useSceneFocus} from './scene-focus';
import {createProductUniverse} from './product-universe';
import {createInteractiveStarfield} from './interactive-starfield';
import {anatomyNodes,type AnatomyNode} from '../data/product-anatomy';
import {createHomeOpticalRoute} from './home-optical-routes';
import {pageConnectionDesigns} from './page-connection-designs';
import {createProductSceneArt} from './product-scene-art';

type Props={progress:number;nodes:AnatomyNode[];paused:boolean;showAssembly:boolean;onSelect:(id:string)=>void;onChapterView?:(chapter:number)=>void;onUnavailable:()=>void};
export function ProductAnatomyScene(props:Props){
 const {state:focus}=useSceneFocus();const live=useRef({...props,focus});const mount=useRef<HTMLDivElement>(null),anchors=useRef(new Map<string,HTMLButtonElement>()),centre=useRef<HTMLButtonElement>(null);const[ready,setReady]=useState(false),[renderNodes,setRenderNodes]=useState(props.nodes),[viewChapter,setViewChapter]=useState(Math.floor(props.progress));
 useEffect(()=>{live.current={...props,focus}},[props,focus]);
 useEffect(()=>{const element=mount.current;if(!element)return;const host=element;let disposed=false,cleanup=()=>{};
 async function start(){try{
  const T=await import('three');const[{GLTFLoader},{RoomEnvironment}]=await Promise.all([import('three/examples/jsm/loaders/GLTFLoader.js'),import('three/examples/jsm/environments/RoomEnvironment.js')]);if(disposed)return;
  const renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.appendChild(renderer.domElement);
  const scene=new T.Scene(),root=new T.Group(),camera=new T.PerspectiveCamera(38,1,.1,100);camera.position.z=16;scene.add(root);const galaxy=createProductUniverse(T),stars=createInteractiveStarfield(T,1600);scene.add(galaxy.display,stars.group);
  const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pmrem.fromScene(room,.03);scene.environment=environment.texture;scene.environmentIntensity=.9;pmrem.dispose();room.dispose();scene.add(new T.HemisphereLight(0xc8efff,0x101e39,1.1));const key=new T.DirectionalLight(0xedfbff,2);key.position.set(-3,5,7);scene.add(key);const rim=new T.DirectionalLight(0x74c9ef,1.5);rim.position.set(5,-1,-3);scene.add(rim);
  const sphereGeo=new T.SphereGeometry(.52,40,24),ringGeo=new T.TorusGeometry(.535,.012,8,72);
  const centreShell=new T.Mesh(new T.SphereGeometry(1.04,48,32),new T.MeshPhysicalMaterial({color:0x9bcced,metalness:.04,roughness:.045,transmission:.8,thickness:.3,transparent:true,opacity:.025,ior:1.45,clearcoat:1,depthWrite:false}));centreShell.visible=false;root.add(centreShell);const art=createProductSceneArt(T,root);const windowGeometry=new T.BoxGeometry(2.7,1.6,.045);const phases=Array.from({length:6},(_,i)=>new Map(anatomyNodes(i).map(n=>[n.id,n.position])));
  let cube:THREE.Group|undefined;let frame=0,last=0,time=0,progress=0,blend=0,visible=true,mx=0,my=0,displayX=.73;let nodeKey='',lastViewChapter=-1;let drag=false,lastPointerX=0,lastPointerY=0,yaw=0,pitch=0;
  type Lens={group:THREE.Group;line:THREE.Line;ribbon:THREE.Mesh;ribbonGeometry:THREE.BufferGeometry;ribbonMaterial:THREE.MeshPhysicalMaterial;geometry:THREE.BufferGeometry;material:THREE.LineBasicMaterial;shell:THREE.MeshPhysicalMaterial;ring:THREE.MeshBasicMaterial;position:THREE.Vector3;visual?:AnatomyNode['visual'];active:boolean;opacity:number;optical:ReturnType<typeof createHomeOpticalRoute>};
  const orbit=createHomeOpticalRoute(T,root,256,1.35,pageConnectionDesigns.product);
  const orbitCurves=Array.from({length:6},(_,chapter)=>{let points=anatomyNodes(chapter).filter(node=>node.visual!=='window').map(node=>new T.Vector3(...node.position));points.sort((a,b)=>Math.atan2(a.y,a.x)-Math.atan2(b.y,b.x));if(points.length===2)points=[points[0],new T.Vector3(0,-2.0,-.3),points[1],new T.Vector3(0,2.0,.3)];return new T.CatmullRomCurve3(points,true,'centripetal',.5)});
  const orbitFrom=new T.Vector3(),orbitTo=new T.Vector3();
  const lenses=new Map<string,Lens>();const projected=new T.Vector3();
  const removeLens=(lens:Lens)=>{lens.optical.dispose();root.remove(lens.group,lens.line,lens.ribbon);lens.ribbonGeometry.dispose();lens.ribbonMaterial.dispose();lens.geometry.dispose();lens.material.dispose();lens.shell.dispose();lens.ring.dispose()};
  const sync=(nodes:AnatomyNode[])=>{const ids=new Set(nodes.map(n=>n.id));for(const[id,lens]of lenses){if(!ids.has(id)&&lens.active)lens.opacity=Math.min(lens.opacity,lens.material.opacity/.7);lens.active=ids.has(id);}for(const node of nodes)if(!lenses.has(node.id)){const group=new T.Group();const shell=new T.MeshPhysicalMaterial({color:node.color,metalness:.03,roughness:.055,transmission:.78,thickness:.20,ior:1.46,transparent:true,opacity:.24,clearcoat:1,depthWrite:false});const ring=new T.MeshBasicMaterial({color:node.color,transparent:true,opacity:.55});if(node.visual==='window'){group.rotation.set(.05,-.12,-.03)}else group.add(new T.Mesh(sphereGeo,shell),new T.Mesh(ringGeo,ring));root.add(group);const geometry=new T.BufferGeometry().setFromPoints(Array.from({length:40},()=>new T.Vector3()));const material=new T.LineBasicMaterial({color:new T.Color(node.color).lerp(new T.Color(0xe8fcff),.44),transparent:true,opacity:.7,toneMapped:false});const line=new T.Line(geometry,material);root.add(line);const ribbonGeometry=new T.BufferGeometry(),ribbonPositions=new Float32Array(40*6*3),ribbonNormals=new Float32Array(ribbonPositions.length),ribbonIndices=[];for(let strand=0;strand<3;strand++)for(let j=0;j<39;j++){const k=(strand*40+j)*2;ribbonIndices.push(k,k+1,k+2,k+1,k+3,k+2)}ribbonGeometry.setAttribute('position',new T.BufferAttribute(ribbonPositions,3));ribbonGeometry.setAttribute('normal',new T.BufferAttribute(ribbonNormals,3));ribbonGeometry.setIndex(ribbonIndices);const ribbonMaterial=new T.MeshPhysicalMaterial({color:new T.Color(node.color).lerp(new T.Color(0xf0fbff),.62),metalness:.35,roughness:.16,clearcoat:1,transparent:true,opacity:0,depthWrite:false,side:T.DoubleSide});const ribbon=new T.Mesh(ribbonGeometry,ribbonMaterial);ribbon.frustumCulled=false;root.add(ribbon);const optical=createHomeOpticalRoute(T,root,96,1,pageConnectionDesigns.product);lenses.set(node.id,{optical,group,line,ribbon,ribbonGeometry,ribbonMaterial,geometry,material,shell,ring,position:new T.Vector3(),visual:node.visual,active:true,opacity:0})}};
  const updateRibbon=(lens:Lens,alpha:number)=>{lens.line.visible=false;lens.ribbon.visible=false;lens.optical.update(time,(t,target)=>target.copy(curve(lens.position,t,lens.visual==='runtime'?1.05:lens.visual==='window'?.9:.53)),lens.visual==='window'?alpha:0)};

  const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();galaxy.resize(host.clientWidth,host.clientHeight)};resize();const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(host);const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting});observer.observe(host);
  const pointer=(event:PointerEvent)=>{mx=event.clientX/innerWidth-.5;my=event.clientY/innerHeight-.5;stars.pointer(mx*2,-my*2);if(drag){yaw=Math.max(-.2,Math.min(.2,yaw+(event.clientX-lastPointerX)*.0012));pitch=Math.max(-.14,Math.min(.14,pitch+(event.clientY-lastPointerY)*.0008));lastPointerX=event.clientX;lastPointerY=event.clientY}};const down=(event:PointerEvent)=>{if(live.current.paused||live.current.focus.active||innerWidth<=1000||event.clientX<innerWidth*.46||(event.target instanceof Element&&event.target.closest('button,a,input')))return;drag=true;lastPointerX=event.clientX;lastPointerY=event.clientY};const up=()=>{drag=false};const reset=()=>{drag=false;yaw=0;pitch=0};window.addEventListener('pointerdown',down);window.addEventListener('pointerup',up);window.addEventListener('pointercancel',up);window.addEventListener('scroll',reset,{passive:true});window.addEventListener('pointermove',pointer,{passive:true});window.addEventListener('blur',stars.leave);const lost=(event:Event)=>{event.preventDefault();live.current.onUnavailable()};renderer.domElement.addEventListener('webglcontextlost',lost);
  cleanup=()=>{cancelAnimationFrame(frame);resizeObserver.disconnect();observer.disconnect();window.removeEventListener('pointerdown',down);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',up);window.removeEventListener('scroll',reset);window.removeEventListener('pointermove',pointer);window.removeEventListener('blur',stars.leave);renderer.domElement.removeEventListener('webglcontextlost',lost);orbit.dispose();for(const lens of lenses.values())removeLens(lens);sphereGeo.dispose();ringGeo.dispose();windowGeometry.dispose();art.dispose();centreShell.geometry.dispose();centreShell.material.dispose();cube?.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});galaxy.dispose();stars.dispose();environment.dispose();renderer.dispose();renderer.domElement.remove()};
  const model=await new GLTFLoader().loadAsync('/product/evidence-lane-cube.glb');if(disposed){model.scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});return}cube=model.scene;cube.scale.setScalar(.57);cube.traverse(o=>{if(o instanceof T.Mesh){const old=Array.isArray(o.material)?o.material:[o.material];const replacement=old.map(original=>{const name=original.name.replaceAll('_',' ').toLowerCase(),mark=name.includes('mark');const colour=mark?0xf1fbff:name.includes('blue')?0x75c9e8:name.includes('pearl')?0xc4e9f3:0x98cfe7;const material=new T.MeshPhysicalMaterial({name:original.name,color:colour,metalness:0,roughness:mark?.15:.045,transmission:mark?0:.78,thickness:.24,ior:1.46,transparent:true,opacity:mark?.14:.30,clearcoat:1,clearcoatRoughness:.03,envMapIntensity:.65,depthWrite:false,side:mark?T.DoubleSide:T.FrontSide});original.dispose();return material});o.material=Array.isArray(o.material)?replacement:replacement[0]}});const innerBrand=cube.clone(true);innerBrand.scale.setScalar(.44);innerBrand.rotation.set(0,0,0);innerBrand.traverse(o=>{if(o instanceof T.Mesh){const original=Array.isArray(o.material)?o.material:[o.material];const solid=original.map(source=>{const material=source.clone();if(material instanceof T.MeshPhysicalMaterial){material.transmission=0;material.opacity=1;material.transparent=false;material.depthWrite=true;material.side=T.DoubleSide;material.roughness=.19;}return material});o.material=Array.isArray(o.material)?solid:solid[0]}});cube.add(innerBrand);cube.rotation.set(.22,-.57,0);art.attachCube(cube);root.add(cube);host.dataset.model='evidence-lane-brand-cube';host.dataset.universe='product-teal-mist-and-flares';host.dataset.connectionStyle='product-orbital-records';setReady(true);
  const project=(element:HTMLElement|undefined|null,position:THREE.Vector3)=>{if(!element)return;projected.copy(position);root.localToWorld(projected);projected.project(camera);element.style.transform=`translate3d(${(projected.x*.5+.5)*host.clientWidth}px,${(-projected.y*.5+.5)*host.clientHeight}px,0) translate(-50%,-50%)`;element.style.visibility=projected.z<1?'visible':'hidden'};
  const smooth=(n:number)=>{n=Math.max(0,Math.min(1,n));return n*n*(3-2*n)};
  const curve=(end:THREE.Vector3,t:number,radius=.53)=>{const length=end.length(),direction=end.clone().normalize();let surface=.58;if(cube){const local=direction.clone().applyQuaternion(cube.quaternion.clone().invert());surface=.58/Math.max(Math.abs(local.x),Math.abs(local.y),Math.abs(local.z),.01)}const start=direction.clone().multiplyScalar(length<1.3?length*.15:surface),finish=end.clone().addScaledVector(direction,-Math.min(radius,length*.2));const side=new T.Vector3(-end.y,end.x,0).normalize();const c1=start.clone().lerp(finish,.25).addScaledVector(side,.48),c2=start.clone().lerp(finish,.73).addScaledVector(side,-.30);c1.z+=.34;c2.z+=.28;const point=start.clone().multiplyScalar((1-t)**3).addScaledVector(c1,3*(1-t)**2*t).addScaledVector(c2,3*(1-t)*t*t).addScaledVector(finish,t*t*t);return point.addScaledVector(side,Math.sin(t*Math.PI)*Math.sin(time*.7+t*5+end.x)*.10)};
  function tick(now:number){if(disposed)return;frame=requestAnimationFrame(tick);const dt=Math.min(.04,(now-last)/1000);last=now;if(!visible||document.hidden)return;const s=live.current;const desired=s.focus.active?Math.floor(s.progress):s.progress;progress+=(desired-progress)*.09;if(!s.paused)time+=dt;host.dataset.waveTime=time.toFixed(3);blend+=((s.focus.active?1:0)-blend)*.10;const chapter=Math.min(5,Math.floor(progress));const currentNodes=anatomyNodes(chapter),futureNodes=anatomyNodes(Math.min(5,chapter+1)),currentMap=new Map(currentNodes.map(n=>[n.id,n])),futureMap=new Map(futureNodes.map(n=>[n.id,n]));const sceneNodes=Array.from(new Map([...currentNodes,...futureNodes].map(n=>[n.id,n])).values());const nextKey=sceneNodes.map(n=>n.id).join('|');if(nextKey!==nodeKey){sync(sceneNodes);setRenderNodes(sceneNodes);nodeKey=nextKey}
   const halfH=16*Math.tan(19*Math.PI/180),halfW=halfH*camera.aspect;const morph=s.focus.active||chapter===5?0:smooth(((progress-chapter)-.55)/.45);const normalX=.73;displayX+=(normalX-displayX)*.07;const targetX=s.focus.active?s.focus.dock.x:normalX,targetY=s.focus.active?s.focus.dock.y:.51;root.position.set(T.MathUtils.lerp((displayX-.5)*halfW*2,(targetX-.5)*halfW*2,blend),T.MathUtils.lerp(-.25-Math.max(0,(parseFloat(document.documentElement.style.getPropertyValue('--site-header-height'))||116)-scrollY)/host.clientHeight*halfH*2,(.5-targetY)*halfH*2,blend),0);const baseScale=host.clientWidth<1450?.72:.88;const detailScale=s.focus.layout==='above'||s.focus.layout==='below'?.37:s.nodes.length>10?(host.clientWidth<1450?.60:.70):.56;root.scale.setScalar(T.MathUtils.lerp(baseScale,detailScale,blend));root.visible=s.showAssembly&&!(s.focus.active&&s.focus.companion?.kind==='controls');root.rotation.set(Math.sin(time*.14)*.018+pitch*(1-blend),Math.sin(time*.11)*.025+yaw*(1-blend),0);host.dataset.manualRotation=(Math.abs(yaw)+Math.abs(pitch)).toFixed(4);if(cube)cube.rotation.y=-.57+Math.sin(time*.23)*.065;camera.position.set(s.focus.active||s.paused?0:mx*.10,s.focus.active||s.paused?0:-my*.08,16);if(!s.paused){key.position.set(-3+Math.sin(time*.22)*1.3+mx*1.6,4.7+Math.cos(time*.19)*.6,7);rim.position.set(4.7+Math.cos(time*.17),-1+Math.sin(time*.21),-3);key.intensity=2+Math.sin(Math.PI*morph)*.65;}camera.lookAt(0,0,0);camera.updateMatrixWorld();root.updateMatrixWorld(true);
   orbit.update(time,(t,out)=>{orbitCurves[chapter].getPoint(t,orbitFrom);orbitCurves[Math.min(5,chapter+1)].getPoint(t,orbitTo);out.copy(orbitFrom).lerp(orbitTo,morph)});
   let packetCount=0;for(let i=0;i<12;i++){art.packet(packetCount++,orbit.pointAt((time*.028+i/12)%1,new T.Vector3()),new T.Color(0xbedce9))}const targets=new Map<string,THREE.Vector3>();
   for(const node of sceneNodes){const lens=lenses.get(node.id)!;const from=currentMap.get(node.id),to=futureMap.get(node.id);const target=(from?new T.Vector3(...from.position):new T.Vector3()).lerp(to?new T.Vector3(...to.position):new T.Vector3(),morph);targets.set(node.id,target);lens.position.copy(target);lens.opacity+=(1-lens.opacity)*.15;const alpha=lens.opacity*((from?1-morph:0)+(to?morph:0));lens.group.position.copy(lens.position);lens.group.visible=node.visual!=='files'&&node.visual!=='runtime';if(node.visual!=='window')lens.group.rotation.y=Math.sin(time*.2)*.1;lens.shell.opacity=.24*alpha;lens.ring.opacity=.28*alpha;const positions=lens.geometry.attributes.position as THREE.BufferAttribute;for(let k=0;k<positions.count;k++){const point=curve(lens.position,k/(positions.count-1),lens.visual==='runtime'?1.05:lens.visual==='window'?.9:.53);positions.setXYZ(k,point.x,point.y,point.z)}positions.needsUpdate=true;lens.material.opacity=(.62+Math.sin(time*.45+node.position[0])*.08)*alpha;updateRibbon(lens,alpha);for(let bead=0;bead<(lens.visual==='window'?2:0);bead++){const t=(time*.14+bead/3+node.position[0]*.06+10)%1;art.packet(packetCount++,lens.optical.pointAt(t,new T.Vector3()),lens.material.color.clone().multiplyScalar(alpha));}const element=anchors.current.get(node.id);project(element,lens.position);if(element){element.style.setProperty('opacity',String(alpha),'important');element.style.pointerEvents=alpha>.75?'auto':'none';element.tabIndex=alpha>.75?0:-1;element.dataset.poseChapter=String(from&&!to?chapter:to&&!from?Math.min(5,chapter+1):morph>.5?Math.min(5,chapter+1):chapter);const label=element.querySelector<HTMLElement>('.flow-object-label');if(label)label.style.opacity=String(smooth((alpha-.65)/.35));if(!s.paused){element.style.setProperty('--orb-light-x',`${35+Math.sin(time*.26+node.position[0]) *14+mx*12}%`);element.style.setProperty('--orb-light-y',`${18+Math.cos(time*.24+node.position[1])*7}%`);element.style.setProperty('--orb-glint-angle',`${120+Math.sin(time*.21+node.position[0])*28}deg`)}}}
   for(const[id,lens]of lenses)if(!lens.active){lens.opacity*=.84;lens.position.multiplyScalar(.92);lens.group.position.copy(lens.position);lens.shell.opacity=.24*lens.opacity;lens.ring.opacity=.28*lens.opacity;lens.material.opacity=.6*lens.opacity;const positions=lens.geometry.attributes.position as THREE.BufferAttribute;for(let k=0;k<positions.count;k++){const point=curve(lens.position,k/(positions.count-1),lens.visual==='runtime'?1.05:lens.visual==='window'?.9:.53);positions.setXYZ(k,point.x,point.y,point.z)}positions.needsUpdate=true;updateRibbon(lens,lens.opacity);if(lens.opacity<.02){removeLens(lens);lenses.delete(id)}}
   art.flush(packetCount);art.update(time,chapter,new Map(Array.from(lenses,([id,lens])=>[id,lens.position])),new Map(Array.from(lenses,([id,lens])=>[id,lens.active?Math.min(1,lens.material.opacity/.62):lens.opacity])));
   project(centre.current,new T.Vector3());const fraction=progress-Math.floor(progress),amount=Math.sin(Math.PI*Math.max(0,(fraction-.55)/.45))**2*(1-blend)*.6;const displacement=stars.update(dt,camera,progress,s.paused,{amount,matrix:root.matrixWorld,point:t=>new T.Vector3(Math.cos(t*Math.PI*2)*3.7,Math.sin(t*Math.PI*2)*2.7,0)});const seenChapter=morph>.5?Math.min(5,chapter+1):chapter;if(seenChapter!==lastViewChapter){lastViewChapter=seenChapter;setViewChapter(seenChapter);live.current.onChapterView?.(seenChapter)}host.dataset.chapter=String(chapter);host.dataset.chapterView=String(seenChapter);host.dataset.morph=morph.toFixed(3);host.dataset.progress=progress.toFixed(3);host.dataset.transitionState=Math.abs(progress-desired)<.02?'settled':'moving';host.dataset.sceneReady=String(!s.focus.active&&blend<.005&&Math.abs(displayX-normalX)<.002&&currentNodes.every(n=>(lenses.get(n.id)?.position.distanceTo(targets.get(n.id)??new T.Vector3(...n.position))??1)<.03));host.dataset.detailReady=String(s.focus.active&&blend>.995);host.dataset.motionEnergy=String(Math.sin(Math.PI*morph));host.dataset.particleDisplacement=displacement.toFixed(4);host.dataset.nodes=String(s.nodes.length);galaxy.uniforms.uTime.value=time;galaxy.uniforms.uProgress.value=progress+2;galaxy.uniforms.uPointer.value.set(s.paused?0:mx*.7,s.paused?0:my*.7);galaxy.render(renderer);renderer.render(scene,camera);
  }frame=requestAnimationFrame(tick);
 }catch{cleanup();live.current.onUnavailable()}}void start();return()=>{disposed=true;cleanup()};},[]);
 return <div className="flow-render product-render" data-assembly-visible={props.showAssembly}><div ref={mount} className="flow-webgl product-webgl" aria-hidden="true"/>{ready&&<div className="flow-object-layer product-object-layer" data-dense={renderNodes.length>10}>{renderNodes.map(node=><button key={node.id} ref={e=>{if(e)anchors.current.set(node.id,e);else anchors.current.delete(node.id)}} className="flow-object product-node" data-visual={node.visual} style={{'--item-color':node.color} as CSSProperties} data-scene-action={node.id} data-scene-label={node.name} onClick={()=>props.onSelect(node.id)} aria-label={'Explore '+node.name}><>{node.visual==='window'?<span className="product-studio-peek"><span className="product-studio-peek-title"><Orb size={28} color={node.color} decorative><SemanticIcon name="studio"/></Orb><strong>Studio</strong><small>READ-ONLY</small></span><span className="product-studio-peek-tabs"><i>Plan</i><i>Evidence</i><i>Tools</i></span><span className="product-studio-peek-diagram"><svg viewBox="0 0 90 65" aria-hidden="true"><path d="M15 13 C35 -2 62 -2 76 12 C91 30 89 44 76 54 C55 70 34 68 16 53 C0 38 1 24 15 13" fill="none" stroke="#91deeb" strokeWidth="1"/><circle cx="15" cy="13" r="6" fill="#b897f3"/><circle cx="16" cy="53" r="6" fill="#73dbe9"/><circle cx="76" cy="12" r="6" fill="#ebbc7a"/><circle cx="76" cy="54" r="6" fill="#ee9ccd"/><image href="/evidence-lane-icon.png" x="28" y="16" width="34" height="34"/></svg><span><b>Project records</b><i>Current Plan</i><i>Evidence &amp; checks</i><i>Tools &amp; context</i></span></span></span>:<><Orb className={node.visual?'product-visual-proxy':undefined} size={renderNodes.length>10?54:68} color={node.color} decorative>{node.image?<img src={node.image} alt=""/>:node.lane?<SourceLaneIcon lane={node.lane} decorative/>:<SemanticIcon name={node.icon}/>}</Orb><span className="flow-object-label" style={renderNodes.length>10?{left:node.position[0]<0?'auto':'calc(100% + 9px)',right:node.position[0]<0?'calc(100% + 9px)':'auto',top:'50%',translate:'none',transform:'translateY(-50%)',margin:0,width:110}:undefined}>{node.name}</span></>}</></button>)}<button ref={centre} data-pose-chapter={viewChapter} className="flow-object flow-object--project product-cube-control" data-scene-centre="true" data-scene-action={'anatomy:'+Math.floor(props.progress)} data-scene-label={Math.floor(props.progress)===4?'Project records':'Evidence Lane'} data-detail-image="/evidence-lane-icon.png" aria-label="Explore this project assembly" onClick={()=>props.onSelect('anatomy:'+Math.floor(props.progress))}><span className="product-cube-hit"/><span className="flow-object-label">{Math.floor(props.progress)===4?'Project records':'Evidence Lane'}</span></button></div>}</div>;
}
