'use client';
import {useEffect,useRef,useState,useMemo,useCallback} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {useMotion} from './experience';
import {useSceneFocus,triggerIdentity} from './scene-focus';
import {OriginalGlassIconOrb as Orb,OriginalGlassPill as Pill} from './original-glass';
import {SemanticIcon} from './semantic-icon';
import {SourceLaneIcon} from './source-lane-icon';
import {anatomyChapters,anatomyNodes} from '../data/product-anatomy';
import {ProductAnatomyDetails} from './product-anatomy-details';
import './home-flow.css';
import './neon-glass.css';
import './product-anatomy.css';
const Scene=dynamic(()=>import('./product-anatomy-scene').then(m=>m.ProductAnatomyScene),{ssr:false});
export function ProductAnatomy(){
 const {paused,toggle}=useMotion(),focus=useSceneFocus();const[progress,setProgress]=useState(0),[visibleChapter,setVisibleChapter]=useState(0),[selected,setSelected]=useState<string|null>(null),[staticView,setStaticView]=useState(false),[fallback,setFallback]=useState(false),[within,setWithin]=useState(true);const story=useRef<HTMLDivElement>(null),isOpen=useRef(false);isOpen.current=!!selected;const chapter=Math.min(5,Math.floor(progress)),nodes=useMemo(()=>anatomyNodes(chapter),[chapter]);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const resize=()=>setStaticView(media.matches||innerWidth<=1000);resize();media.addEventListener('change',resize);window.addEventListener('resize',resize);return()=>{media.removeEventListener('change',resize);window.removeEventListener('resize',resize)}},[]);
 useEffect(()=>{let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(!story.current||isOpen.current)return;let next=0;story.current.querySelectorAll<HTMLElement>('[data-product-chapter]').forEach((element,i)=>{const r=element.getBoundingClientRect();if(r.top<=innerHeight*.42)next=i+Math.max(0,Math.min(.999,(innerHeight*.42-r.top)/r.height))});setProgress(next);setWithin(story.current.getBoundingClientRect().bottom>innerHeight*.4)})};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[]);
 const open=useCallback((id:string)=>{const pose=(document.activeElement as HTMLElement|null)?.dataset.poseChapter;if(pose!==undefined)setProgress(Number(pose));focus.select(id,triggerIdentity(document.activeElement));setSelected(id)},[focus.select]);const close=useCallback(()=>{setSelected(null);requestAnimationFrame(()=>{let next=0;story.current?.querySelectorAll<HTMLElement>('[data-product-chapter]').forEach((element,i)=>{const r=element.getBoundingClientRect();if(r.top<=innerHeight*.42)next=i+Math.max(0,Math.min(.999,(innerHeight*.42-r.top)/r.height))});setProgress(next)})},[]);
 const go=(index:number)=>{const target=document.querySelector(`#product-chapter-${index} .flow-copy`);if(target)window.scrollTo({top:target.getBoundingClientRect().top+scrollY-150,behavior:staticView?'instant':'smooth'})};const still=staticView||fallback;
 return <main id="main" className="home-flow product-anatomy" data-static={still}><div className="flow-story product-story" ref={story}>{!still&&<div className="flow-scene-boundary"><Scene showAssembly={within} progress={progress} nodes={nodes} paused={paused} onChapterView={setVisibleChapter} onSelect={open} onUnavailable={()=>setFallback(true)}/></div>}{within&&!still&&<nav className="flow-chapters" aria-label="Product story">{anatomyChapters.map((item,i)=><a key={item.name} href={'#product-chapter-'+i} aria-current={visibleChapter===i?'step':undefined} onClick={e=>{e.preventDefault();go(i)}}><span>{String(i).padStart(2,'0')}</span><i/><b>{item.name}</b></a>)}</nav>}
 {anatomyChapters.map((item,i)=><section key={item.name} id={'product-chapter-'+i} data-product-chapter className="flow-section product-chapter"><div className="flow-copy product-copy"><p className="flow-kicker">{i===0?'EVIDENCE LANE / PRODUCT':String(i).padStart(2,'0')+' / '+item.name}</p>{i===0?<h1>{item.heading}<br/><em>{item.accent}</em></h1>:<h2>{item.heading}<br/><em>{item.accent}</em></h2>}<p>{item.body}</p><p className="product-node-hint">{i===4?'Open the centre cube or either location.':'Open a node to inspect its own detail.'}</p>{i===0&&<button className="product-scroll-cue" onClick={()=>go(1)}>Explore the connected records <span>↓</span></button>}{i===1&&<p className="product-caption">Separate records. Explicit links. One project.</p>}{i===3&&<p className="product-caption">A question keeps the Plan unchanged.<br/>A steer revises the affected work.<br/>Execution follows the selected task.</p>}{i===4&&<p className="product-caption">Persistent local Windows · Codex Desktop Stable & Beta</p>}{i===5&&<p className="product-caption">View, navigate, open, minimise and restore.<br/>Direct project changes through Codex.</p>}</div>{still&&<div className="product-static-assembly" data-detail-group><Pill data-detail-action={'anatomy:'+i} data-detail-name="Evidence Lane" leading={<Orb size={70} decorative><img src="/evidence-lane-icon.png" alt=""/></Orb>} onClick={()=>open('anatomy:'+i)}>Evidence Lane</Pill><div>{anatomyNodes(i).map(n=><Pill key={n.id} data-detail-action={n.id} leading={<Orb color={n.color} decorative>{n.image?<img src={n.image} alt=""/>:n.lane?<SourceLaneIcon lane={n.lane} decorative/>:<SemanticIcon name={n.icon}/>}</Orb>} onClick={()=>open(n.id)}>{n.name}</Pill>)}</div></div>}</section>)}
 </div><section className="flow-finish product-finish"><p className="flow-kicker">TAKE THE NEXT STEP</p><h2>Choose the intention.<br/><em>Follow its workflow.</em></h2><p>Explore the public workflows or see how work moves through the project.</p><div className="product-next-links"><Link href="/workflows">Find a workflow ↗</Link><Link href="/how-it-works">How the work runs ↗</Link></div><p className="catalog-note">Source candidate · See the release guide for distribution and qualification status.</p></section>{within&&!still&&<div className="flow-controls"><button onClick={toggle} aria-pressed={paused}>{paused?'Play motion':'Pause motion'}</button></div>}<ProductAnatomyDetails selected={selected} onClose={close} onNavigate={open}/></main>;
}
