'use client';
import {useEffect,type CSSProperties} from 'react';
import {OriginalGlassPopup} from './original-popup';
import {OriginalGlassIconOrb as Orb,OriginalGlassPill as Pill} from './original-glass';
import {DetailControlCompanion} from './detail-control-companion';
import {SemanticIcon,semanticIconColors,type SemanticIconName} from './semantic-icon';
import {SourceLaneIcon} from './source-lane-icon';
import {useSceneFocus} from './scene-focus';
import {productRecords,productSources,productModes,productLocations} from '../data/product-story';
import {anatomyChapters,anatomyNodes} from '../data/product-anatomy';
import {RecordDetail,SingleToolDetail} from './home-subject-detail';
import {ToolBrowser} from './tool-browser';
import {ToolIdentity,ToolLogoRow,toolName} from './tool-identity';
import {StudioViewDetail,studioViewIcons} from './studio-view-detail';
import catalogue from '../data/tool-browser.json';
const profiles:Record<string,string[]>={local_code:['code'],github_code:['code'],docs:['document'],ppt:['presentation'],data_excel:['spreadsheet'],data:['data'],tableau:['tableau'],power_bi:['power_bi'],pdf_ocr:['pdf_ocr'],images_ocr:['images_ocr'],research:['research'],artifacts:['artifacts'],custom:['custom']};

export function ProductAnatomyDetails({selected,onClose,onNavigate}:{selected:string|null;onClose:()=>void;onNavigate:(id:string)=>void}){
 const {state}=useSceneFocus();useEffect(()=>{if(!selected)return;const panel=document.querySelector('#product-detail');const scroll=panel?.querySelector('.flowPopupScroll');if(scroll)scroll.scrollTop=0;(panel as HTMLElement|null)?.focus({preventScroll:true})},[selected]);
 const[kind,...rest]=selected?.split(':')??[],arg=rest.join(':');const record=productRecords.find(r=>r.id===arg),material=productSources.find(r=>r[0]===arg),location=productLocations.find(r=>r.id===arg),mode=productModes[Number(arg)],chapter=anatomyChapters[Number(arg)];
 const identity=state.identity;const node=kind==='material'?anatomyNodes(2).find(n=>n.id===selected):undefined;
 const defaultName=kind==='record'?record?.name:kind==='material'?material?.[1]:kind==='mode'?mode?.name:kind==='location'?location?.title:kind==='studio'?arg:kind==='tool'?toolName(arg):kind==='tools'?'Tools and dependencies':'Evidence Lane';
 const icon=(identity?.icon&&identity.icon in semanticIconColors?identity.icon:kind==='record'?record?.icon:kind==='studio'?studioViewIcons[arg]:kind==='location'?location?.icon:kind==='mode'?(['sources','plan','work'] as const)[Number(arg)]:node?.icon??'project') as SemanticIconName;
 const color=identity?.color??record?.color??node?.color??semanticIconColors[icon??'project'];const title=identity?.title??defaultName;
 const description=kind==='record'?record?.purpose:kind==='material'?material?.[3]:kind==='mode'?mode?.effect:kind==='location'?location?.description:kind==='studio'?'The information presented in this read-only Studio view.':kind==='anatomy'?chapter?.body:kind==='tool'?'The tool’s delivery role and declared operations.':'Inspect the current source catalogue and operation relationships.';
 return <OriginalGlassPopup open={!!selected} onClose={onClose} panelId="product-detail" labelledBy="product-detail-title" size="wide" companion={<DetailControlCompanion onSelect={onNavigate}/>}>{selected&&<><header className="flow-detail-heading" style={{'--item-color':color} as CSSProperties}>{kind==='tool'?<ToolIdentity id={arg} size={72}/>:<Orb size={72} color={color} decorative>{identity?.image?<img src={identity.image} alt=""/>:kind==='anatomy'?<img src="/evidence-lane-icon.png" alt=""/>:node?.image?<img src={node.image} alt=""/>:node?.lane?<SourceLaneIcon lane={node.lane} decorative/>:<SemanticIcon name={icon??'project'}/>}</Orb>}<div><p className="flow-kicker">EVIDENCE LANE / {kind==='anatomy'?'PRODUCT':kind.toUpperCase()}</p><h2 id="product-detail-title">{title}</h2><p>{description}</p></div></header><div className="atlas-detail-content" key={selected}>
 {kind==='record'&&<RecordDetail id={arg}/>}
 {kind==='material'&&material&&<MaterialDetail id={arg} onNavigate={onNavigate}/>}
 {kind==='mode'&&mode&&<section className="subject-detail"><blockquote>{mode.prompt}</blockquote><dl className="studio-view-fields"><div><dt>Effect on the Plan</dt><dd>{mode.plan}</dd></div><div><dt>Project effect</dt><dd>{mode.effect}</dd></div></dl><div className="subject-mini-flow"><span>Your intention</span><span>{mode.name==='Ask'?'Attributed read':mode.name==='Steer'?'Safe Plan change':'Scoped operation'}</span><span>{mode.name==='Ask'?'Referenced answer':mode.name==='Steer'?'Current revision':'Recorded result'}</span></div><p>{mode.record}</p></section>}
 {kind==='location'&&location&&<section className="subject-detail"><ul className="subject-facts">{location.items.map(item=><li key={item}>{item}</li>)}</ul><p>{location.boundary}</p>{arg==='runtime'&&<Pill data-detail-name="Tools and dependencies" leading={<Orb color="#efd088" decorative><SemanticIcon name="tools"/></Orb>} onClick={()=>onNavigate('tools')}>Inspect the shared tool catalogue</Pill>}</section>}
 {kind==='studio'&&<StudioViewDetail view={arg}/>}
 {kind==='tool'&&<SingleToolDetail id={arg} onNavigate={onNavigate}/>}
 {kind==='tools'&&<ToolBrowser/>}
 {kind==='anatomy'&&chapter&&<section className="subject-detail"><h3>{chapter.name}</h3>{Number(arg)===4?<div className="product-location-detail">{productLocations.map(place=><article key={place.id}><h4>{place.title}</h4><p>{place.description}</p><ul>{place.items.map(item=><li key={item}>{item}</li>)}</ul><p className="atlas-detail-note">{place.boundary}</p></article>)}</div>:<><p>{Number(arg)<2?'The centre coordinates references between these records. Each record retains its own database, files and responsibility.':Number(arg)===2?'A selected file, its source snapshot and the evidence used by a task are separately inspectable.':Number(arg)===3?'The request determines whether the project is read, safely steered or changed through its current work.':'Studio observes these views. Humans navigate and inspect; project changes go through Codex.'}</p><div className="subject-records">{anatomyNodes(Number(arg)).map(n=><Pill key={n.id} data-detail-name={n.name} leading={<Orb color={n.color} decorative>{n.image?<img src={n.image} alt=""/>:n.lane?<SourceLaneIcon lane={n.lane} decorative/>:<SemanticIcon name={n.icon}/>}</Orb>} onClick={()=>onNavigate(n.id)}>{n.name}</Pill>)}</div></>}</section>}
 </div></>}</OriginalGlassPopup>;
}
function MaterialDetail({id,onNavigate}:{id:string;onNavigate:(id:string)=>void}){const actions=catalogue.operations.filter(action=>(profiles[id]??[]).includes(action.profile));const tools=Array.from(new Set(actions.flatMap(a=>a.tools)));return <section className="subject-detail"><div className="subject-mini-flow"><span>Selected material</span><span>Source identity & snapshot</span><span>Attributed project evidence</span></div><p>Selection, preparation, reading and changing material are distinct operations. Each uses the declared source scope, route and checks.</p><h3>Tools declared by this source family</h3><ToolLogoRow tools={tools} onSelect={tool=>onNavigate('tool:'+tool)}/><h3>Available operation contracts</h3><div className="subject-action-list">{actions.map(action=><article key={action.id}><h4>{action.id.replaceAll('_',' ')}</h4><p>{action.description}</p><small>{action.mutates?'Changes state within its declared scope':'Reads without changing project state'}</small></article>)}</div><p className="catalog-note">This is source-contract information. Supported fidelity, source grants and tool readiness are checked for the chosen operation; the website has not run it.</p></section>}
