import type * as Three from 'three';
export function createProductSceneArt(T:typeof Three,root:Three.Group){
 const geometries:Three.BufferGeometry[]=[],materials:Three.Material[]=[];
 const g=<G extends Three.BufferGeometry>(v:G)=>{geometries.push(v);return v},m=<M extends Three.Material>(v:M)=>{materials.push(v);return v};
 const glow=m(new T.ShaderMaterial({transparent:true,depthWrite:false,vertexColors:true,toneMapped:false,uniforms:{},vertexShader:'varying vec3 tint;void main(){tint=color;vec4 p=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*p;gl_PointSize=clamp(80./-p.z,2.,8.);}',fragmentShader:'varying vec3 tint;void main(){float r=length(gl_PointCoord-.5)*2.;if(r>1.)discard;gl_FragColor=vec4(tint,exp(-r*r*4.)*.88);\n#include <colorspace_fragment>\n}'}));
 const packetGeometry=g(new T.BufferGeometry()),packetPositions=new Float32Array(90*3),packetColours=new Float32Array(90*3);packetGeometry.setAttribute('position',new T.BufferAttribute(packetPositions,3));packetGeometry.setAttribute('color',new T.BufferAttribute(packetColours,3));const packets=new T.Points(packetGeometry,glow);root.add(packets);
 const files=new T.Group(),atom=new T.Group();root.add(files,atom);
 const paper=g(new T.BoxGeometry(.48,.65,.035)),rule=g(new T.BoxGeometry(.31,.018,.012));const paperMat=m(new T.MeshPhysicalMaterial({color:0xbbd8e8,roughness:.18,metalness:.1,clearcoat:1,transparent:true,opacity:.87})),ink=m(new T.MeshBasicMaterial({color:0x457c9f}));
 for(let i=0;i<5;i++){const sheet=new T.Group();sheet.add(new T.Mesh(paper,paperMat));for(let j=0;j<4;j++){const line=new T.Mesh(rule,ink);line.position.set(-.02,.16-j*.10,.025);sheet.add(line)}sheet.position.set(i%2===0?-.31:.31,(2-i)*.35,(i%2)*.12);sheet.rotation.set(.03*(i-2),-.22,.035*(i-2));files.add(sheet)}
 const ringGeometry=g(new T.TorusGeometry(.93,.009,6,96)),rings:Three.Group[]=[],beads:Three.Mesh[]=[];const ringMat=m(new T.MeshBasicMaterial({color:0x7ed9e8,transparent:true,opacity:.58})),beadGeo=g(new T.SphereGeometry(.055,12,8)),beadMat=m(new T.MeshBasicMaterial({color:0xe8fcff}));
 for(let i=0;i<3;i++){const orbit=new T.Group();orbit.rotation.set(Math.PI/3+i*.3,i*Math.PI/3,.3);orbit.add(new T.Mesh(ringGeometry,ringMat));const bead=new T.Mesh(beadGeo,beadMat);orbit.add(bead);rings.push(orbit);beads.push(bead);atom.add(orbit)}
 const nucleus=new T.Mesh(g(new T.SphereGeometry(.22,24,16)),m(new T.MeshPhysicalMaterial({color:0x74dce8,emissive:0x168391,emissiveIntensity:.5,roughness:.1,metalness:.1,clearcoat:1})));atom.add(nucleus);
 const dustGeo=g(new T.BufferGeometry()),dustPos=[],dustColors=[];for(let i=0;i<95;i++){const a=i*2.399963,y=1-2*(i+.5)/95,r=Math.sqrt(1-y*y)*(1.08+(i%5)*.025);dustPos.push(Math.cos(a)*r,y*1.17,Math.sin(a)*r);const c=new T.Color(i%6===0?0xedd19d:0x7cc3d7);dustColors.push(c.r,c.g,c.b)}dustGeo.setAttribute('position',new T.Float32BufferAttribute(dustPos,3));dustGeo.setAttribute('color',new T.Float32BufferAttribute(dustColors,3));atom.add(new T.Points(dustGeo,glow));
 return {
  attachCube(cube:Three.Group){const box=g(new T.BoxGeometry(2.02,2.02,2.02));const edges=new T.LineSegments(g(new T.EdgesGeometry(box)),m(new T.LineBasicMaterial({color:0xc9f5ff,transparent:true,opacity:.72,toneMapped:false})));cube.add(edges);const positions=[];for(let i=0;i<18;i++)positions.push(Math.sin(i*2.17)*.72,Math.cos(i*1.73)*.72,Math.sin(i*3.13)*.72);const dust=g(new T.BufferGeometry());dust.setAttribute('position',new T.Float32BufferAttribute(positions,3));cube.add(new T.Points(dust,m(new T.PointsMaterial({color:0x99e9ff,size:.024,transparent:true,opacity:.65,depthWrite:false,toneMapped:false}))))},
  packet(index:number,position:Three.Vector3,color:Three.Color){packetPositions.set([position.x,position.y,position.z],index*3);packetColours.set([color.r,color.g,color.b],index*3)},
  flush(count:number){packetGeometry.setDrawRange(0,count);packetGeometry.attributes.position.needsUpdate=true;packetGeometry.attributes.color.needsUpdate=true},
  update(time:number,chapter:number,positions:Map<string,Three.Vector3>,weights:Map<string,number>){files.visible=(weights.get('location:files')??0)>.02;atom.visible=(weights.get('location:runtime')??0)>.02;files.scale.setScalar(weights.get('location:files')??0);atom.scale.setScalar(weights.get('location:runtime')??0);const f=positions.get('location:files'),a=positions.get('location:runtime');if(f)files.position.copy(f);if(a)atom.position.copy(a);files.rotation.y=-.1+Math.sin(time*.28)*.09;atom.rotation.y=time*.08;beads.forEach((bead,i)=>bead.position.set(Math.cos(time*.7+i*2)*.93,Math.sin(time*.7+i*2)*.93,0));nucleus.scale.setScalar(1+Math.sin(time*.6)*.035)},
  dispose(){root.remove(files,atom,packets);geometries.forEach(x=>x.dispose());materials.forEach(x=>x.dispose())}
 };
}
