'use client';
import Link from 'next/link';import{GlassPopup,GlassOrb,GlassFacts}from'./glass';import{layers,sources,stages}from'../data/project-story';
const layerFacts=[
 {steps:['Choose the exact files, repository or URLs that belong to the project.','Register their ordered identity and prepare bounded source tasks.','Process the selected sources through their owning tools and inspect coverage.'],output:'Source records, snapshots, parser observations and evidence references.',evidence:'Recorded input hashes, selected source identities and extraction coverage.',limit:'Registration does not mean indexing is complete. Source freshness must be checked separately.',tools:[['git','Git','Selected code and history'],['python','Python','Registered parsers'],['database','SQLite','Separate source records'],['media','Document tools','Format-specific extraction']]},
 {steps:['Read the complete current Plan at one exact revision.','Define the outcome, task order, scope, dependencies and acceptance checks.','Apply a semantic change only at the affected work’s safe checkpoint.'],output:'One current Plan revision and an eligible next task.',evidence:'Task contracts, revision identity, change history and linked result references.',limit:'Completed history stays intact. A question does not rewrite the Plan.',tools:[['package','Plan registry','Current ordered work'],['database','SQLite','Separate Plan database'],['pulse','Validation','Project-selected checks'],['git','Revision binding','Reject stale completion']]},
 {steps:['Resolve the exact next eligible task and the current project permissions.','Check tool readiness, source identity and the operation’s bounded input.','Admit the job, observe the required worker tools and inspect its result.'],output:'A bounded job, addressed output and recorded checks.',evidence:'Job identity, selected route, output references and verification observations.',limit:'Queued is not completed. A failed or uncertain effect is not blindly retried.',tools:[['terminal','Worker processes','Owned operating-system tools'],['python','Engine','Task and scope admission'],['pulse','Checks','Operation-specific verification'],['package','Result store','Addressed output artifacts']]},
 {steps:['Select the recorded task result or source snapshot you want to inspect.','Follow the original owner’s bounded read with its exact reference.','Read the output, checks and stated limitations together.'],output:'Inspectable results with their supporting references.',evidence:'Source, task, receipt and output identities remain attributable.',limit:'A historical verification receipt does not recheck today’s source bytes.',tools:[['database','Source records','Identity and origin'],['git','Receipts','Recorded effects and checks'],['media','Artifacts','Natural result files'],['node','Evidence links','Attributed relationships']]},
 {steps:['Search project-local references within explicit bounds.','Follow the selected locators to the owning evidence rather than copying every store.','Checkpoint relevant context and verify compatibility when returning.'],output:'A bounded selection of relevant project references and compatible saved context.',evidence:'Locator identities, source ownership, checkpoint references and verified-work lessons.',limit:'Host recall and project memory stay separate. Memory is not proof of current native attachment.',tools:[['database','SQLite FTS','Bounded project search'],['node','Evidence locators','Original owners retained'],['package','Checkpoints','Exact context references'],['pulse','Learning','Verified-work provenance']]},
 {steps:['Inspect the project’s current registered connector and exact backend binding.','Configure only the authorized actions, targets, paths and expiry.','Check measured readiness for the selected operation before using it.'],output:'A versioned, scoped connector record and separate readiness observations.',evidence:'Grant version, backend identity, resource scope and expiry.',limit:'A saved connector cannot create an arbitrary adapter or imply service availability.',tools:[['python','Registered adapters','Known backend implementations'],['git','Scoped grants','Exact project and targets'],['pulse','Readiness','Measured operation eligibility'],['terminal','Client route','Authenticated engine access']]}
];
const sourceFacts=[
 {steps:['Select the exact repository and bounded files.','Register file hashes; keep working-copy bytes separate from Git snapshots.','Prepare and execute the required indexing task, then query its recorded coverage.'],tools:[['git','Git','Refs, commits and selected history'],['python','Structural parsers','Supported language coverage'],['database','SQLite search','Bounded code evidence'],['terminal','Project checks','Only the checks selected for this project']],limit:'A parser may not fully understand every language. Indexing is not proof that the project builds.'},
 {steps:['Select the Word documents or PowerPoint presentations.','Inspect content and structure with the registered format-specific route.','Run requested changes, render the output and check actual fidelity.'],tools:[['media','OpenXML','Document and slide structure'],['python','Format adapters','Bounded reads and edits'],['terminal','Renderers','Operation-selected visual output'],['package','Artifact output','Source-linked result files']],limit:'Complex layouts, fonts, embedded objects and animation require representative output checks.'},
 {steps:['Select the workbook, dataset or supported BI source.','Inspect structure and stored values; select the appropriate query or calculation route.','Run scoped transformation or recalculation and inspect resulting artifacts.'],tools:[['database','Data adapters','DuckDB, pandas, Polars or Arrow'],['media','Excel tools','Workbook and calculation routes'],['python','BI adapters','Supported Tableau and Power BI formats'],['pulse','Validation','Operation-specific output checks']],limit:'Stored spreadsheet values differ from recalculated values. Local BI files do not imply service access.'},
 {steps:['Select the permitted web, PDF or image sources and the capture scope.','Extract content with the relevant parser, renderer or OCR route.','Retain origin, extraction coverage and citation references with the result.'],tools:[['python','Web capture','Authorized source extraction'],['media','PDF tools','Page and text inspection'],['terminal','OCR tools','Selected languages and models'],['database','Research records','Attributed source snapshots']],limit:'OCR accuracy depends on source quality. Network access and site restrictions can limit capture.'}
];
export function ProjectDetail({selection,onClose}:{selection:{type:'layer'|'source'|'stage';index:number;title?:string}|null;onClose:()=>void}){
 const i=selection?.index??0,type=selection?.type??'layer';const layer=layerFacts[i%6],source=sourceFacts[i%4];const title=selection?.title??(type==='layer'?layers[i][0]:type==='source'?sources[i][0]:stages[i][0]);const description=type==='layer'?layers[i][2]:type==='source'?sources[i][2]:stages[i][2];const steps=type==='source'?source.steps:type==='layer'?layer.steps:[stages[i][2], 'Inspect the current project and exact owning workflow before proceeding.', 'Keep the observed result, remaining limits and next eligible action explicit.'];const tools=type==='source'?source.tools:layer.tools;const output=type==='layer'?layer.output:type==='source'?sources[i][3]:stages[i][4];const evidence=type==='layer'?layer.evidence:'Selected source identity, current task reference and owning operation observations.';const limit=type==='layer'?layer.limit:type==='source'?source.limit:'This illustration is not a live execution. The current Plan and operation contract determine what can run.';
 return <GlassPopup open={!!selection} onClose={onClose} title={title} kicker={type==='layer'?'EXPLORE YOUR PROJECT':type==='source'?'SOURCE INTAKE & TOOL ROLES':'THE PROJECT WORKFLOW'} description={description} icon={type==='source'?sources[i][4]:['database','package','terminal','git','node','python'][i%6]} color={layers[i%6][3]}><div className="glass-popup-grid"><section className="glass-panel"><h3>How it works</h3><ol>{steps.map(s=><li key={s}>{s}</li>)}</ol></section><section className="glass-panel"><h3>What you can inspect</h3><GlassFacts items={[["Produces",output],["Evidence",evidence],["Boundary",limit]]}/></section></div><section className="glass-panel popup-tools"><p className="eyebrow">TOOLS & RESPONSIBILITIES</p><div className="glass-tool-grid">{tools.map(([icon,name,role])=><div key={name}><GlassOrb icon={icon} color={layers[i%6][3]} size={40}/><span><strong>{name}</strong><small>{role}</small></span></div>)}</div><p className="quiet">The owning operation selects its required tools. This website does not measure your installed runtime.</p></section><div className="glass-sequence">{['Select the scope','Check the context','Follow the owning action','Inspect the result'].map((s,n)=><div key={s}><span>0{n+1}</span>{s}</div>)}</div><Link className="button" href={type==='source'?'/integrations':'/workflows'} onClick={onClose}>Read the relevant workflow →</Link></GlassPopup>
}
