'use client';
import {useEffect,useRef,useState} from 'react';
import type * as THREE from 'three';
export const universeTools=[{id:'git',label:'Git',file:'git.svg',color:0xf05a40},{id:'github',label:'GitHub',file:'github.png',color:0xbca9fa},{id:'python',label:'Python',file:'python.svg',color:0xffd260},{id:'nodejs',label:'Node.js',file:'nodejs.svg',color:0x8cdf72},{id:'word',label:'Word',file:'word.svg',color:0x70b5ff},{id:'excel',label:'Excel',file:'excel.svg',color:0x61d9a0},{id:'powerpoint',label:'PowerPoint',file:'powerpoint.svg',color:0xff9772}];
type Props={phase:number;paused:boolean;hovered:string|null;onTool:(id:string)=>void;onProject:()=>void;onUnavailable:()=>void};
export function ProjectUniverseScene(props:Props){const mount=useRef<HTMLDivElement>(null),live=useRef(props);const[ready,setReady]=useState(false);const[tooltip,setTooltip]=useState('');useEffect(()=>{live.current=props},[props]);
 useEffect(()=>{const element=mount.current;if(!element)return;const host=element;let gone=false;let cleanup=()=>{};
 async function start(){try{
  const T=await import('three');const[{GLTFLoader},{RoomEnvironment}]=await Promise.all([import('three/examples/jsm/loaders/GLTFLoader.js'),import('three/examples/jsm/environments/RoomEnvironment.js')]);if(gone)return;
  const renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.4));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;host.appendChild(renderer.domElement);
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(42,1,.1,150);camera.position.set(0,4,13);camera.lookAt(0,0,0);const root=new T.Group();scene.add(root);
  const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;scene.environmentIntensity=.72;room.dispose();pmrem.dispose();
  scene.add(new T.HemisphereLight(0xb7e3ff,0x061225,.75));const key=new T.DirectionalLight(0x8fe3ff,3.8);key.position.set(-3,6,5);scene.add(key);const rim=new T.DirectionalLight(0xd6a5ff,3);rim.position.set(5,2,-3);scene.add(rim);
  const geometries:THREE.BufferGeometry[]=[],materials:THREE.Material[]=[],textures:THREE.Texture[]=[];let core:THREE.Group|undefined;const nodes:THREE.Group[]=[],hitMeshes:THREE.Mesh[]=[],faces:THREE.Mesh[]=[],connections:THREE.Line[]=[],pulses:THREE.Mesh[]=[];
  const geo=<G extends THREE.BufferGeometry>(g:G)=>{geometries.push(g);return g};const mat=<M extends THREE.Material>(m:M)=>{materials.push(m);return m};
  const skyMat=mat(new T.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:{time:{value:0},phase:{value:0},aspect:{value:1},pointer:{value:new T.Vector2()}},vertexShader:'varying vec2 uvp;void main(){uvp=uv;gl_Position=vec4(position.xy,.999,1.);}',fragmentShader:`varying vec2 uvp;uniform float time;uniform float phase;uniform float aspect;uniform vec2 pointer;float hash(vec2 p){return fract(sin(dot(p,vec2(37.71,119.37)))*43758.3);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}float field(vec2 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=noise(p)*a;p=mat2(.83,-.56,.56,.83)*p*2.07+3.7;a*=.5;}return v;}void main(){vec2 p=(uvp-.5)*vec2(aspect,1.)*2.;p+=pointer*.09+vec2(phase*.10,phase*-.04);vec2 q=p*1.8+vec2(time*.006,0);float bend=.35*sin(p.x*1.3+phase*.25);float band=exp(-pow(p.y-bend,2.)*3.5);float f=field(q+field(q*1.7));float veins=field(q*4.8+10.);vec3 c=vec3(.004,.010,.021);c+=vec3(.075,.18,.27)*pow(f,2.1)*band;c+=vec3(.12,.043,.20)*pow(field(q*1.25+22.),3.)*(1.-band*.25);c+=vec3(.16,.075,.018)*pow(veins,5.)*band*.6;c*=1.-.40*pow(field(q*7.),2.)*band;gl_FragColor=vec4(c,1.);}`}));const sky=new T.Mesh(geo(new T.PlaneGeometry(2,2)),skyMat);sky.renderOrder=-1000;scene.add(sky);
  let seed=913;const random=()=>{seed=seed*16807%2147483647;return(seed-1)/2147483646};const starCount=innerWidth<700?2300:4800;const positions=new Float32Array(starCount*3),sizes=new Float32Array(starCount),colors=new Float32Array(starCount*3);
  for(let i=0;i<starCount;i++){positions.set([(random()-.5)*90,(random()-.5)*55,-12-random()*65],i*3);sizes[i]=random()>.965?4+random()*4:.7+random()*2.3;const c=new T.Color(i%9===0?0xffbf77:i%5===0?0xb9a0ed:0x88c5ed);colors.set([c.r,c.g,c.b],i*3)}
  const starGeometry=geo(new T.BufferGeometry());starGeometry.setAttribute('position',new T.BufferAttribute(positions,3));starGeometry.setAttribute('size',new T.BufferAttribute(sizes,1));starGeometry.setAttribute('color',new T.BufferAttribute(colors,3));const starMaterial=mat(new T.ShaderMaterial({transparent:true,depthWrite:false,vertexColors:true,blending:T.AdditiveBlending,uniforms:{time:{value:0},ratio:{value:Math.min(devicePixelRatio,1.4)}},vertexShader:'attribute float size;varying vec3 tint;varying float id;uniform float ratio;void main(){tint=color;id=position.x*3.+position.y;vec4 p=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*p;gl_PointSize=clamp(size*ratio*(24./-p.z),.65,10.);}',fragmentShader:'varying vec3 tint;varying float id;uniform float time;void main(){float d=length(gl_PointCoord-.5)*2.;if(d>1.)discard;float a=exp(-d*d*7.)*(.70+.22*sin(id+time*.25));gl_FragColor=vec4(tint,a);}'}));const stars=new T.Points(starGeometry,starMaterial);scene.add(stars);
  const nodeGeometry=geo(new T.SphereGeometry(.37,36,24));const faceGeometry=geo(new T.PlaneGeometry(.45,.45));const pulseGeometry=geo(new T.SphereGeometry(.028,10,8));
  for(let i=0;i<universeTools.length;i++){const tool=universeTools[i],node=new T.Group();node.userData.toolId=tool.id;root.add(node);nodes.push(node);const shellMat=mat(new T.MeshPhysicalMaterial({color:tool.color,metalness:.18,roughness:.08,transparent:true,opacity:.24,clearcoat:1,depthWrite:false,emissive:tool.color,emissiveIntensity:.14}));const shell=new T.Mesh(nodeGeometry,shellMat);shell.userData.toolId=tool.id;shell.userData.label=tool.label;shell.renderOrder=4;node.add(shell);hitMeshes.push(shell);const edgeMat=mat(new T.MeshBasicMaterial({color:tool.color,transparent:true,opacity:.20,wireframe:true,depthWrite:false}));const edge=new T.Mesh(geo(new T.IcosahedronGeometry(.381,2)),edgeMat);node.add(edge);const face=new T.Mesh(faceGeometry,mat(new T.MeshBasicMaterial({transparent:true,side:T.DoubleSide,depthWrite:false})));face.renderOrder=3;node.add(face);faces.push(face);const lineGeo=geo(new T.BufferGeometry());lineGeo.setAttribute('position',new T.BufferAttribute(new Float32Array(40*3),3));const line=new T.Line(lineGeo,mat(new T.LineBasicMaterial({color:tool.color,transparent:true,opacity:.36})));root.add(line);connections.push(line);const pulse=new T.Mesh(pulseGeometry,mat(new T.MeshBasicMaterial({color:tool.color})));root.add(pulse);pulses.push(pulse);}
  let frame=0,last=0,time=0,currentPhase=0,mouseX=0,mouseY=0,drag=false,moved=false,dx=0,dy=0,manualYaw=0,manualPitch=0,visible=true,frameCount=0;const ray=new T.Raycaster(),pointer=new T.Vector2(),quaternion=new T.Quaternion();
  const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();skyMat.uniforms.aspect.value=camera.aspect};resize();const ro=new ResizeObserver(resize);ro.observe(host);const io=new IntersectionObserver(es=>{visible=es[0].isIntersecting});io.observe(host);
  const windowPointer=(e:PointerEvent)=>{mouseX=e.clientX/innerWidth-.5;mouseY=e.clientY/innerHeight-.5};window.addEventListener('pointermove',windowPointer,{passive:true});
  const down=(e:PointerEvent)=>{drag=e.pointerType==='mouse';moved=false;dx=e.clientX;dy=e.clientY;if(drag)host.setPointerCapture(e.pointerId)};const move=(e:PointerEvent)=>{if(drag){const a=e.clientX-dx,b=e.clientY-dy;moved=moved||Math.abs(a)+Math.abs(b)>3;manualYaw+=a*.002;manualPitch=Math.max(-.25,Math.min(.25,manualPitch+b*.0015));dx=e.clientX;dy=e.clientY}const r=host.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(hitMeshes,false)[0];setTooltip(hit?String(hit.object.userData.label):'');host.style.cursor=hit?'pointer':'grab'};const up=()=>{drag=false;if(moved)return;ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(hitMeshes,false)[0];if(hit)live.current.onTool(String(hit.object.userData.toolId));else live.current.onProject()};const cancel=()=>{drag=false;moved=true};const keyboard=(e:KeyboardEvent)=>{if(e.key==='Enter'){e.preventDefault();live.current.onProject()}if(e.key.startsWith('Arrow')){e.preventDefault();manualYaw+=e.key==='ArrowLeft'?-.15:e.key==='ArrowRight'?.15:0;manualPitch+=e.key==='ArrowUp'?-.08:e.key==='ArrowDown'?.08:0}};
  host.addEventListener('pointerdown',down);host.addEventListener('pointermove',move);host.addEventListener('pointerup',up);host.addEventListener('pointercancel',cancel);host.addEventListener('keydown',keyboard);const lost=(e:Event)=>{e.preventDefault();live.current.onUnavailable()};renderer.domElement.addEventListener('webglcontextlost',lost);
  cleanup=()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();window.removeEventListener('pointermove',windowPointer);host.removeEventListener('pointerdown',down);host.removeEventListener('pointermove',move);host.removeEventListener('pointerup',up);host.removeEventListener('pointercancel',cancel);host.removeEventListener('keydown',keyboard);renderer.domElement.removeEventListener('webglcontextlost',lost);core?.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());environment.dispose();renderer.dispose();renderer.domElement.remove()};
  const[model,icons]=await Promise.all([new GLTFLoader().loadAsync('/home-current/project-nexus.glb'),Promise.all(universeTools.map(t=>new T.TextureLoader().loadAsync(`/brands/${t.file}`)))]);if(gone){icons.forEach(t=>t.dispose());model.scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});return}core=model.scene;root.add(core);icons.forEach((t,i)=>{t.colorSpace=T.SRGBColorSpace;textures.push(t);(faces[i].material as THREE.MeshBasicMaterial).map=t;(faces[i].material as THREE.MeshBasicMaterial).needsUpdate=true});host.dataset.sceneReady='true';host.dataset.toolIds=universeTools.map(t=>t.id).join(',');setReady(true);
  const smooth=(x:number)=>{const t=Math.max(0,Math.min(1,x));return t*t*(3-2*t)};
  function tick(now:number){if(gone)return;frame=requestAnimationFrame(tick);const dt=Math.min(.05,(now-last)/1000);last=now;if(!visible||document.hidden||++frameCount%2)return;const state=live.current;const still=state.paused||matchMedia('(prefers-reduced-motion: reduce)').matches;if(!still)time+=dt*2;currentPhase+=(state.phase-currentPhase)*(still?1:.09);const chapter=Math.min(5,Math.floor(currentPhase)),fraction=currentPhase-chapter;const xs=[4.0,4.3,-4.4,4.3,-4.4,-4.4];const next=Math.min(5,chapter+1);const blend=smooth((fraction-.65)/.35);const mobile=camera.aspect<.9;const targetX=mobile?0:T.MathUtils.lerp(xs[chapter],xs[next],blend);root.position.x+=(targetX-root.position.x)*.065;root.position.y=mobile?1.6:chapter===0?-1.25:0;root.scale.setScalar(mobile?.72:chapter===0?1.15:.93);root.rotation.y=manualYaw+Math.sin(time*.035)*.06+currentPhase*.12;root.rotation.x=manualPitch;camera.position.set(mouseX*.6,3.5+mouseY*.35-Math.sin(currentPhase*.7)*.6,mobile?15:13.5-Math.sin(fraction*Math.PI)*.6);camera.lookAt(0,0,0);skyMat.uniforms.time.value=time;skyMat.uniforms.phase.value=currentPhase;skyMat.uniforms.pointer.value.set(mouseX,mouseY);starMaterial.uniforms.time.value=time;stars.rotation.y=mouseX*.025+currentPhase*.013;stars.rotation.x=mouseY*.017;stars.position.z=currentPhase*.55;const path=chapter===2||chapter===3||chapter===4;
   nodes.forEach((node,i)=>{const angle=i*Math.PI*2/7+time*.045;const orbit=new T.Vector3(Math.cos(angle)*3.75,.6+Math.sin(angle*2)*.55,Math.sin(angle)*2.2);const lane=new T.Vector3((i-3)*1.02,.75+Math.sin(i*.8)*.2,1.0);node.position.copy(orbit.lerp(lane,path?.85:0));const selected=state.hovered===universeTools[i].id;node.scale.setScalar(selected?1.22:1);node.getWorldQuaternion(quaternion);faces[i].quaternion.copy(quaternion.invert()).multiply(camera.quaternion);const a=connections[i].geometry.attributes.position as THREE.BufferAttribute;for(let j=0;j<40;j++){const t=j/39;a.setXYZ(j,node.position.x*t,node.position.y*t+Math.sin(t*Math.PI)*.65,node.position.z*t)}a.needsUpdate=true;(connections[i].material as THREE.LineBasicMaterial).opacity=selected?.9:.29;const travel=(time*.18+i*.14)%1;pulses[i].position.set(node.position.x*travel,node.position.y*travel+Math.sin(travel*Math.PI)*.65,node.position.z*travel);pulses[i].scale.setScalar(selected?1.8:1)});if(core)core.rotation.y=time*.075;renderer.render(scene,camera);
  }frame=requestAnimationFrame(tick);
 }catch{cleanup();live.current.onUnavailable()}}
 void start();return()=>{gone=true;cleanup()};
 },[]);
 return <div className="project-universe-render"><img src="/home-current/project-nexus.png" alt="" className={ready?'universe-poster hidden':'universe-poster'}/><div ref={mount} className="universe-canvas" tabIndex={0} role="group" aria-label="Interactive project and tool constellation. Drag or use arrow keys to orbit; select a tool or press Enter to inspect."/>{tooltip&&<span className="universe-tooltip">{tooltip}</span>}</div>;
}
