'use client';
import Link from 'next/link';import backend from '../data/backend.json';import {NavigationIcon,type NavigationIconName} from './navigation-icon';import{OriginalGlassIconOrb}from'./original-glass';import{SemanticIcon,semanticIconColors}from'./semantic-icon';import {EvidenceBrand} from './evidence-brand';import type{CSSProperties}from'react';import {usePathname} from 'next/navigation';import {useState,useRef,useEffect} from 'react';
const navIcons:NavigationIconName[]=['home','product','workflows','studio','how','integrations','docs','download'];
const navColors=['#79def3','#aacfff','#84e7b7','#91c9ff','#f2c779','#d8a7fa','#a9c3fc','#efce76'];
export const nav=[['Home','/'],['Product','/product'],['Workflows','/workflows'],['Studio','/studio'],['How it works','/how-it-works'],['Integrations','/integrations'],['Docs','/docs'],['Download','/download']];
const groups=[['Explore',['Product','/product'],['Workflows','/workflows'],['How it works','/how-it-works']],['Use Evidence Lane',['Download','/download'],['Windows Studio','/studio'],['Integrations','/integrations']],['User guides',['Quickstart','/docs/quickstart'],['Install','/docs/install'],['Project setup','/docs/project-setup'],['Workflow guide','/docs/workflow-guide'],['Troubleshooting','/docs/troubleshooting']],['Repository',['Overview','/docs/readme'],['SDK & MCP','/docs/sdk-mcp'],['Releases','/docs/releases'],['Source on GitHub','https://github.com/rathee000001/evidence_lane_plugin']],['Policies',['Privacy','/privacy'],['Terms','/terms'],['MIT License','/license'],['Copyright','/copyright'],['Third-party notices','/third-party'],['Security','/security'],['Local data','/local-data']],['Contributors',['Contributors','/contributors']],['Praveen Rathee',['GitHub profile','https://github.com/rathee000001']]] as const;
export function Header(){const header=useRef<HTMLElement>(null);useEffect(()=>{const element=header.current;if(!element)return;const update=()=>document.documentElement.style.setProperty('--site-header-height',element.getBoundingClientRect().height+'px');update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect()},[]);const pathname=usePathname();const[open,setOpen]=useState(false);return <header ref={header} className="site-header"><a className="skip-link" href="#main">Skip to content</a><div className="header-inner shell"><div className="original-brand"><EvidenceBrand/></div><button className="menu-toggle" aria-expanded={open} aria-controls="primary-nav" onClick={()=>setOpen(!open)}>{open?'Close ×':'Menu ☰'}</button><nav id="primary-nav" className={open?'nav open':'nav'} aria-label="Main navigation">{nav.map(([label,href],i)=><Link key={href} href={href} onClick={()=>setOpen(false)} className={`${pathname===href?'active ':''}${href==='/download'?'download-pill':''}`} style={{'--item-color':navColors[i]} as CSSProperties} aria-current={pathname===href?'page':undefined}><OriginalGlassIconOrb size={36} color={navColors[i]}><NavigationIcon name={navIcons[i]}/></OriginalGlassIconOrb><span>{label}</span>{href==='/download'?' ↗':''}</Link>)}</nav></div></header>}
export function ProjectStatusNotice(){return <aside className="project-status-notice" aria-label="Project status"><div className="shell"><strong>Experimental project — development is on hold.</strong><span>Evidence Lane remains incomplete while the maintainer focuses on securing employment. This website and the local Studio are a working snapshot, not a production-ready service.</span></div></aside>}
export function Footer(){return <footer className="site-footer"><div className="shell"><div className="footer-lead"><div className="original-brand"><EvidenceBrand large/></div><p>Keep the context.<br/>Move the project forward.</p><div className="release-caption">{backend.version} source candidate<br/><Link href="/docs/releases">Release information ↗</Link></div></div><div className="footer-map">{groups.map(([title,...items])=><div key={title}><h2>{title}</h2>{items.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</div>)}</div><div className="footer-bottom"><span>© 2026 Praveen Rathee · <Link href="/license">MIT License</Link></span><span>Built for intentional work.</span><a href="#main">Back to top ↑</a></div></div></footer>}
