'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {createHomeOpticalRoute} from './home-optical-routes';
import {pageConnectionDesigns} from './page-connection-designs';
import type * as Three from 'three';
import type {SpatialStory,SpatialNode} from '../data/spatial-story';
import {OriginalGlassIconOrb as Orb} from './original-glass';
import {SemanticIcon,semanticIconColors} from './semantic-icon';
import {CubeAppIcon} from './evidence-cube';
import {ToolIdentity,toolName} from './tool-identity';
type Props={story:SpatialStory;progress:number;paused:boolean;small?:boolean;onView?:(i:number)=>void;onOpen:(node:SpatialNode,chapter:number)=>void;onUnavailable:()=>void};
const ease=(v:number)=>{const t=Math.max(0,Math.min(1,v));return t*t*(3-2*t)};
/** Persistent camera, pooled refractive ribbons and projected controls for page-specific compositions. */
export function SpatialStoryScene(props:Props){
 const host=useRef<HTMLDivElement>(null),mount=useRef<HTMLDivElement>(null),controls=useRef<(HTMLButtonElement|null)[]>([]),panes=useRef<(HTMLDivElement|null)[]>([]),live=useRef(props);live.current=props;
 const[view,setView]=useState(Math.min(props.story.chapters.length-1,Math.floor(props.progress))),[ready,setReady]=useState(false),viewRef=useRef(view);const chapter=props.story.chapters[view];
 useEffect(()=>{const element=host.current,canvas=mount.current;if(!element||!canvas)return;let disposed=false,cleanup=()=>{};
 const start=async()=>{const[T,{RoomEnvironment}]=await Promise.all([import('three'),import('three/examples/jsm/environments/RoomEnvironment.js')]);if(disposed)return;let renderer:Three.WebGLRenderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'})}catch{live.current.onUnavailable();return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;canvas.append(renderer.domElement);
 const scene=new T.Scene(),group=new T.Group(),camera=new T.OrthographicCamera(-5,5,4,-4,.1,50);camera.position.z=20;scene.add(group);const room=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;scene.environmentIntensity=1.5;room.dispose();pmrem.dispose();scene.add(new T.HemisphereLight(0xcbeaff,0x171827,2));const light=new T.DirectionalLight(0xe3f5ff,4),warm=new T.DirectionalLight(0xffd28a,2);scene.add(light,warm);warm.position.set(4,-2,6);
 const routeCount=9,opticalRoutes=Array.from({length:routeCount},()=>createHomeOpticalRoute(T,group,112,1,pageConnectionDesigns[live.current.story.id as keyof typeof pageConnectionDesigns]));element.dataset.connectionStyle=live.current.story.id+'-connections';
 const beadGeometry=new T.SphereGeometry(.021,8,6),beadMaterial=new T.MeshBasicMaterial({color:0xdcf3ff,transparent:true,opacity:.85});const beads=Array.from({length:routeCount*2},()=>{const m=new T.Mesh(beadGeometry,beadMaterial);group.add(m);return m});
 let width=1,height=1,worldWidth=10,frame=0,last=0,time=0,progress=live.current.progress,yaw=0,pitch=0,shownYaw=0,shownPitch=0,drag=false,mx=0,my=0,isReady=false;
 const resize=()=>{width=Math.max(1,element.clientWidth);height=Math.max(1,element.clientHeight);worldWidth=8*width/height;camera.left=-worldWidth/2;camera.right=worldWidth/2;camera.updateProjectionMatrix();renderer.setSize(width,height,false)};const ro=new ResizeObserver(resize);ro.observe(element);resize();
 const down=(e:PointerEvent)=>{if(live.current.paused||(e.target instanceof Element&&e.target.closest('button,a,input')))return;drag=true;mx=e.clientX;my=e.clientY;element.setPointerCapture(e.pointerId)};const move=(e:PointerEvent)=>{if(!drag)return;yaw=Math.max(-.22,Math.min(.22,yaw+(e.clientX-mx)*.001));pitch=Math.max(-.14,Math.min(.14,pitch-(e.clientY-my)*.0008));mx=e.clientX;my=e.clientY};const up=()=>{drag=false};const reset=()=>{yaw=0;pitch=0;drag=false};const lost=(e:Event)=>{e.preventDefault();live.current.onUnavailable()};element.addEventListener('pointerdown',down);element.addEventListener('pointermove',move);element.addEventListener('pointerup',up);element.addEventListener('pointercancel',up);window.addEventListener('scroll',reset,{passive:true});renderer.domElement.addEventListener('webglcontextlost',lost);
 const point=(n:{x:number;y:number})=>new T.Vector3((n.x-50)/100*worldWidth,(50-n.y)*.08,0),projected=new T.Vector3(),aPoint=new T.Vector3(),bPoint=new T.Vector3(),at=new T.Vector3(),next=new T.Vector3();
 const put=(el:HTMLElement,p:Three.Vector3)=>{projected.copy(p).applyMatrix4(group.matrixWorld).project(camera);el.style.left=((projected.x*.5+.5)*width)+'px';el.style.top=((-projected.y*.5+.5)*height)+'px'};
 const curve=(chapterIndex:number,route:number)=>{const c=live.current.story.chapters[chapterIndex],e=c.edges[route];if(!e){const p=point({x:50,y:50});return new T.CubicBezierCurve3(p,p.clone(),p.clone(),p.clone())}const a=point(c.nodes[e[0]]),b=point(c.nodes[e[1]]),d=b.clone().sub(a),length=d.length();d.normalize();const radius=(live.current.small?19:innerWidth<1450?28:34)*8/height;const trim=Math.min(radius,length*.25);a.addScaledVector(d,trim);b.addScaledVector(d,-trim);const h1=a.clone().lerp(b,.33),h2=a.clone().lerp(b,.67),bend=Math.min(1.05,a.distanceTo(b)*.28);const style=live.current.story.id;
 if(style==='how-it-works'){if(Math.abs(d.x)>Math.abs(d.y)){h1.set(T.MathUtils.lerp(a.x,b.x,.6),a.y,.12);h2.set(T.MathUtils.lerp(a.x,b.x,.4),b.y,.12)}else{h1.set(a.x,T.MathUtils.lerp(a.y,b.y,.6),.12);h2.set(b.x,T.MathUtils.lerp(a.y,b.y,.4),.12)}}
 else if(style==='integrations'){const normal=new T.Vector3(-d.y,d.x,0);h1.addScaledVector(normal,bend*.65);h2.addScaledVector(normal,bend*.65);h1.z=.3;h2.z=.3}
 else if(style==='docs'){h1.y+=bend*.7;h2.y+=bend*.7;h1.z=.16;h2.z=.16}
 else{h1.set(a.x,T.MathUtils.lerp(a.y,b.y,.55),.1);h2.set(b.x,T.MathUtils.lerp(a.y,b.y,.45),.1)}return new T.CubicBezierCurve3(a,h1,h2,b)};
 const tick=(now:number)=>{frame=requestAnimationFrame(tick);if(document.hidden){last=now;return}if(now-last<16)return;const dt=Math.min(.04,(now-last)/1000);last=now;const state=live.current,all=state.story.chapters;if(!state.paused)time+=dt;element.dataset.waveTime=time.toFixed(3);progress=state.paused?state.progress:progress+(state.progress-progress)*(1-Math.exp(-dt*10));const a=Math.min(all.length-1,Math.floor(progress)),b=Math.min(all.length-1,a+1),blend=a===b?0:ease(((progress%1)-.55)/.45),seen=blend<.5?a:b;if(seen!==viewRef.current){viewRef.current=seen;setView(seen);state.onView?.(seen)}shownYaw+=(yaw-shownYaw)*.16;shownPitch+=(pitch-shownPitch)*.16;group.rotation.set(shownPitch,shownYaw,0);group.updateMatrixWorld(true);element.dataset.progress=progress.toFixed(3);element.dataset.transitionState=Math.abs(progress-state.progress)<.02?'settled':'moving';element.dataset.manualRotation=(Math.abs(shownYaw)+Math.abs(shownPitch)).toFixed(4);element.style.setProperty('--story-label-opacity',String(Math.pow(Math.abs(blend-.5)*2,2)));light.position.set(-3+Math.sin(time*.35)*2,4+Math.cos(time*.23),7);
 const ca=Array.from({length:routeCount},(_,i)=>curve(a,i)),cb=Array.from({length:routeCount},(_,i)=>curve(b,i));for(let r=0;r<routeCount;r++){const alpha=(all[a].edges[r]?1-blend:0)+(all[b].edges[r]?blend:0);opticalRoutes[r].update(time,(t,target)=>{ca[r].getPoint(t,aPoint);cb[r].getPoint(t,bPoint);target.copy(aPoint).lerp(bPoint,blend)},alpha);for(let k=0;k<2;k++){const bead=beads[r*2+k],t=(time*.09+k*.5+r*.13)%1;opticalRoutes[r].pointAt(t,bead.position);bead.visible=alpha>.5}}
 for(let i=0;i<8;i++){const el=controls.current[i];if(!el)continue;const na=all[a].nodes[i],nb=all[b].nodes[i],alpha=(na?1-blend:0)+(nb?blend:0);at.copy(point(na??{x:50,y:50})).lerp(point(nb??{x:50,y:50}),blend);put(el,at);el.style.opacity=String(alpha);el.style.visibility=alpha>.02?'visible':'hidden';el.style.pointerEvents=alpha>.7?'auto':'none';el.tabIndex=alpha>.7?0:-1}
 for(let i=0;i<4;i++){const el=panes.current[i];if(!el)continue;const pa=all[a].panes?.[i],pb=all[b].panes?.[i],alpha=(pa?1-blend:0)+(pb?blend:0),p=pa??pb;if(!p){el.style.opacity='0';continue}const q=pb??pa!;at.copy(point(p)).lerp(point(q),blend);put(el,at);el.style.width=T.MathUtils.lerp(p.w,q.w,blend)/100*width+'px';el.style.height=T.MathUtils.lerp(p.h,q.h,blend)/100*height+'px';el.style.opacity=String(alpha*.85);el.style.transform=`rotateY(${shownYaw}rad) rotateX(${shownPitch}rad)`}
 if(!isReady){isReady=true;setReady(true)}renderer.render(scene,camera)};frame=requestAnimationFrame(tick);
 cleanup=()=>{cancelAnimationFrame(frame);ro.disconnect();element.removeEventListener('pointerdown',down);element.removeEventListener('pointermove',move);element.removeEventListener('pointerup',up);element.removeEventListener('pointercancel',up);window.removeEventListener('scroll',reset);renderer.domElement.removeEventListener('webglcontextlost',lost);opticalRoutes.forEach(route=>route.dispose());beadGeometry.dispose();beadMaterial.dispose();environment.dispose();renderer.dispose();renderer.domElement.remove()};};void start().catch(()=>{if(!disposed)live.current.onUnavailable()});return()=>{disposed=true;cleanup()};
 },[]);
 return <div ref={host} className={'spatial-scene '+(props.small?'is-small':'')} data-ready={ready} data-view-chapter={view} data-detail-companion><div className="spatial-scene-canvas" ref={mount} aria-hidden="true"/>{Array.from({length:4},(_,i)=><div key={i} ref={e=>{panes.current[i]=e}} className="spatial-scene-pane"><span>{chapter.panes?.[i]?.title}</span>{chapter.panes?.[i]?.rows&&<div className="spatial-pane-rows" aria-hidden="true">{chapter.panes[i].rows?.map(row=><p key={row}>{row}</p>)}</div>}{chapter.panes?.[i]?.toolIds?.map((id,k)=><button className="spatial-dock-tool flow-object" key={id} data-detail-name={toolName(id)} aria-label={toolName(id)} style={{left:k===0?'20%':'80%'}} onClick={()=>props.onOpen({name:toolName(id),icon:'tools',x:0,y:0,body:'Inspect this declared tool, its operation relationships and configuration requirements.',catalog:'tools',toolId:id},view)}><ToolIdentity id={id} size={props.small?23:38}/></button>)}</div>)}{Array.from({length:8},(_,i)=>{const n=chapter.nodes[i];return <button key={i} ref={e=>{controls.current[i]=e}} className="spatial-node flow-object" data-detail-name={n?.name} data-scene-centre={n?.brand?'true':undefined} aria-label={n?.name} onClick={()=>n&&props.onOpen(n,view)} style={{'--node-color':semanticIconColors[n?.icon??'project']} as CSSProperties}>{n&&<><Orb size={props.small?38:n.brand?82:64} color={semanticIconColors[n.icon]} decorative>{n.brand?<CubeAppIcon size={props.small?27:52}/>:<SemanticIcon name={n.icon} size={props.small?23:34}/>}</Orb><span className="spatial-node-label">{n.name}</span></>}</button>})}{chapter.track&&<p className="spatial-scene-track">{chapter.track}</p>}</div>;
}
