'use client';
import {useState} from 'react';
import Link from 'next/link';
import {guides} from '../data/guides';
import capabilities from '../data/integrations.json';
import backend from '../data/backend.json';
import {OriginalGlassIconOrb as Orb,OriginalGlassPill as Pill} from './original-glass';
import {SemanticIcon,type SemanticIconName} from './semantic-icon';
import {ToolBrowser} from './tool-browser';
import './story-library.css';
export function GuideLibrary(){const[query,setQuery]=useState(''),[group,setGroup]=useState('All');const shown=guides.filter(g=>(group==='All'||g.group===group)&&(g.title+' '+g.intro+' '+g.sections.map(s=>s.title).join(' ')).toLowerCase().includes(query.toLowerCase()));return <section id="guide-library" className="story-library"><p className="flow-kicker">THE GUIDE LIBRARY</p><h2>Start with what you need.</h2><label className="library-search">Search guides<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try installation, sources, hooks or recovery…"/></label><div className="library-filters">{['All','Get started','Use a project','Reference'].map(g=><Pill key={g} active={group===g} aria-pressed={group===g} onClick={()=>setGroup(g)}>{g}</Pill>)}</div><p role="status" className="catalog-note">{shown.length} matching guides</p><div className="library-books">{shown.map(g=><Link key={g.slug} href={'/docs/'+g.slug}><Orb size={52} color="#b5b8f1" decorative><SemanticIcon name={g.group==='Reference'?'api':g.group==='Get started'?'project':'guide'} size={28}/></Orb><span>{g.group}</span><h3>{g.title}</h3><p>{g.intro}</p><b>Open the guide ↗</b></Link>)}</div>{shown.length===0&&<p>No matching guides. Try a broader term or choose All.</p>}<Link className="library-related" href="/workflows">Explore the 24 individual workflows ↗</Link></section>}
const icons:Record<string,SemanticIconName>={Code:'api',Office:'guide','Data & BI':'sources','Research & media':'records',Sources:'project'};
export function CapabilityLibrary(){const[query,setQuery]=useState(''),[group,setGroup]=useState('All'),[selected,setSelected]=useState(capabilities[0]);const shown=capabilities.filter(c=>(group==='All'||group===c.category)&&(c.name+' '+c.operations).toLowerCase().includes(query.toLowerCase()));return <section id="capability-library" className="story-library"><p className="flow-kicker">EXPLORE THE CAPABILITIES</p><h2>Find the source. Inspect the route.</h2><label className="library-search">Search capabilities<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try Excel, code, PDF or research…"/></label><div className="library-filters">{['All','Code','Office','Data & BI','Research & media','Sources'].map(g=><Pill key={g} aria-pressed={group===g} active={group===g} onClick={()=>setGroup(g)}>{g}</Pill>)}</div><p className="catalog-note" role="status">{shown.length} capability groups · This website does not measure runtime readiness.</p><div className="capability-library-layout"><div className="capability-library-list">{shown.map(c=><button key={c.name} aria-pressed={selected.name===c.name} onClick={()=>setSelected(c)}><Orb size={40} color="#85dfbf" decorative><SemanticIcon name={icons[c.category]}/></Orb><span>{c.name}</span></button>)}{!shown.length&&<p>No matching capability.</p>}</div><article className="capability-library-detail" aria-live="polite"><p className="flow-kicker">{selected.category}</p><h3>{selected.name}</h3><p>{selected.operations}</p><dl><dt>Configuration</dt><dd>{selected.configuration}</dd><dt>Coverage and limits</dt><dd>{selected.limitation}</dd><dt>Readiness</dt><dd>Inspect current observations through the connected runtime before execution.</dd></dl><details><summary>Inspect its registered actions</summary><div className="library-actions">{selected.actions.map(a=><code key={a}>{a}</code>)}</div></details></article></div><details className="library-catalogue"><summary>Explore all tools, actions and worker relationships</summary><ToolBrowser/></details></section>}
export function ReleaseInspector(){const[query,setQuery]=useState(''),[copied,setCopied]=useState(''),[copyError,setCopyError]=useState(false);const assets=backend.assets.filter(a=>a.filename.toLowerCase().includes(query.toLowerCase()));return <section id="release-inspector" className="story-library"><p className="flow-kicker">RELEASE REFERENCE</p><h2>Inspect the exact package.</h2><p>Source candidate {backend.version}. Public availability and installed-native execution are not verified by this website.</p><div className="release-buttons"><Link href="https://github.com/rathee000001/evidence_lane_plugin/releases">View published releases ↗</Link><Link href="/docs/install">Read installation guide ↗</Link></div><details className="release-identity"><summary>Source-bound release identity</summary><dl><dt>Declared ref</dt><dd>{backend.release.release_ref}</dd><dt>Asset-set SHA-256</dt><dd><code>{backend.release.assets_sha256}</code></dd><dt>Bundle-plan SHA-256</dt><dd><code>{backend.release.bundle_plan_sha256}</code></dd></dl></details><label className="library-search">Find a component<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Component filename…"/></label><p role="status" className="catalog-note">{assets.length} source-bound component archives · {copyError?'Clipboard unavailable. Select and copy the displayed checksum.':copied?'Checksum copied for '+copied:'Select a checksum to copy it.'}</p><div className="release-assets">{assets.map(a=><article key={a.filename}><Orb size={42} decorative><SemanticIcon name="download"/></Orb><div><h3>{a.filename}</h3><p>{(a.bytes/1024/1024).toFixed(1)} MiB · {a.condition}</p><code>{a.sha256}</code></div><button onClick={async()=>{try{await navigator.clipboard.writeText(a.sha256);setCopied(a.filename);setCopyError(false)}catch{setCopied('');setCopyError(true);}}} aria-label={'Copy SHA-256 for '+a.filename}>Copy SHA-256</button></article>)}</div></section>}
