'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {createHomeOpticalRoute} from './home-optical-routes';
import {pageConnectionDesigns} from './page-connection-designs';
import type * as Three from 'three';
import {studioJourney} from '../data/studio-journey';
import {studioObserverViews} from '../data/studio-observer-views';
import {OriginalGlassIconOrb as Orb,OriginalGlassPill as Pill} from './original-glass';
import {SemanticIcon} from './semantic-icon';
import {studioViewIcons} from './studio-view-detail';
type Props={progress:number;paused:boolean;small?:boolean;selectedView?:string|null;onSelectView?:(view:string)=>void;onView?:(index:number)=>void;onOpen:(view:string,title?:string,body?:string)=>void;onUnavailable:()=>void};
const smooth=(value:number)=>{const t=Math.max(0,Math.min(1,value));return t*t*(3-2*t)};
export function StudioLivingScene(props:Props){
 const rootElement=useRef<HTMLDivElement>(null),canvasHost=useRef<HTMLDivElement>(null),windowElement=useRef<HTMLDivElement>(null),brandButton=useRef<HTMLButtonElement>(null),nodes=useRef<(HTMLButtonElement|null)[]>([]),hover=useRef(false),live=useRef(props);live.current=props;
 const[chapter,setChapter]=useState(Math.min(4,Math.floor(props.progress))),[ready,setReady]=useState(false);const currentChapter=useRef(chapter),readyRef=useRef(false);const story=studioJourney[chapter],view=studioObserverViews.find(v=>v.name===(props.selectedView??story.view))??studioObserverViews[0];
 useEffect(()=>{const host=rootElement.current,mount=canvasHost.current;if(!host||!mount)return;let gone=false,dispose=()=>{};
 const start=async()=>{const T=await import('three');const[{RoomEnvironment},{GLTFLoader}]=await Promise.all([import('three/examples/jsm/environments/RoomEnvironment.js'),import('three/examples/jsm/loaders/GLTFLoader.js')]);const model=await new GLTFLoader().loadAsync('/product/evidence-lane-cube.glb');const disposeModel=()=>model.scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});if(gone){disposeModel();return}let renderer:Three.WebGLRenderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'})}catch{disposeModel();live.current.onUnavailable();return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.setClearColor(0,0);mount.append(renderer.domElement);const scene=new T.Scene(),root=new T.Group(),camera=new T.OrthographicCamera(-5,5,4,-4,.1,80);camera.position.z=20;scene.add(root);
 const room=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;scene.environmentIntensity=1.6;room.dispose();pmrem.dispose();scene.add(new T.HemisphereLight(0xc2eaff,0x151e38,2));const key=new T.DirectionalLight(0xe4faff,4),rim=new T.DirectionalLight(0x8ccaff,2);key.position.set(-4,5,7);rim.position.set(4,-2,4);scene.add(key,rim);
 const glass=new T.MeshPhysicalMaterial({color:0xb9dcf2,metalness:.48,roughness:.14,clearcoat:1,clearcoatRoughness:.05,transparent:true,opacity:.72,depthWrite:false,side:T.DoubleSide});const segments=96;
 const routeMaterials=Array.from({length:5},()=>glass.clone());const strips=Array.from({length:18},(_,stripIndex)=>{const positions=new Float32Array((segments+1)*6),normals=new Float32Array(positions.length),indices=[];for(let j=0;j<segments;j++){const n=j*2;indices.push(n,n+1,n+2,n+1,n+3,n+2)}const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(positions,3));geometry.setAttribute('normal',new T.BufferAttribute(normals,3));geometry.setIndex(indices);const mesh=new T.Mesh(geometry,stripIndex<15?routeMaterials[Math.floor(stripIndex/3)]:glass);mesh.frustumCulled=false;mesh.visible=stripIndex>=15;root.add(mesh);return{mesh,geometry,positions,normals}});
 const opticalRoutes=Array.from({length:5},()=>createHomeOpticalRoute(T,root,112,1,pageConnectionDesigns.studio));host.dataset.connectionStyle='studio-observer-frame';
 const portGeometry=new T.TorusGeometry(.052,.008,8,24),portMaterial=new T.MeshBasicMaterial({color:0xb6e5f4,transparent:true,opacity:.62,depthWrite:false});const ports=Array.from({length:5},()=>{const port=new T.Mesh(portGeometry,portMaterial);root.add(port);return port});
 const brand=new T.Group(),sphereGeometry=new T.SphereGeometry(.57,40,28),sphereMaterial=new T.MeshPhysicalMaterial({color:0x91d8f4,metalness:.04,roughness:.045,transmission:.95,thickness:.16,ior:1.4,clearcoat:1,transparent:true,opacity:.30,depthWrite:false});brand.add(new T.Mesh(sphereGeometry,sphereMaterial));model.scene.scale.setScalar(.30);model.scene.rotation.set(.16,-.52,0);model.scene.traverse(o=>{if(o instanceof T.Mesh){const old=Array.isArray(o.material)?o.material:[o.material];const fresh=old.map(m=>{const name=m.name.toLowerCase().replaceAll('_',' ');return new T.MeshPhysicalMaterial({color:name.includes('mark')?0xe6f7ff:name.includes('blue')?0x367bbf:name.includes('pearl')?0xc6dfed:0x95afc9,metalness:.04,roughness:.26,clearcoat:.8,envMapIntensity:.35,side:T.DoubleSide})});old.forEach(m=>m.dispose());o.material=Array.isArray(o.material)?fresh:fresh[0]}});brand.add(model.scene);root.add(brand);
 const packetGeometry=new T.SphereGeometry(.019,8,6),packetMaterial=new T.MeshBasicMaterial({color:0xc5f4ff,transparent:true,opacity:.78});const packets=Array.from({length:10},()=>{const mesh=new T.Mesh(packetGeometry,packetMaterial);root.add(mesh);return mesh});
 let width=1,height=1,worldWidth=10,frame=0,last=0,time=0,progress=live.current.progress,yaw=0,pitch=0,shownYaw=0,shownPitch=0,drag=false,lastX=0,lastY=0;
 const resize=()=>{width=Math.max(1,host.clientWidth);height=Math.max(1,host.clientHeight);worldWidth=8*width/height;camera.left=-worldWidth/2;camera.right=worldWidth/2;camera.updateProjectionMatrix();renderer.setSize(width,height,false)};const ro=new ResizeObserver(resize);ro.observe(host);resize();
 const down=(e:PointerEvent)=>{if(live.current.paused||innerWidth<=1000||(e.target instanceof Element&&e.target.closest('button,a,input')))return;drag=true;lastX=e.clientX;lastY=e.clientY;host.setPointerCapture(e.pointerId)};const move=(e:PointerEvent)=>{if(!drag)return;yaw=Math.max(-.22,Math.min(.22,yaw+(e.clientX-lastX)*.001));pitch=Math.max(-.14,Math.min(.14,pitch-(e.clientY-lastY)*.0008));lastX=e.clientX;lastY=e.clientY};const up=()=>{drag=false};const reset=()=>{drag=false;yaw=0;pitch=0};host.addEventListener('pointerdown',down);host.addEventListener('pointermove',move);host.addEventListener('pointerup',up);host.addEventListener('pointercancel',up);window.addEventListener('scroll',reset,{passive:true});const lost=(e:Event)=>{e.preventDefault();live.current.onUnavailable()};renderer.domElement.addEventListener('webglcontextlost',lost);
 const vector=(x:number,y:number)=>new T.Vector3((x-50)/100*worldWidth,(50-y)*.08,0);const projected=new T.Vector3(),point=new T.Vector3(),before=new T.Vector3(),after=new T.Vector3();
 const put=(element:HTMLElement|null,position:Three.Vector3)=>{if(!element)return;projected.copy(position).applyMatrix4(root.matrixWorld).project(camera);element.style.left=((projected.x*.5+.5)*width).toFixed(2)+'px';element.style.top=((-projected.y*.5+.5)*height).toFixed(2)+'px'};
 const route=(index:number,stage:number)=>{const data=studioJourney[stage],w=data.window,node=index===4?data.brand:data.nodes[index];if(!node){const p=vector(w.x,w.y+w.h/2);return new T.CubicBezierCurve3(p,p.clone(),p.clone(),p.clone())}const start=vector(node.x,node.y);let x=Math.max(w.x-w.w/2+7,Math.min(w.x+w.w/2-7,node.x)),y=w.y+w.h/2;if(node.x<w.x-w.w/2-5){x=w.x-w.w/2;y=Math.max(w.y-w.h/2+7,Math.min(w.y+w.h/2-7,node.y))}const end=vector(x,y),direction=end.clone().sub(start).normalize();start.addScaledVector(direction,index===4?.57:(live.current.small?20:34)*8/height);const h1=start.clone().lerp(end,.33),h2=start.clone().lerp(end,.72);h1.x+=(index%2===0?.18:-.18);h2.z=.12;return new T.CubicBezierCurve3(start,h1,h2,end)};
 const tick=(now:number)=>{frame=requestAnimationFrame(tick);if(document.hidden){last=now;return}if(now-last<16)return;const dt=Math.min(.04,(now-last)/1000);last=now;const state=live.current;if(!state.paused)time+=dt;host.dataset.waveTime=time.toFixed(3);progress=state.paused?state.progress:progress+(state.progress-progress)*(1-Math.exp(-dt*10));const aIndex=Math.min(4,Math.floor(progress)),bIndex=Math.min(4,aIndex+1),mix=aIndex===4?0:smooth(((progress%1)-.55)/.45),a=studioJourney[aIndex],b=studioJourney[bIndex],seen=mix<.5?aIndex:bIndex;if(seen!==currentChapter.current){currentChapter.current=seen;setChapter(seen);live.current.onView?.(seen)}shownYaw+=(yaw-shownYaw)*.16;shownPitch+=(pitch-shownPitch)*.16;const poseX=shownPitch+(state.paused?0:Math.sin(time*.22)*.015),poseY=shownYaw+(state.paused?0:Math.sin(time*.18)*.025);root.rotation.set(poseX,poseY,0);root.updateMatrixWorld(true);host.dataset.progress=progress.toFixed(3);host.dataset.transitionState=Math.abs(progress-state.progress)<.02?'settled':'moving';host.dataset.morph=mix.toFixed(3);host.dataset.manualRotation=(Math.abs(shownYaw)+Math.abs(shownPitch)).toFixed(4);const fade=Math.pow(Math.abs(mix-.5)*2,2);host.style.setProperty('--studio-content-opacity',String(.2+fade*.8));key.position.x=-3+Math.sin(time*.3)*2;rim.position.y=-2+Math.cos(time*.25);
 const w={x:T.MathUtils.lerp(a.window.x,b.window.x,mix),y:T.MathUtils.lerp(a.window.y,b.window.y,mix),w:T.MathUtils.lerp(a.window.w,b.window.w,mix),h:T.MathUtils.lerp(a.window.h,b.window.h,mix)};put(windowElement.current,vector(w.x,w.y));if(windowElement.current){windowElement.current.style.width=(w.w/100*width)+'px';windowElement.current.style.height=(w.h/100*height)+'px';windowElement.current.style.transform=`translate(-50%,-50%) rotateX(${poseX}rad) rotateY(${poseY}rad)`}
 const positions=Array.from({length:4},(_,i)=>{const na=a.nodes[i]??a.brand,nb=b.nodes[i]??b.brand,bottomA=a.window.y+a.window.h/2,bottomB=b.window.y+b.window.h/2;const zone=(n:{x:number;y:number},win:{x:number;y:number;w:number;h:number})=>n.x<win.x-win.w/2?'left':n.x>win.x+win.w/2?'right':'bottom';if(zone(na,a.window)!==zone(nb,b.window)){const via=Math.min(90,Math.max(bottomA,bottomB)+14);return new T.CubicBezierCurve3(vector(na.x,na.y),vector(na.x,via),vector(nb.x,via),vector(nb.x,nb.y)).getPoint(mix)}return vector(na.x,na.y).lerp(vector(nb.x,nb.y),mix)});const currentRoute=(i:number)=>{const node=positions[i];let x=Math.max(w.x-w.w/2+7,Math.min(w.x+w.w/2-7,node.x/worldWidth*100+50)),y=w.y+w.h/2;if(node.x/worldWidth*100+50<w.x-w.w/2-5){x=w.x-w.w/2;y=Math.max(w.y-w.h/2+7,Math.min(w.y+w.h/2-7,50-node.y/.08))}else if(node.x/worldWidth*100+50>w.x+w.w/2+5){x=w.x+w.w/2;y=Math.max(w.y-w.h/2+7,Math.min(w.y+w.h/2-7,50-node.y/.08))}const end=vector(x,y),start=node.clone().addScaledVector(end.clone().sub(node).normalize(),(state.small?20:34)*8/height),h1=start.clone().lerp(end,.33),h2=start.clone().lerp(end,.72);h1.x+=(i%2?.18:-.18);h2.z=.12;return new T.CubicBezierCurve3(start,h1,h2,end)};const curvesA=Array.from({length:5},(_,i)=>i<4?currentRoute(i):route(i,aIndex)),curvesB=[...curvesA];for(let i=0;i<4;i++)routeMaterials[i].opacity=.72*((a.nodes[i]?1-mix:0)+(b.nodes[i]?mix:0));const brandPath=new T.CubicBezierCurve3(vector(a.brand.x,a.brand.y),vector(a.brand.x,90),vector(b.brand.x,90),vector(b.brand.x,b.brand.y));const brandPoint=brandPath.getPoint(mix),brandEnd=(()=>{const bx=brandPoint.x/worldWidth*100+50,by=50-brandPoint.y/.08;return bx>w.x+w.w/2?vector(w.x+w.w/2,Math.max(w.y-w.h/2+5,Math.min(w.y+w.h/2-5,by))):bx<w.x-w.w/2?vector(w.x-w.w/2,Math.max(w.y-w.h/2+5,Math.min(w.y+w.h/2-5,by))):vector(Math.max(w.x-w.w/2+5,Math.min(w.x+w.w/2-5,bx)),by<w.y?w.y-w.h/2:w.y+w.h/2)})(),brandStart=brandPoint.clone().addScaledVector(brandEnd.clone().sub(brandPoint).normalize(),.57),brandLink=new T.CubicBezierCurve3(brandStart,brandStart.clone().lerp(brandEnd,.33),brandStart.clone().lerp(brandEnd,.72),brandEnd);curvesA[4]=brandLink;curvesB[4]=brandLink;
 for(let edge=0;edge<5;edge++){const alpha=edge===4?1:(a.nodes[edge]?1-mix:0)+(b.nodes[edge]?mix:0);curvesA[edge].getPoint(1,before);curvesB[edge].getPoint(1,after);ports[edge].position.copy(before).lerp(after,mix);ports[edge].visible=alpha>.1;ports[edge].scale.setScalar(1+Math.sin(time*.7+edge)*.06);opticalRoutes[edge].update(time,(t,target)=>{curvesA[edge].getPoint(t,before);curvesB[edge].getPoint(t,after);target.copy(before).lerp(after,mix)},alpha)}
 for(let edge=5;edge<6;edge++)for(let strand=0;strand<3;strand++){const strip=strips[edge*3+strand];for(let j=0;j<=segments;j++){const t=j/segments;if(edge===5){const angle=t*Math.PI*2,c=Math.cos(angle),s=Math.sin(angle);point.set((w.x-50)/100*worldWidth+Math.sign(c)*Math.pow(Math.abs(c),.30)*w.w/200*worldWidth,(50-w.y)*.08+Math.sign(s)*Math.pow(Math.abs(s),.30)*w.h*.04,0);const angle2=angle+.006,c2=Math.cos(angle2),s2=Math.sin(angle2);after.set((w.x-50)/100*worldWidth+Math.sign(c2)*Math.pow(Math.abs(c2),.30)*w.w/200*worldWidth,(50-w.y)*.08+Math.sign(s2)*Math.pow(Math.abs(s2),.30)*w.h*.04,0)}else{curvesA[edge].getPoint(t,before);curvesB[edge].getPoint(t,after);point.copy(before).lerp(after,mix);curvesA[edge].getPoint(Math.min(1,t+.006),before);curvesB[edge].getPoint(Math.min(1,t+.006),after);after.copy(before).lerp(after,mix)}const dx=after.x-point.x,dy=after.y-point.y,length=Math.hypot(dx,dy)||1,nx=-dy/length,ny=dx/length,envelope=edge===5?1:Math.sin(Math.PI*t),spread=(strand-1)*.022*envelope+Math.sin(time*.5+t*8+strand*.3)*.024*envelope,half=strand===1?.014:.006;for(let side=0;side<2;side++){const k=j*6+side*3,offset=spread+(side?half:-half);strip.positions[k]=point.x+nx*offset;strip.positions[k+1]=point.y+ny*offset;strip.positions[k+2]=Math.sin(time*.35+t*6+strand)*.05*envelope;const twist=Math.sin(time*.45+t*6+strand*.5)*.22;strip.normals[k]=nx*Math.sin(twist);strip.normals[k+1]=ny*Math.sin(twist);strip.normals[k+2]=Math.cos(twist)}}strip.geometry.attributes.position.needsUpdate=true;strip.geometry.attributes.normal.needsUpdate=true}
 for(let i=0;i<4;i++){const element=nodes.current[i],na=a.nodes[i],nb=b.nodes[i];if(!element)continue;point.copy(positions[i]);put(element,point);const alpha=(na?1-mix:0)+(nb?mix:0);element.style.opacity=String(alpha);element.style.visibility=alpha>.01?'visible':'hidden';element.style.pointerEvents=alpha>.7?'auto':'none';element.tabIndex=alpha>.7?0:-1;const label=element.querySelector<HTMLElement>('.studio-scene-label');if(label)label.style.opacity=String(fade)}
 brand.position.copy(brandPoint);brand.scale.setScalar(state.paused?1:hover.current?1.04:1);model.scene.rotation.y=-.52+Math.sin(time*.25)*.05;put(brandButton.current,brand.position);for(let i=0;i<10;i++){const edge=Math.floor(i/2),t=(time*.11+i*.47)%1;curvesA[edge].getPoint(t,before);curvesB[edge].getPoint(t,after);opticalRoutes[edge].pointAt(t,packets[i].position);packets[i].visible=edge===4||Boolean(a.nodes[edge]||b.nodes[edge])}if(!readyRef.current){readyRef.current=true;setReady(true)}renderer.render(scene,camera)};frame=requestAnimationFrame(tick);
 dispose=()=>{cancelAnimationFrame(frame);ro.disconnect();host.removeEventListener('pointerdown',down);host.removeEventListener('pointermove',move);host.removeEventListener('pointerup',up);host.removeEventListener('pointercancel',up);window.removeEventListener('scroll',reset);renderer.domElement.removeEventListener('webglcontextlost',lost);strips.forEach(s=>s.geometry.dispose());opticalRoutes.forEach(route=>route.dispose());portGeometry.dispose();portMaterial.dispose();glass.dispose();routeMaterials.forEach(m=>m.dispose());sphereGeometry.dispose();sphereMaterial.dispose();packetGeometry.dispose();packetMaterial.dispose();disposeModel();environment.dispose();renderer.dispose();renderer.domElement.remove()};
 };void start().catch(()=>{if(!gone)live.current.onUnavailable()});return()=>{gone=true;dispose()};
 },[]);
 return <div ref={rootElement} className={'studio-living-scene '+(props.small?'is-small':'')} data-ready={ready} data-view-chapter={chapter} data-detail-companion><div className="studio-living-canvas" ref={canvasHost} aria-hidden="true"/><div className="studio-live-window" ref={windowElement}><header><strong>Evidence Lane Studio</strong><small>ILLUSTRATIVE · READ-ONLY</small><span aria-hidden="true">−　□　×</span></header><nav aria-label="Illustrative Studio views">{studioObserverViews.map(v=><button key={v.name} aria-pressed={v.name===view.name} onClick={()=>props.onSelectView?.(v.name)}>{v.name}</button>)}</nav><div className="studio-live-window-content"><p>{view.title}</p><div>{view.fields.map(([title,body])=><button className="studio-live-field flow-object" key={title} data-detail-name={title} onClick={()=>props.onOpen(view.name,title,body)}><Orb size={24} color={view.color} decorative><SemanticIcon name={studioViewIcons[view.name]??'studio'} size={16}/></Orb><span><strong>{title}</strong><small>{body}</small></span></button>)}</div></div><footer>Selected project · Current observations · Attributed evidence</footer></div><button ref={brandButton} className="studio-native-brand flow-object" data-scene-centre data-detail-name={story.centre} aria-label={'Explore '+story.centre.toLowerCase()} onPointerEnter={()=>{hover.current=true}} onPointerLeave={()=>{hover.current=false}} onFocus={()=>{hover.current=true}} onBlur={()=>{hover.current=false}} onClick={()=>props.onOpen('Overview',story.name,story.body)}><span className="studio-brand-hit"/><span className="studio-scene-label">{story.centre}</span></button>{Array.from({length:4},(_,i)=>{const node=story.nodes[i];return <button key={i} ref={e=>{nodes.current[i]=e}} className="studio-live-node flow-object" data-detail-name={node?.name} aria-label={node?.name} onClick={()=>node&&props.onOpen(node.view,node.name,node.body)} style={{'--node-color':node?.color??'#9edcee'} as CSSProperties}>{node&&<><Orb size={props.small?40:68} color={node.color} decorative>{node.image?<img src={node.image} alt=""/>:<SemanticIcon name={node.icon} size={34}/>}</Orb><span className="studio-scene-label">{node.name}</span></>}</button>})}</div>;
}
