'use client';
import {useCallback,useState,type CSSProperties} from 'react';
import Link from 'next/link';
import {PageUniverse} from './page-universe';
import {OriginalGlassIconOrb as Orb,OriginalGlassPill as Pill} from './original-glass';
import {OriginalGlassPopup} from './original-popup';
import {DetailControlCompanion} from './detail-control-companion';
import {SemanticIcon,type SemanticIconName} from './semantic-icon';
import {CubeAppIcon} from './evidence-cube';
import {useSceneFocus,triggerIdentity} from './scene-focus';
import {useMotion} from './experience';
import {studioPanels} from '../data/studio-panels';
import {StudioViewDetail,studioViewIcons} from './studio-view-detail';
import './home-flow.css';
import './neon-glass.css';
import './cosmic-pages.css';

const extra=[{name:'Learning',color:'#8de0b1',title:'Keep the lessons attributed.',description:'Inspect procedural lessons recorded after verified work, their evidence and applicability.',fields:[['Procedure','What the verified work established.'],['Evidence','The task and checks behind the lesson.'],['Applicability','The project and operation context.'],['Revocation','Withdrawn lessons retain their history.']]},{name:'Compute',color:'#e9ce87',title:'Read the measured environment.',description:'See declared CPU and accelerator routes alongside actual compatibility observations.',fields:[['CPU','The operation’s supported local CPU route.'],['Accelerators','Only the devices and runtimes supported by that operation.'],['Compatibility','The measured driver and dependency environment.'],['Budgets','The bounds of the selected operation.']]},{name:'Diagnostics',color:'#86d6ed',title:'See what is known—and missing.',description:'Read engine, client and toolchain observations without confusing configuration with verification.',fields:[['Engine connection','Service observations and last received state.'],['Session binding','The explicitly selected client and project.'],['Dependencies','Measured tool availability and reported gaps.'],['Qualification','Installed, configured and executed are separate states.']]}];
const views=[...studioPanels,...extra];
export function StudioWorld(){const[selected,setSelected]=useState(0),[rail,setRail]=useState(true),[detail,setDetail]=useState<{view:string;title:string;body:string;icon:SemanticIconName;color:string}|null>(null);const focus=useSceneFocus(),{paused,toggle}=useMotion();const view=views[selected],icon=studioViewIcons[view.name]??'studio';const close=useCallback(()=>setDetail(null),[]);
 const open=(name:string,title?:string,body?:string)=>{const item=views.find(v=>v.name===name);const next={view:name,title:title??name,body:body??item?.description??'Studio observes the selected project and its persistent local engine. Navigate and inspect here; direct project changes through Codex.',icon:(studioViewIcons[name]??'studio') as SemanticIconName,color:item?.color??'#8bdaf4'};focus.select(name,triggerIdentity(document.activeElement));setDetail(next)};
 return <div className="home-flow cosmic-page studio-world" data-motion-paused={paused} data-universe-stage={selected}><PageUniverse world="studio"/>
 <section className="cosmic-hero studio-world-hero"><div className="cosmic-heading"><p className="flow-kicker">EVIDENCE LANE / STUDIO</p><h1>A window into<br/><em>the work.</em></h1><p>Inspect the project.<br/>Keep decisions in Codex.</p><ul className="cosmic-intents"><li><Orb size={40} color="#a7c7ff" decorative><SemanticIcon name="checks"/></Orb><span><strong>See clearly</strong>Plan, jobs, sources and evidence.</span></li><li><Orb size={40} color="#e6bd7c" decorative><SemanticIcon name="memory"/></Orb><span><strong>Keep context</strong>Separate records, connected references.</span></li><li><Orb size={40} color="#80dec4" decorative><SemanticIcon name="workflow"/></Orb><span><strong>Stay in control</strong>Project changes go through Codex.</span></li></ul><a className="cosmic-text-link" href="#studio-demo">Explore the observer ↓</a></div>
 <div className="studio-hero-illustration"><div className="studio-brain-orbit"><Orb size={112} color="#ab9eee" decorative><SemanticIcon name="memory" size={73}/></Orb><i/></div><div className="studio-hero-window"><header><Orb size={26} decorative><SemanticIcon name="studio" size={16}/></Orb><strong>Evidence Lane Studio</strong><span>ILLUSTRATIVE · READ-ONLY</span></header><div className="studio-hero-window-content"><aside><CubeAppIcon size={46}/><span>Selected project</span><i/><i/><i/></aside><div><nav><b>Plan</b><span>Jobs</span><span>Evidence</span></nav><article><SemanticIcon name="plan"/><strong>Current task</strong><p>Scope and expected outcome</p></article><article><SemanticIcon name="resume"/><strong>Next task</strong><p>Dependencies and Plan order</p></article><article><SemanticIcon name="checks"/><strong>Recorded checks</strong><p>Observed results and coverage</p></article></div></div></div><button className="studio-hero-cube" onClick={()=>open('Overview')} aria-label="Explore the Studio overview"><Orb size={96} color="#93dcff" decorative><CubeAppIcon size={62}/></Orb></button><div className="studio-plinth"/></div></section>
 <section className="studio-demo cosmic-section" id="studio-demo"><header className="cosmic-section-heading"><p className="flow-kicker">01 / EXPLORE THE OBSERVER</p><h2>The view changes.<br/><em>The project stays in context.</em></h2><p>Select a view to explore the information it presents. This website illustration is not connected to your engine.</p></header><div className="studio-window" data-detail-group><header className="studio-window-title"><Orb size={33} color="#8ecdf5" decorative><SemanticIcon name="studio"/></Orb><strong>Evidence Lane Studio</strong><span>ILLUSTRATIVE · READ-ONLY</span><div aria-hidden="true">−　□　×</div></header><div className={'studio-window-body '+(!rail?'rail-collapsed':'')}><aside className="studio-project-rail"><button aria-expanded={rail} onClick={()=>setRail(!rail)}>{rail?'‹ Project context':'›'} </button>{rail&&<><CubeAppIcon size={62}/><strong>Your selected project</strong><span>Selected through Codex</span><div className="studio-project-marker"><SemanticIcon name="project"/>Project records</div><p>One persistent local engine.<br/>Separate project state.<br/>A read-only human view.</p></>}</aside><div className="studio-window-main"><nav aria-label="Studio views">{views.map((v,i)=><Pill key={v.name} active={i===selected} aria-pressed={i===selected} data-detail-action={v.name} data-detail-name={v.name} leading={<Orb size={27} color={v.color} decorative><SemanticIcon name={studioViewIcons[v.name]??'studio'} size={16}/></Orb>} onClick={()=>setSelected(i)}>{v.name}</Pill>)}</nav><section className="studio-window-view" style={{'--view-color':view.color} as CSSProperties}><div className="studio-view-heading"><Orb size={60} color={view.color} decorative><SemanticIcon name={icon} size={30}/></Orb><div><p className="flow-kicker">{view.name}</p><h3>{view.title}</h3></div></div><p>{view.description}</p><div className="studio-observation-cards">{view.fields.map(([title,body],i)=><button key={title} onClick={()=>open(view.name,title,body)} data-detail-name={title}><span className="studio-field-index">{String(i+1).padStart(2,'0')}</span><strong>{title}</strong><p>{body}</p><span>Inspect this field ↗</span></button>)}</div><Pill leading={<Orb size={31} color={view.color} decorative><SemanticIcon name={icon}/></Orb>} onClick={()=>open(view.name)}>Explore {view.name.toLowerCase()} details ↗</Pill></section><footer><span>Project context</span><span>Current Plan</span><span>Attributed evidence</span></footer></div></div></div></section>
 <section className="cosmic-section studio-evidence-section"><div className="cosmic-section-heading"><p className="flow-kicker">02 / INSPECT THE EVIDENCE</p><h2>Open the result.<br/><em>Follow what supports it.</em></h2><p>A result, its source references and its recorded checks answer different questions. Keep each visible in its own context.</p></div><div className="studio-evidence-trail" data-detail-group>{[['Sources','sources','Selected material and identity'],['Work','work','Task and operation references'],['Evidence','results','Addressed output and receipts'],['Checks','checks','What was actually observed']].map(([name,glyph,body],i)=><button key={name} data-detail-action="Evidence" data-detail-name={name} onClick={()=>open('Evidence',name,body)}><Orb size={80} color={['#80c6f3','#bd9afa','#80e2bd','#eac680'][i]} decorative><SemanticIcon name={glyph as SemanticIconName} size={36}/></Orb><strong>{name}</strong><span>{body}</span></button>)}</div></section>
 <section className="cosmic-section"><header className="cosmic-section-heading"><p className="flow-kicker">03 / SEE THE BOUNDARIES</p><h2>Observation stays visible.<br/><em>Authority stays explicit.</em></h2></header><div className="cosmic-card-grid" data-detail-group>{[['Toolchains','Declared tools are not measured readiness.'],['Workers','A process is not proof of task completion.'],['Connections','A connected client does not gain extra project access.']].map(([name,body])=><button className="cosmic-glass-card" key={name} data-detail-action={name} data-detail-name={name} onClick={()=>open(name)}><Orb size={58} color={views.find(v=>v.name===name)?.color} decorative><SemanticIcon name={studioViewIcons[name]} size={28}/></Orb><h3>{name}</h3><p>{body}</p><span>Explore the view ↗</span></button>)}</div></section>
 <section className="cosmic-finish"><h2>Open. Minimise. Return.</h2><p>Studio runs on persistent local Windows with Codex Desktop Stable or Beta. The engine can remain available in the background; Studio remains visible and accessible.</p><Link href="/docs/studio">Read the Studio guide ↗</Link></section><div className="flow-controls"><button onClick={toggle} aria-pressed={paused}>{paused?'Play motion':'Pause motion'}</button></div>
 <OriginalGlassPopup open={!!detail} onClose={close} panelId="studio-world-detail" labelledBy="studio-world-detail-title" companion={<DetailControlCompanion onSelect={id=>open(id)}/>}><div className="cosmic-detail"><header><Orb size={72} color={detail?.color} decorative><SemanticIcon name={detail?.icon??'studio'} size={36}/></Orb><div><p className="flow-kicker">STUDIO / READ-ONLY VIEW</p><h2 id="studio-world-detail-title">{detail?.title}</h2><p>{detail?.body}</p></div></header>{detail&&<StudioViewDetail view={detail.view}/>}</div></OriginalGlassPopup>
 </div>;
}
