'use client';
import {ToolBrowser} from './tool-browser';
import {StudioOverviewGraphic} from './studio-overview-graphic';
import {productRecords} from '../data/product-story';
import {OriginalGlassIconOrb as Orb} from './original-glass';
import {SemanticIcon,type SemanticIconName,semanticIconColors} from './semantic-icon';
export const studioViewIcons:Record<string,SemanticIconName>={Plan:'plan',Jobs:'work',Workers:'worker',Evidence:'results',Toolchains:'tools',Connections:'connections',Learning:'learning',Compute:'compute',Diagnostics:'checks'};
const details:Record<string,{summary:string;fields:[string,string][]}>={
 Overview:{summary:'A visible, read-only window into the selected project and the shared local engine.',fields:[['Plan and jobs','Follow ordered work and its recorded state.'],['Evidence and learning','Inspect source references, results, checks and procedural lessons.'],['Tools and compute','Inspect declared routes and measured readiness.'],['Human controls','View, navigate, open, minimise and restore. Direct project changes through Codex.']]},
 Plan:{summary:'The selected project’s current work, task order and recorded progress.',fields:[['Current revision','The current ordered task list and scope.'],['Task status','Completed work, the active task and queued work.'],['Task contract','The outcome, dependencies and verification expected for a task.'],['Steers','Affected future work changes while completed history remains intact.']]},
 Jobs:{summary:'Submitted work and its durable state, with references to the project task and result.',fields:[['Waiting and running','Queued and running jobs have distinct states.'],['Safe boundaries','Checkpointed, cancelled and superseded jobs retain their history.'],['Outcomes','Succeeded, failed and uncertain outcomes remain distinguishable.'],['Uncertain effects','An uncertain operation is not silently replayed.']]},
 Workers:{summary:'Engine-owned tool processes, the operations they handle and their observed readiness.',fields:[['Operation scope','Allowed inputs, paths and output bounds.'],['Tool environment','The declared dependencies for the operation.'],['Execution observations','Actual worker identity and result when available.']]},
 Evidence:{summary:'Recorded results and the source and verification references behind them.',fields:[['Result','The deliverable or recorded outcome tied to its task.'],['Source trail','Selected material, identities and snapshots.'],['Checks','What was observed and within what coverage.'],['Limits','Missing, unrun or uncertain checks remain visible.']]},
 Connections:{summary:'Client sessions and their connection to the shared local engine.',fields:[['Host profile','Codex Desktop Stable or Beta on persistent local Windows.'],['Project binding','The selected project and attributed client session.'],['Connection state','Engine observations of the supported connection.'],['Scoped API access','Explicit HTTPS/TLS API access needs its declared credentials and scope; it does not add another host profile.']]},
 Learning:{summary:'Procedural lessons recorded after verified work, with their evidence and scope.',fields:[['Lesson','The useful procedure and the work it came from.'],['Evidence','The observations that supported recording it.'],['Applicability','The project and operation context.'],['Revocation','A lesson can be revoked without rewriting its history.']]},
 Compute:{summary:'Declared compute routes and measured compatibility for the selected operation.',fields:[['CPU','The general local route for CPU tools.'],['NVIDIA CUDA','Requires declared support, compatible hardware and a measured environment.'],['AMD ROCm','Requires a supported runtime and compatible operation.'],['DirectML','Available only where a supported Windows operation declares it.']]},
 Diagnostics:{summary:'Engine diagnostic observations and the limits of what has been verified.',fields:[['Engine','Connection and service observations.'],['Client','Exact host profile and project/session binding.'],['Toolchain','Dependency readiness and operation-specific checks.'],['Qualification','Configured, installed and verified states remain separate.']]}
};
export function StudioViewDetail({view}:{view:string}){if(view==='Toolchains')return <ToolBrowser/>;const d=details[view]??details.Diagnostics;const icon=studioViewIcons[view]??'studio';return <section className="studio-view-detail"><header><Orb size={54} color={semanticIconColors[icon]} decorative><SemanticIcon name={icon}/></Orb><h3>{view}</h3></header><p>{d.summary}</p>{view==='Overview'&&<StudioOverviewGraphic/>}<dl className="studio-view-fields">{d.fields.map(([name,description])=><div key={name}><dt>{name}</dt><dd>{description}</dd></div>)}</dl>{view==='Workers'&&<ToolBrowser initialMode="workers"/>}<p className="catalog-note">This is a guide to the information shown in Studio. It is not a live view of your engine or project.</p></section>}
