'use client';
import {useEffect,useState} from 'react';
import data from '../data/tool-browser.json';
import {ToolIdentity,ToolLogoRow,toolName} from './tool-identity';
import {OriginalGlassPill as Pill} from './original-glass';
import {OriginalGlassIconOrb} from './original-glass';
import {SemanticIcon,type SemanticIconName} from './semantic-icon';
function AtlasIcon({name,size=42}:{name:SemanticIconName;size?:number}){return <OriginalGlassIconOrb size={size} decorative><SemanticIcon name={name}/></OriginalGlassIconOrb>}

export function ToolBrowser({initialTool,initialMode='tools',initialAction,initialWorker}:{initialTool?:string;initialMode?:'tools'|'actions'|'workers';initialAction?:string;initialWorker?:string}){const[limit,setLimit]=useState(40);const[relatedLimit,setRelatedLimit]=useState(12);useEffect(()=>setLimit(40),[initialMode]);const[mode,setMode]=useState(initialMode),[query,setQuery]=useState(''),[selected,setSelected]=useState(initialTool??''),[actionId,setActionId]=useState(initialAction??''),[workerId,setWorkerId]=useState(initialWorker??'');const tools=data.tools.filter(t=>(toolName(t.id)+' '+t.kind+' '+t.packages.join(' ')).toLowerCase().includes(query.toLowerCase()));const actions=data.operations.filter(a=>(a.id+' '+a.description+' '+a.profile).toLowerCase().includes(query.toLowerCase()));const workers=data.workers.filter(w=>w.id.toLowerCase().includes(query.toLowerCase()));useEffect(()=>setRelatedLimit(12),[selected]);const tool=data.tools.find(t=>t.id===selected),action=data.operations.find(a=>a.id===actionId),worker=data.workers.find(w=>w.id===workerId);return <section className="tool-browser"><div className="tool-browser-modes">{(['tools','actions','workers'] as const).map((m,i)=><Pill key={m} active={mode===m} aria-pressed={mode===m} onClick={()=>{setMode(m);setQuery('')}}>{[`${data.toolCount} tools & dependencies`,`${data.actionCount} actions`,`${data.workerOperationCount} worker operations`][i]}</Pill>)}</div><label className="tool-search">Search {mode}<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setLimit(40)}} placeholder={mode==='tools'?'Tool, library or package name':mode==='actions'?'Action, purpose or profile':'Worker operation name'}/></label><div className="tool-browser-layout"><div className="tool-browser-list">
 {mode==='tools'&&tools.slice(0,limit).map(t=><button key={t.id} aria-pressed={selected===t.id} onClick={()=>setSelected(t.id)}><ToolIdentity id={t.id}/><span><strong>{toolName(t.id)}</strong><small>{t.kind.replaceAll('_',' ')}</small></span></button>)}
 {mode==='actions'&&actions.slice(0,limit).map(a=><button key={a.id} aria-pressed={actionId===a.id} onClick={()=>setActionId(a.id)}><span><strong>{a.id.replaceAll('_',' ')}</strong><small>{a.profile} · {a.mutates?'Changes state':'Read'}</small></span></button>)}
 {mode==='workers'&&workers.slice(0,limit).map(w=><button key={w.id} aria-pressed={workerId===w.id} onClick={()=>setWorkerId(w.id)}><span><strong>{w.id.replaceAll('_',' ')}</strong><small>{w.operations.length} invoking actions</small></span></button>)}
 {((mode==='tools'&&!tools.length)||(mode==='actions'&&!actions.length)||(mode==='workers'&&!workers.length))&&<p>No matches in the current catalogue.</p>}
 {(mode==='tools'?tools.length:mode==='actions'?actions.length:workers.length)>limit&&<button className="catalogue-more" onClick={()=>setLimit(n=>n+40)}>Show the next 40 entries ↓</button>}
 </div><div className="tool-browser-inspector">
 {mode==='tools'&&(tool?<><header><ToolIdentity id={tool.id} size={74}/><div><h3>{toolName(tool.id)}</h3><span>{tool.kind.replaceAll('_',' ')}</span></div></header><p>{tool.provisioning}.</p><dl className="tool-properties"><div><dt>Delivery role</dt><dd>{tool.required?'Required shared Windows bundle':tool.external?'Configured external service':'Internal or operation-specific component'}</dd></div><div><dt>Configuration</dt><dd>{tool.external?'Explicit external configuration required':'No external service configuration declared'}</dd></div><div><dt>Licence</dt><dd>{tool.license?'Separate licence/grant required':'No separate licence grant declared by this catalogue'}</dd></div></dl><h4>Declared packages</h4>{tool.packages.length?<ul>{tool.packages.map(p=><li key={p}>{p}</li>)}</ul>:<p className="catalog-note">Provided as native tooling, packaged engine code, a standard-library component or the declared adapter.</p>}<h4>Related actions</h4><div className="tool-related-actions">{tool.operations.length?tool.operations.slice(0,relatedLimit).map(id=><button key={id} onClick={()=>{setActionId(id);setMode('actions');setQuery('')}}>{id.replaceAll('_',' ')} ↗</button>):<p>Retained in the catalogue; no direct operation route references this entry in the current projection.</p>}</div>{tool.operations.length>relatedLimit&&<button className="catalogue-more" onClick={()=>setRelatedLimit(n=>n+24)}>Show more related actions ({tool.operations.length-relatedLimit} remaining) ↓</button>}</>:<CatalogueIntro kind="tools"/>)}
 {mode==='actions'&&(action?<><h3>{action.id.replaceAll('_',' ')}</h3><p>{action.description}</p><dl className="tool-properties"><div><dt>Effect</dt><dd>{action.mutates?'Changes project or runtime state':'Read-only action'}</dd></div><div><dt>Permission</dt><dd>{action.permission}</dd></div><div><dt>Workflow</dt><dd>{action.workflow}</dd></div><div><dt>Task scope</dt><dd>{action.requiresTask?'Requires the active work boundary':'Does not require an active work task'}</dd></div></dl><h4>Declared tools</h4><ToolLogoRow tools={action.tools} onSelect={id=>{setSelected(id);setMode('tools');setQuery('')}}/><h4>Operation routes</h4>{action.routes.map(r=><article className="tool-route" key={r.id}><strong>{r.id}</strong><p>{r.reason}</p><span>{r.provider} · {r.fidelity}</span></article>)}{action.workers.length>0&&<><h4>Worker operations</h4><div className="tool-related-actions">{action.workers.map(id=><button key={id} onClick={()=>{setWorkerId(id);setMode('workers');setQuery('')}}>{id.replaceAll('_',' ')} ↗</button>)}</div></>}</>:<CatalogueIntro kind="actions"/>)}
 {mode==='workers'&&(worker?<><h3>{worker.id.replaceAll('_',' ')}</h3><p>An owned OS worker operation invoked through the relevant engine route. Worker processes carry out bounded tool work; they are not AI subagents.</p><div className="worker-mini-flow"><span>Task scope</span><i>→</i><span>Worker</span><i>→</i><span>Result checks</span></div><h4>Invoking actions</h4><div className="tool-related-actions">{worker.operations.map(id=><button key={id} onClick={()=>{setActionId(id);setMode('actions');setQuery('')}}>{id.replaceAll('_',' ')} ↗</button>)}</div><p className="catalog-note">Actual worker identity, readiness and execution are observed at runtime. This catalogue does not show running processes.</p></>:<CatalogueIntro kind="workers"/>)}
 </div></div><p className="catalog-note">Current source catalogue: {data.toolCount} tools/dependencies, {data.actionCount} actions. Installation and execution have not been verified by this website.</p></section>}
function CatalogueIntro({kind}:{kind:string}){return <><AtlasIcon name={kind==='workers'?'work':kind==='actions'?'workflow':'tools'} size={74}/><h3>{kind==='workers'?'Inspect worker operations':kind==='actions'?'Inspect an action':'Inspect a tool or dependency'}</h3><p>Select an entry to see its role and relationships in the current backend contracts.</p><div className="worker-mini-flow"><span>Workflow</span><i>→</i><span>Action</span><i>→</i><span>Tools & workers</span></div></>}
