import type {CSSProperties} from 'react';
import {OriginalGlassIconOrb} from './original-glass';
import {SemanticIcon} from './semantic-icon';
import catalogIcons from '../../public/brands/catalog/attribution.json';
const files=new Set(catalogIcons.icons.map(x=>x.slug));
const map:Record<string,string>={SQLite_CAS:'sqlite',SQLite_FTS5_BM25:'sqlite',APSW_SQLite_engine:'sqlite',SQLite_immutable_URI_reader:'sqlite',sqlite_vec:'sqlite',LangGraph_Mermaid_engine:'langgraph',Mermaid_CLI_mmdc:'mermaid',NodeJS_TypeScript:'typescript',pytest:'pytest',Ruff:'ruff',pandas:'pandas',pyarrow:'apachearrow',RapidOCR_ONNX_Runtime:'onnx',OpenCV:'opencv',MCP_Python_SDK:'modelcontextprotocol',Pydantic:'pydantic',FFmpeg:'ffmpeg',DuckDB:'duckdb',SQLAlchemy:'sqlalchemy',LangChain:'langchain',SentenceTransformers:'huggingface',HuggingFace_Hub_ModelSnapshot:'huggingface',FastAPI:'fastapi',Pydantic_Settings:'pydantic',Polars:'polars',NextJS_React_ThreeJS_FramerMotion:'nextdotjs',FastMCP:'modelcontextprotocol',Milvus:'milvus',OpenSearch:'opensearch',OpenTelemetry:'opentelemetry',Grafana:'grafana',LibreOffice:'libreoffice',JSONSchema:'json'};
const originals:Record<string,string>={Tableau_Hyper_API:'tableau.ico',PowerBI_TOM:'powerbi.svg',PBIXRay:'powerbi.svg',Git:'git.svg',GitPython:'git.svg',Git_detector:'git.svg',PyGithub:'github.png',Python:'python.svg',DOCX_OpenXML:'word.svg',PPTX_OpenXML:'powerpoint.svg',openpyxl:'excel.svg',python_calamine:'excel.svg'};
const titles:Record<string,string>={hashlib_pathlib:'Python hashing & paths',SQLite_CAS:'SQLite content-addressed storage',SQLite_FTS5_BM25:'SQLite FTS5 / BM25',APSW_SQLite_engine:'APSW SQLite engine',NodeJS_TypeScript:'Node.js & TypeScript',LangGraph_Mermaid_engine:'LangGraph / Mermaid engine',Python_Graphviz_DOT_engine:'Python Graphviz / DOT engine',LlamaIndex_SQLite_indexer:'LlamaIndex SQLite indexer',Mermaid_CLI_mmdc:'Mermaid CLI',DOCX_OpenXML:'Word / OpenXML',PPTX_OpenXML:'PowerPoint / OpenXML',Tableau_Hyper_API:'Tableau Hyper API',PowerBI_TOM:'Power BI TOM',NextJS_React_ThreeJS_FramerMotion:'Next.js / React / Three.js / Framer Motion',HuggingFace_Hub_ModelSnapshot:'Hugging Face model snapshots',TreeSitter_LanguagePack:'Tree-sitter language pack',Cryptography_PyJWT:'Cryptography / PyJWT'};
export function toolName(id:string){return titles[id]??id.replaceAll('_',' ')}
export function toolTone(id:string){const hex=catalogIcons.icons.find(i=>i.slug===map[id])?.hex;return hex?`color-mix(in srgb, #${hex} 48%, #d5efff)`:id==='Git'?'#ef9979':id==='Python'?'#86d0f4':'#c7b4f0'}
export function ToolIdentity({id,size=42}:{id:string;size?:number}){const slug=map[id],original=originals[id];const entry=catalogIcons.icons.find(i=>i.slug===slug);const color=toolTone(id);return <OriginalGlassIconOrb size={size} color={color} decorative>{original?<img src={`/brands/${original}`} alt=""/>:slug&&files.has(slug)?<img className="catalog-vendor-mark" src={`/brands/catalog/${slug}.svg`} alt=""/>:id.startsWith('SQLite')?<SemanticIcon name="sources"/>:id.includes('parser')||id.includes('OpenXML')?<SemanticIcon name="guide"/>:id.includes('Hash')||id.includes('Secret')?<SemanticIcon name="checks"/>:<svg viewBox="0 0 24 24" aria-hidden="true" data-tool-mark={id}><rect x="3" y="3" width="18" height="18" rx="4" fill="#8f84bf66" stroke="#dccfff"/><text x="12" y="12.5" textAnchor="middle" dominantBaseline="middle" fill="#f4edff" fontFamily="sans-serif" fontSize="7.5" fontWeight="700">{id.split(/[_\s]+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}</text></svg>}</OriginalGlassIconOrb>}
export const toolAliases:Record<string,string>={'Tree-sitter':'TreeSitter_LanguagePack','DOCX / OpenXML':'DOCX_OpenXML','PPTX / OpenXML':'PPTX_OpenXML','Tableau Hyper':'Tableau_Hyper_API','Excel readers':'openpyxl','Power BI tooling':'PowerBI_TOM','OCR tools':'RapidOCR_ONNX_Runtime','Image/OCR tools':'OpenCV','HTTP clients':'HTTPX','Source readers':'Python','Artifact tools':'Project_inventory','Local code':'Git','GitHub code':'PyGithub','Word':'DOCX_OpenXML','PowerPoint':'PPTX_OpenXML','Excel':'openpyxl','Structured data':'DuckDB','Tableau':'Tableau_Hyper_API','Power BI':'PowerBI_TOM','PDF & OCR':'PyMuPDF','Images & media':'OpenCV','Research & web':'HTTPX','Artifacts':'Project_inventory','Custom sources / selected SQLite':'SQLite_immutable_URI_reader'};
export function ToolLogoRow({tools,onSelect}:{tools:string[];onSelect?:(id:string)=>void}){return <div className="tool-logo-row">{tools.map(label=>{const id=toolAliases[label]??label;return onSelect?<button key={id} style={{'--item-color':toolTone(id)} as CSSProperties} onClick={()=>onSelect(id)} data-detail-name={toolName(id)} data-tool-id={id} data-detail-action={'tool:'+id}><ToolIdentity id={id} size={34}/><span>{toolName(id)}</span></button>:<span key={id} style={{'--item-color':toolTone(id)} as CSSProperties}><ToolIdentity id={id} size={30}/><span>{label}</span></span>})}</div>}
