'use client';
import {useCallback,useEffect,useLayoutEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {AnimatePresence,motion} from 'framer-motion';
import Link from 'next/link';
import workflows from '../data/workflows.json';
import {workflowJourney,type JourneyNode} from '../data/workflow-journey';
import {workflowStageLabels as labels} from '../data/workflow-stage-labels';
import {OriginalGlassIconOrb as Orb,OriginalGlassPill as Pill} from './original-glass';
import {OriginalGlassPopup} from './original-popup';
import {SemanticIcon,type SemanticIconName} from './semantic-icon';
import {CubeAppIcon} from './evidence-cube';
import {WorkflowUniverse} from './workflow-universe';
import {WorkflowRequestScene} from './workflow-request-scene';
import {WorkflowMorphScene} from './workflow-morph-scene';
import {ToolBrowser} from './tool-browser';
import {useMotion} from './experience';
import {useSceneFocus,triggerIdentity} from './scene-focus';
import './home-flow.css';
import './neon-glass.css';
import './workflow-universe.css';
function ActionReference({action}:{action:string}){const[expanded,setExpanded]=useState(false);return <section><button className="workflow-reference-toggle" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Close':'Inspect'} related actions, tools and worker routes {expanded?'−':'+'}</button>{expanded&&<ToolBrowser key={action} initialMode="actions" initialAction={action}/>}</section>}
type Workflow=typeof workflows[number];
type Detail={chapter:number;node?:JourneyNode;workflow?:Workflow;kind:'scene'|'directory'};
const colors:Record<string,string>={Start:'#87e6bb',Sources:'#72d9f8',Work:'#c5a1ff',Understand:'#82beff',Connect:'#edc580',Continue:'#ee94c9'};
const icons:Record<string,SemanticIconName>={Start:'project',Sources:'sources',Work:'plan',Understand:'checks',Connect:'connections',Continue:'resume'};
const clean=(s:string)=>s.replaceAll('Delta','task').replaceAll('ENV/UOP','operating policy').replaceAll('Root PV','project coordinator').replaceAll('PV root','project-state root');

function JourneyGraph({chapter,paused,onOpen,small=false,gather=0}:{chapter:number;paused:boolean;onOpen:(node?:JourneyNode)=>void;small?:boolean;gather?:number}){
 const graphRef=useRef<HTMLDivElement>(null),[size,setSize]=useState({width:1000,height:650});useLayoutEffect(()=>{const e=graphRef.current;if(!e)return;const ro=new ResizeObserver(()=>setSize({width:e.clientWidth,height:e.clientHeight}));ro.observe(e);return()=>ro.disconnect()},[chapter]);
 if(chapter===0)return <WorkflowRequestScene onOpen={onOpen} paused={paused} gather={gather}/>;
 const base=workflowJourney[chapter],data={...base,nodes:base.nodes.map(n=>({...n,x:50+(n.x-50)*(1-gather),y:50+(n.y-50)*(1-gather)}))},points=new Map(data.nodes.map(n=>[n.id,n]));const centre={x:50,y:50};const point=(id:string)=>id==='centre'?centre:points.get(id)!;
 return <div ref={graphRef} className={'workflow-graph '+(small?'is-compact':'')} data-paused={paused} data-chapter={chapter}>
 <svg className="workflow-wires" viewBox="0 0 1000 800" preserveAspectRatio="none" aria-hidden="true">{data.edges.map(([a,b,label],i)=>{const start=point(a),end=point(b),dx=end.x-start.x,dy=end.y-start.y,len=Math.hypot(dx,dy)||1;const pixelDx=dx*size.width/100,pixelDy=dy*size.height/100,pixelLength=Math.hypot(pixelDx,pixelDy)||1;const orbRadius=(small?22:size.width<450?22:size.width<720?31:38)*(1-gather*.6);const sr=a==='centre'?(small?30:52):orbRadius,er=b==='centre'?(small?30:52):orbRadius;const s={x:start.x+pixelDx/pixelLength*sr/size.width*100,y:start.y+pixelDy/pixelLength*sr/size.height*100},e={x:end.x-pixelDx/pixelLength*er/size.width*100,y:end.y-pixelDy/pixelLength*er/size.height*100};const tangent=(p:{x:number;y:number})=>({x:-(p.y-50),y:(p.x-50)});const ta=tangent(start),tb=tangent(end);const cycle=chapter===2&&a!=='centre'&&b!=='centre';const d=cycle?`M${s.x*10},${s.y*8} C${(s.x+ta.x*.38)*10},${(s.y+ta.y*.38)*8} ${(e.x-tb.x*.38)*10},${(e.y-tb.y*.38)*8} ${e.x*10},${e.y*8}`:`M${s.x*10},${s.y*8} C${(s.x+(e.x-s.x)*.34)*10},${s.y*8-Math.min(18,pixelLength*.08)} ${(e.x-(e.x-s.x)*.34)*10},${e.y*8+Math.min(18,pixelLength*.08)} ${e.x*10},${e.y*8}`;const color=points.get(b)?.color??'#9edcf4';return <g key={i}><motion.path animate={{d}} transition={{duration:paused?0:.8}} stroke={color} strokeWidth="9" opacity=".22" className="workflow-wire-glow"/><motion.path animate={{d}} transition={{duration:paused?0:.8}} stroke={color} data-optical-route strokeWidth="2.1" opacity=".3"/><motion.path animate={{d}} transition={{duration:paused?0:.8}} stroke="#e3f8ff" strokeWidth="2.4" strokeDasharray="3 85" className="workflow-signal" style={{animationDelay:`-${i*.8}s`}}/>{label&&<text x={(s.x+e.x)*5} y={(s.y+e.y)*4-12} textAnchor="middle">{label}</text>}</g>})}</svg>
 <button className="workflow-cube flow-object" data-scene-centre data-detail-name={data.centre} onClick={()=>onOpen()} aria-label={'Explore '+data.centre.toLowerCase()}><Orb size={104} color="#b1d9ff" decorative><CubeAppIcon size={68}/></Orb><span className="workflow-node-name">{data.centre}</span></button>
 <AnimatePresence>{data.nodes.map((n,i)=><motion.button key={n.id} className={'workflow-node flow-object '+(chapter===2?(n.x<30?'label-left':n.x>70?'label-right':n.y<30?'label-above':''):'')} data-detail-name={n.name} aria-label={n.name} aria-haspopup="dialog" initial={{left:'50%',top:'50%',opacity:0,scale:.15}} exit={{left:'50%',top:'50%',opacity:0,scale:.15,pointerEvents:'none'}} animate={{x:'-50%',y:'-50%',left:n.x+'%',top:n.y+'%',opacity:1,scale:1-gather*.6}} transition={{duration:paused?0:.8,ease:[.22,1,.36,1]}} onClick={()=>onOpen(n)} style={{'--node-color':n.color} as CSSProperties}><span className="workflow-node-float" style={{animationDelay:`-${i*.8}s`}}><Orb size={76} color={n.color} decorative><SemanticIcon name={n.icon} size={34}/></Orb></span><span className="workflow-node-name">{n.name}</span></motion.button>)}</AnimatePresence>
 </div>;
}

export function WorkflowJourney(){
 const{paused,toggle}=useMotion(),focus=useSceneFocus();const[chapter,setChapter]=useState(0),[visibleChapter,setVisibleChapter]=useState(0),[progress,setProgress]=useState(0),[compact,setCompact]=useState(false),[sceneUnavailable,setSceneUnavailable]=useState(false),[detail,setDetail]=useState<Detail|null>(null),[query,setQuery]=useState(''),[group,setGroup]=useState('All'),[selected,setSelected]=useState(workflows[0]);const openRef=useRef(false);openRef.current=!!detail;const story=useRef<HTMLDivElement>(null),openerName=useRef<string|null>(null);
 const shown=useMemo(()=>workflows.filter(w=>(group==='All'||w.group===group)&&`${w.title} ${w.example} ${w.outcome}`.toLowerCase().includes(query.toLowerCase())),[query,group]);
 useEffect(()=>{let frame=0;const media=matchMedia('(prefers-reduced-motion: reduce)');const resize=()=>setCompact(media.matches||innerWidth<=1000);resize();media.addEventListener('change',resize);const scroll=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(openRef.current)return;let index=0,position=0;story.current?.querySelectorAll<HTMLElement>('[data-workflow-chapter]').forEach((el,i)=>{const r=el.getBoundingClientRect();if(r.top<innerHeight*.5){index=i;position=i+Math.max(0,Math.min(.999,(innerHeight*.5-r.top)/r.height))}});if(story.current&&story.current.getBoundingClientRect().bottom<innerHeight*.45)index=5;setChapter(index);setProgress(position)})};scroll();window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',resize);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',scroll);window.removeEventListener('resize',resize);media.removeEventListener('change',resize)}},[]);
 const close=useCallback(()=>{setDetail(null);requestAnimationFrame(function restore(_time:number,attempt=0){if(openRef.current||!openerName.current||!document.querySelector('.workflow-page'))return;const candidates=Array.from(document.querySelectorAll<HTMLElement>('[data-detail-name]'));const target=candidates.find(e=>e.dataset.detailName===openerName.current&&e.getBoundingClientRect().width&&getComputedStyle(e).visibility!=='hidden');if(target)target.focus({preventScroll:true});else if(attempt<20)requestAnimationFrame(()=>restore(0,attempt+1))})},[]);
 const openScene=(index:number,node?:JourneyNode)=>{if(!focus.state.active){const trigger=document.activeElement as HTMLElement;openerName.current=trigger?.dataset.detailName??null;focus.open(trigger?.getBoundingClientRect(),trigger?.closest('.workflow-floating-scene,.workflow-inline-scene')?.getBoundingClientRect()??document.querySelector('[data-scene-centre]')?.getBoundingClientRect())}focus.select(node?.id??'workflow-chapter-'+index,triggerIdentity(document.activeElement));setDetail({chapter:index,node,kind:'scene'})};
 const openWorkflow=(workflow:Workflow)=>{if(!focus.state.active){const trigger=document.activeElement as HTMLElement;openerName.current=trigger?.dataset.detailName??null;focus.open(trigger?.getBoundingClientRect())}setSelected(workflow);focus.select(workflow.id,triggerIdentity(document.activeElement));setDetail(d=>({chapter:d?.chapter??Math.min(chapter,4),workflow,kind:d?.kind??'directory'}))};
 useEffect(()=>{if(detail){const el=document.querySelector('.flowPopupScroll');if(el)el.scrollTop=0}},[detail]);
 const subject=detail?.workflow??(detail?.node?workflows.find(w=>w.id===detail.node!.workflow):undefined);const chapterData=workflowJourney[detail?.chapter??0];const title=detail?.workflow?.title??detail?.node?.name??chapterData.name;const description=detail?.workflow?.outcome??detail?.node?.description??chapterData.detail;const color=detail?.node?.color??(subject?colors[subject.group]:'#b1d9ff');
 const still=compact||sceneUnavailable;const companion=detail?<div className={'workflow-detail-companion '+(detail.kind==='directory'||still?'is-directory':'')} data-detail-companion style={{left:compact?'50%':focus.state.dock.x*100+'%',top:compact?'auto':focus.state.dock.y*100+'%'}}>{detail.kind==='scene'&&still?<nav aria-label="Current flow details"><Pill onClick={()=>openScene(detail.chapter)} leading={<Orb size={30} decorative><CubeAppIcon size={22}/></Orb>}>{workflowJourney[detail.chapter].name}</Pill>{workflowJourney[detail.chapter].nodes.map(n=><Pill key={n.id} onClick={()=>openScene(detail.chapter,n)} leading={<Orb size={30} color={n.color} decorative><SemanticIcon name={n.icon} size={19}/></Orb>}>{n.name}</Pill>)}</nav>:detail.kind==='scene'?<WorkflowMorphScene progress={detail.chapter} paused={paused} small onUnavailable={()=>setSceneUnavailable(true)} onOpen={openScene}/>:<nav aria-label="Workflow choices">{shown.map(w=><Pill key={w.id} active={subject?.id===w.id} leading={<Orb size={30} color={colors[w.group]} decorative><SemanticIcon name={icons[w.group]}/></Orb>} onClick={()=>openWorkflow(w)}>{w.title}</Pill>)}</nav>}</div>:undefined;
 const go=(index:number)=>{const target=document.querySelector('#workflow-chapter-'+index+' .workflow-copy');if(target){const offset=(document.querySelector('.site-header')?.getBoundingClientRect().height??116)+28;window.scrollTo({top:target.getBoundingClientRect().top+scrollY-offset,behavior:paused?'instant':'smooth'})}};
 const rawBlend=chapter<4?Math.max(0,Math.min(1,((progress%1)-.65)/.35)):0;const blend=rawBlend*rawBlend*(3-2*rawBlend);
 return <div className="home-flow workflow-page" data-static={still} data-motion-paused={paused}>
 <WorkflowUniverse/><div className="workflow-story" ref={story}>
 {!still&&chapter<5&&!detail&&<div className="workflow-floating-scene workflow-persistent-scene" data-scroll-progress={progress.toFixed(3)}><WorkflowMorphScene progress={progress} paused={paused} onChapterView={setVisibleChapter} onUnavailable={()=>setSceneUnavailable(true)} onOpen={openScene}/></div>}
 <nav className="workflow-story-rail" aria-label="Workflow story">{workflowJourney.map((c,i)=><a key={c.name} href={'#workflow-chapter-'+i} onClick={e=>{e.preventDefault();go(i)}} aria-label={String(i).padStart(2,'0')+' '+c.name} aria-current={chapter<5&&(still?chapter:visibleChapter)===i?'step':undefined}><span>{String(i).padStart(2,'0')}</span><b>{c.name}</b></a>)}<a href="#workflow-directory" aria-label="05 All workflows" aria-current={chapter===5?'step':undefined}><span>05</span><b>All workflows</b></a></nav>
 {workflowJourney.map((c,i)=><section className="workflow-chapter" id={'workflow-chapter-'+i} data-workflow-chapter key={c.name}><div className="workflow-copy"><p className="flow-kicker">{String(i).padStart(2,'0')} / {c.name.toUpperCase()}</p>{i===0?<h1>{c.heading}<br/><em>{c.accent}</em></h1>:<h2>{c.heading}<br/><em>{c.accent}</em></h2>}<p>{c.body}</p>{i===0?<><form className="workflow-hero-search" onSubmit={e=>{e.preventDefault();setGroup('All');document.getElementById('workflow-directory')?.scrollIntoView({behavior:paused?'instant':'smooth'})}}><label><span aria-hidden="true">⌕</span><input aria-label="Describe the workflow you need" placeholder="Describe what you want to do…" value={query} onChange={e=>setQuery(e.target.value)}/></label><button aria-label="Find matching workflows" type="submit">→</button></form><div className="workflow-search-examples"><span>Try:</span>{['sources','Plan','recovery'].map(q=><button key={q} onClick={()=>{setQuery(q);setGroup('All');document.getElementById('workflow-directory')?.scrollIntoView({behavior:paused?'instant':'smooth'})}}>{q==='sources'?'Bring sources':q==='Plan'?'Change the Plan':'Recover work'}</button>)}</div><p className="workflow-hint">24 distinct workflows · Search by what you want to do</p></>:<p className="workflow-hint">Open an orb for its detail. Open the centre for this flow’s connections.</p>}</div>{i===0&&<nav className="workflow-capability-links" aria-label="Explore the connected capabilities">{([{label:'Skills',hint:'Choose an intent',href:'#workflow-directory',icon:'workflow',color:'#be9aff'},{label:'Actions',hint:'Typed operations',href:'/integrations#capability-library',icon:'api',color:'#82e2bd'},{label:'Tools',hint:'Selected capability',href:'/integrations#capability-library',icon:'tools',color:'#eec17e'},{label:'Hooks',hint:'Visible events',href:'/how-it-works#how-it-works-3',icon:'records',color:'#a8bcf6'},{label:'Evidence',hint:'Inspect the result',href:'/product',icon:'results',color:'#7bd8ed'}] as const).map(item=><Link key={item.label} href={item.href}><Orb size={36} color={item.color} decorative><SemanticIcon name={item.icon} size={21}/></Orb><span><strong>{item.label}</strong><small>{item.hint}</small></span></Link>)}</nav>}{still&&<div className="workflow-inline-scene"><JourneyGraph chapter={i} paused={paused} onOpen={n=>openScene(i,n)}/></div>}</section>)}
 </div>
 <section className="workflow-directory" id="workflow-directory"><header><p className="flow-kicker">05 / CHOOSE THE WORKFLOW</p><h2>What would you like<br/><em>to move forward?</em></h2><p>Explore each workflow’s purpose, representative stages, inspectable result and limits.</p></header><div className="workflow-browser"><label className="workflow-search-field"><span aria-hidden="true">⌕</span><input type="search" aria-label="Find a workflow" placeholder="Try sources, memory, connections or recovery…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="workflow-categories" aria-label="Filter workflows">{['All',...Object.keys(colors)].map(g=><button key={g} aria-pressed={group===g} style={{'--category-color':colors[g]??'#b2d4e8'} as CSSProperties} onClick={()=>setGroup(g)}>{g}</button>)}</div><p role="status" className="workflow-match-count">{shown.length} of 24 workflows</p><div className="workflow-directory-layout"><div className="workflow-choices" data-detail-group>{shown.map(w=><Pill key={w.id} active={selected.id===w.id} data-detail-action={w.id} data-detail-name={w.title} leading={<Orb size={40} color={colors[w.group]} decorative><SemanticIcon name={icons[w.group]} size={22}/></Orb>} onClick={()=>{setSelected(w)}} onDoubleClick={()=>openWorkflow(w)}><small>{w.group}</small>{w.title}</Pill>)}{!shown.length&&<div className="workflow-empty"><h3>No matching workflow</h3><button onClick={()=>{setQuery('');setGroup('All')}}>Reset search and filters</button></div>}</div><aside className="workflow-selected" style={{'--node-color':colors[selected.group]} as CSSProperties}><Orb size={64} color={colors[selected.group]} decorative><SemanticIcon name={icons[selected.group]} size={32}/></Orb><p className="flow-kicker">SELECTED WORKFLOW</p><h3>{selected.title}</h3><p>{selected.outcome}</p><ol>{selected.stages.map((s,i)=><li key={s.action+i}><span>{i+1}</span><strong>{labels[s.action]??s.action.replaceAll('_',' ')}</strong></li>)}</ol><Pill leading={<Orb size={30} color={colors[selected.group]} decorative><SemanticIcon name={icons[selected.group]}/></Orb>} onClick={()=>openWorkflow(selected)}>Open workflow details ↗</Pill><p className="workflow-note">Representative stages. Your request determines branches and prerequisites. This is not a live run.</p></aside></div></div></section>
 <section className="workflow-finish"><p className="flow-kicker">START WITH THE INTENT</p><h2>You describe the work.<br/><em>The workflow supplies the structure.</em></h2><p>Codex uses the appropriate first-class workflow. The engine checks the project, current state and required tools before work runs.</p><Link href="/how-it-works">See how the work runs ↗</Link></section><div className="flow-controls"><button onClick={toggle} aria-pressed={paused}>{paused?'Play motion':'Pause motion'}</button></div>
 <OriginalGlassPopup open={!!detail} onClose={close} panelId="workflow-detail" labelledBy="workflow-detail-title" companion={companion}><div className="workflow-detail-content" style={{'--node-color':color} as CSSProperties}><header className="workflow-detail-heading"><Orb size={76} color={color} decorative>{detail?.node?<SemanticIcon name={detail.node.icon} size={36}/>:subject?<SemanticIcon name={icons[subject.group]} size={36}/>:<CubeAppIcon size={50}/>}</Orb><div><p className="flow-kicker">{subject?'WORKFLOW / '+subject.group.toUpperCase():'EVIDENCE LANE / '+chapterData.centre}</p><h2 id="workflow-detail-title">{title}</h2><p>{description}</p></div></header>{subject?<><section><h3>{detail?.node?'Its owning workflow: '+subject.title:'What happens'}</h3><ol className="workflow-detail-stages">{subject.stages.map((s,i)=><li key={s.action+i}><strong><span>{String(i+1).padStart(2,'0')}</span>{labels[s.action]??s.action.replaceAll('_',' ')}</strong><p>{clean(s.description)}</p><small>{s.mutates?'Changes state within its authorized scope':'Reads current evidence'}</small></li>)}</ol></section><section><h3>What you can inspect</h3><p>{subject.outcome}</p><p className="workflow-detail-boundary">{subject.limitation}</p></section><ActionReference action={subject.stages[0]?.action??"workflow_catalog"}/><section><h3>Example request</h3><blockquote>{subject.example}</blockquote><p className="workflow-note">Use this intention in Codex with the selected project and sources. Exploring this guide submits no command.</p></section></>:<section><h3>Follow the connections</h3><div className="workflow-connection-list">{chapterData.edges.map(([a,b,label])=><p key={a+b}><strong>{a==='centre'?'Evidence Lane':chapterData.nodes.find(n=>n.id===a)?.name} → {b==='centre'?'Evidence Lane':chapterData.nodes.find(n=>n.id===b)?.name}</strong>{label&&<span>{label}</span>}</p>)}</div><p>Open an individual orb to inspect its role, owning workflow and practical request.</p></section>}</div></OriginalGlassPopup>
 </div>;
}
