'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import type * as Three from 'three';
import {workflowJourney,type JourneyNode} from '../data/workflow-journey';
import {OriginalGlassIconOrb as Orb} from './original-glass';
import {SemanticIcon} from './semantic-icon';
import {CubeAppIcon} from './evidence-cube';

type Props={progress:number;paused:boolean;small?:boolean;onChapterView?:(chapter:number)=>void;onUnavailable?:()=>void;onOpen:(chapter:number,node?:JourneyNode)=>void};
type Point={x:number;y:number};
const smooth=(v:number)=>{const t=Math.max(0,Math.min(1,v));return t*t*(3-2*t)};
const centres:Point[]=[{x:26,y:50},{x:50,y:50},{x:50,y:50},{x:54,y:35},{x:41,y:44}];
const arrangements:Point[][]=[[],[],[],[{x:10,y:35},{x:32,y:35},{x:83,y:35},{x:66,y:77},{x:88,y:77}],[{x:12,y:44},{x:71,y:19},{x:77,y:65},{x:34,y:82},{x:90,y:87}]];
const descriptions=['','Read evidence and answer the question.','Attributed answers, options and limits.','Checkpoint and revise affected work.','Preserve completed history.','Run the eligible task with its tools.','Verify before the next task.'];

/** One camera, one ribbon pool and one node pool for the complete scroll story. */
export function WorkflowMorphScene(props:Props){
 const mount=useRef<HTMLDivElement>(null),canvas=useRef<HTMLDivElement>(null),buttons=useRef<(HTMLButtonElement|null)[]>([]),centreButton=useRef<HTMLButtonElement>(null),live=useRef(props);live.current=props;
 const[view,setView]=useState(Math.min(4,Math.floor(props.progress))),[ready,setReady]=useState(false);const readyRef=useRef(false);const viewRef=useRef(view);const data=workflowJourney[view];
 useEffect(()=>{const host=mount.current,canvasHost=canvas.current;if(!host||!canvasHost)return;let gone=false,dispose=()=>{};
 Promise.all([import('three'),import('three/examples/jsm/environments/RoomEnvironment.js')]).then(([T,{RoomEnvironment}])=>{if(gone)return;let renderer:Three.WebGLRenderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'})}catch{live.current.onUnavailable?.();return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.23;renderer.setClearColor(0,0);canvasHost.append(renderer.domElement);const lost=(event:Event)=>{event.preventDefault();live.current.onUnavailable?.()};renderer.domElement.addEventListener('webglcontextlost',lost);
 const scene=new T.Scene(),root=new T.Group(),camera=new T.OrthographicCamera(-5,5,4,-4,.1,70);camera.position.z=20;scene.add(root);const room=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;scene.environmentIntensity=1.75;room.dispose();pmrem.dispose();scene.add(new T.HemisphereLight(0xc8ebff,0x201438,2));const key=new T.DirectionalLight(0xe8f8ff,4),rim=new T.DirectionalLight(0xb5a0ff,3);key.position.set(-3,4,6);rim.position.set(5,-2,3);scene.add(key,rim);
 const material=new T.MeshPhysicalMaterial({color:0xc9dce9,metalness:.58,roughness:.17,clearcoat:1,clearcoatRoughness:.07,transparent:true,opacity:.64,side:T.DoubleSide,depthWrite:false}),coreMaterial=new T.MeshPhysicalMaterial({color:0xe4edf6,metalness:.76,roughness:.14,clearcoat:1,transparent:true,opacity:.86,side:T.DoubleSide,depthWrite:false});
 const segments=88,strands=5,edgeCount=8;
 const ribbons=Array.from({length:edgeCount},()=>Array.from({length:strands},(_,strand)=>{const positions=new Float32Array((segments+1)*6),normals=new Float32Array(positions.length),indices=[];for(let j=0;j<segments;j++){const n=j*2;indices.push(n,n+1,n+2,n+1,n+3,n+2)}const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(positions,3));geometry.setAttribute('normal',new T.BufferAttribute(normals,3));geometry.setIndex(indices);const mesh=new T.Mesh(geometry,strand===2?coreMaterial:material);mesh.frustumCulled=false;root.add(mesh);return{mesh,geometry,positions,normals}}));
 const beadGeometry=new T.SphereGeometry(.018,8,6),beadMaterial=new T.MeshBasicMaterial({color:0xc5e8ff,transparent:true,opacity:.8});const beads=Array.from({length:edgeCount*2},()=>{const mesh=new T.Mesh(beadGeometry,beadMaterial);root.add(mesh);return mesh});
 let width=1,height=1,frame=0,last=0,time=0,displayProgress=Math.max(0,Math.min(4.999,live.current.progress)),yaw=0,pitch=0,shownYaw=0,shownPitch=0,drag=false,lastX=0,lastY=0;
 const resize=()=>{width=Math.max(1,host.clientWidth);height=Math.max(1,host.clientHeight);renderer.setSize(width,height,false)};const ro=new ResizeObserver(resize);ro.observe(host);resize();
 const down=(e:PointerEvent)=>{if(live.current.paused||innerWidth<=1000||(e.target instanceof Element&&e.target.closest('button,a,input')))return;drag=true;lastX=e.clientX;lastY=e.clientY;host.setPointerCapture(e.pointerId)};
 const move=(e:PointerEvent)=>{if(!drag)return;yaw=Math.max(-.2,Math.min(.2,yaw+(e.clientX-lastX)*.001));pitch=Math.max(-.14,Math.min(.14,pitch-(e.clientY-lastY)*.0008));lastX=e.clientX;lastY=e.clientY};const up=()=>{drag=false};const reset=()=>{drag=false;yaw=0;pitch=0};host.addEventListener('pointerdown',down);host.addEventListener('pointermove',move);host.addEventListener('pointerup',up);host.addEventListener('pointercancel',up);window.addEventListener('scroll',reset,{passive:true});
 const vector=(p:Point)=>new T.Vector3((p.x-50)/10,(50-p.y)*.08,0);
 const layout=(chapter:number)=>{const c=centres[chapter];const nodes=workflowJourney[chapter].nodes.map((n,i)=>{let point=arrangements[chapter][i]??{x:n.x,y:n.y};if(chapter===0){if(i===0)point={x:8,y:50};else{const row=Math.floor((i-1)/2),choice=i%2===1;const radius=live.current.small?(choice?15:14):width<800?(choice?23:19):(choice?32:26.5);point={x:(choice?40:73.5)+(10+radius)/width*100,y:18+row*32}}}return{...n,...point}});return{chapter,centre:c,nodes}};
 type Layout=ReturnType<typeof layout>;
 const centreRadius=()=>live.current.small?30:52;const radius=(l:Layout,index:number)=>l.chapter===0?(index===0?(live.current.small?22:width<800?39:48):live.current.small?15:width<800?23:32):(live.current.small?22:innerWidth<=1300?31:38);
 const curve=(l:Layout,edgeIndex:number)=>{const edge=workflowJourney[l.chapter].edges[edgeIndex];if(!edge){const p=vector(l.centre);return new T.CubicBezierCurve3(p,p.clone(),p.clone(),p.clone())}const indexA=l.nodes.findIndex(n=>n.id===edge[0]),indexB=l.nodes.findIndex(n=>n.id===edge[1]);const a=indexA<0?l.centre:l.nodes[indexA],b=indexB<0?l.centre:l.nodes[indexB];const start=vector(a),end=vector(b);const dx=(b.x-a.x)*width/100,dy=(b.y-a.y)*height/100,len=Math.max(1,Math.hypot(dx,dy));const ra=indexA<0?centreRadius():radius(l,indexA),rb=indexB<0?centreRadius():radius(l,indexB);const trim=Math.min(1,len/Math.max(1,ra+rb+12));start.x+=dx/len*ra*trim/width*10;start.y-=dy/len*ra*trim/height*8;end.x-=dx/len*rb*trim/width*10;end.y+=dy/len*rb*trim/height*8;const h1=start.clone(),h2=end.clone();if(l.chapter===2){const va=new T.Vector3(-(a.y-50)/10,-(a.x-50)*.08,0),vb=new T.Vector3(-(b.y-50)/10,-(b.x-50)*.08,0);h1.addScaledVector(va,.38);h2.addScaledVector(vb,-.38)}else{const distance=start.distanceTo(end);const bend=Math.min(.34,distance*.2);h1.lerp(end,.35);h2.lerp(start,.35);h1.y+=bend;h2.y-=bend;if(l.chapter===4&&edge[0]==='uncertain'){h1.x-=1.2;h2.x-=1.2}if(l.chapter===4&&edge[1]==='close'){h1.set(-.7,-2.6,0);h2.set(1.7,-3.2,0)}}return new T.CubicBezierCurve3(start,h1,h2,end)};
 const aPoint=new T.Vector3(),bPoint=new T.Vector3(),point=new T.Vector3(),nextPoint=new T.Vector3(),projected=new T.Vector3();let currentCurves:Three.CubicBezierCurve3[]=[];let nextCurves:Three.CubicBezierCurve3[]=[];let mix=0;
 const put=(element:HTMLElement,p:Three.Vector3)=>{projected.copy(p).applyMatrix4(root.matrixWorld).project(camera);element.style.left=`${(projected.x*.5+.5)*width}px`;element.style.top=`${(-projected.y*.5+.5)*height}px`};
 const tick=(now:number)=>{frame=requestAnimationFrame(tick);if(document.hidden||host.getBoundingClientRect().bottom<0||host.getBoundingClientRect().top>innerHeight){last=now;return}const dt=Math.min(.04,Math.max(.001,(now-last)/1000));if(now-last<16)return;last=now;const state=live.current;if(!state.paused)time+=dt;const target=Math.max(0,Math.min(4.999,state.progress));displayProgress=state.paused?target:displayProgress+(target-displayProgress)*(1-Math.exp(-dt*10));if(Math.abs(target-displayProgress)<.0001)displayProgress=target;const chapter=Math.min(4,Math.floor(displayProgress)),next=Math.min(4,chapter+1);mix=chapter===4?0:smooth(((displayProgress%1)-.55)/.45);const a=layout(chapter),b=layout(next),visibleStage=mix<.5?chapter:next;if(viewRef.current!==visibleStage){viewRef.current=visibleStage;setView(visibleStage);live.current.onChapterView?.(visibleStage)}currentCurves=Array.from({length:edgeCount},(_,i)=>curve(a,i));nextCurves=Array.from({length:edgeCount},(_,i)=>curve(b,i));shownYaw+=(yaw-shownYaw)*.16;shownPitch+=(pitch-shownPitch)*.16;root.rotation.set(shownPitch,shownYaw,0);root.updateMatrixWorld(true);host.dataset.progress=displayProgress.toFixed(3);host.dataset.morph=mix.toFixed(3);host.style.setProperty('--phase-visibility',String(Math.pow(Math.abs(mix-.5)*2,2)));host.dataset.manualRotation=(Math.abs(shownYaw)+Math.abs(shownPitch)).toFixed(4);key.position.set(-3+Math.sin(time*.32)*1.5,4+Math.cos(time*.26),6);rim.position.x=4+Math.cos(time*.21)*2;
 for(let i=0;i<edgeCount;i++){for(let strand=0;strand<strands;strand++){const ribbon=ribbons[i][strand];for(let j=0;j<=segments;j++){const t=j/segments;currentCurves[i].getPoint(t,aPoint);nextCurves[i].getPoint(t,bPoint);point.copy(aPoint).lerp(bPoint,mix);currentCurves[i].getPoint(Math.min(1,t+.006),aPoint);nextCurves[i].getPoint(Math.min(1,t+.006),bPoint);nextPoint.copy(aPoint).lerp(bPoint,mix);const dx=nextPoint.x-point.x,dy=nextPoint.y-point.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,envelope=Math.sin(Math.PI*t),spread=(strand-2)*.034*envelope,wave=Math.sin(t*9-time*.65+strand*.2)*.012*envelope,half=(strand===2?.022:.007)*(.35+.65*envelope),twist=Math.sin(t*6.28+time*.4+strand*.3)*.2;for(let side=0;side<2;side++){const k=j*6+side*3,offset=spread+wave+(side?half:-half);ribbon.positions[k]=point.x+nx*offset;ribbon.positions[k+1]=point.y+ny*offset;ribbon.positions[k+2]=Math.sin(t*5+time*.35+strand*.5)*.08*envelope;ribbon.normals[k]=nx*Math.sin(twist);ribbon.normals[k+1]=ny*Math.sin(twist);ribbon.normals[k+2]=Math.cos(twist)}}ribbon.geometry.attributes.position.needsUpdate=true;ribbon.geometry.attributes.normal.needsUpdate=true;}for(let j=0;j<2;j++){const t=(time*.12+i*.13+j*.5)%1;currentCurves[i].getPoint(t,aPoint);nextCurves[i].getPoint(t,bPoint);beads[i*2+j].position.copy(aPoint).lerp(bPoint,mix);beads[i*2+j].visible=Boolean(workflowJourney[chapter].edges[i]||workflowJourney[next].edges[i])}}
 const centre=centreButton.current;if(centre){point.copy(vector(a.centre)).lerp(vector(b.centre),mix);put(centre,point)}
 for(let i=0;i<7;i++){const button=buttons.current[i];if(!button)continue;const na=a.nodes[i],nb=b.nodes[i],opacity=(na?1-mix:0)+(nb?mix:0);point.copy(vector(na??a.centre)).lerp(vector(nb??b.centre),mix);put(button,point);button.style.opacity=String(opacity);button.style.pointerEvents=opacity>.85?'auto':'none';button.style.visibility=opacity<.01?'hidden':'visible';button.setAttribute('aria-hidden',String(opacity<.1));button.tabIndex=opacity>.85?0:-1;const label=button.querySelector<HTMLElement>('.morph-node-text');if(label)label.style.opacity=String(mix===0||mix===1?1:Math.pow(Math.abs(mix-.5)*2,2));const payload=button.querySelector<HTMLElement>('.original-glass-orb__payload');if(payload)payload.style.opacity=String(.15+.85*Math.abs(mix-.5)*2)}
 if(!readyRef.current){readyRef.current=true;setReady(true)}renderer.render(scene,camera)};frame=requestAnimationFrame(tick);
 dispose=()=>{cancelAnimationFrame(frame);ro.disconnect();host.removeEventListener('pointerdown',down);host.removeEventListener('pointermove',move);host.removeEventListener('pointerup',up);host.removeEventListener('pointercancel',up);window.removeEventListener('scroll',reset);for(const group of ribbons)for(const r of group)r.geometry.dispose();material.dispose();coreMaterial.dispose();beadGeometry.dispose();beadMaterial.dispose();environment.dispose();renderer.domElement.removeEventListener('webglcontextlost',lost);renderer.dispose();renderer.domElement.remove()};
 }).catch(()=>{if(!gone)live.current.onUnavailable?.()});return()=>{gone=true;dispose()};
 },[]);
 return <div className={'workflow-morph-scene '+(props.small?'is-small':'')} ref={mount} data-detail-companion data-view-chapter={view} data-ready={ready}><div className="workflow-morph-canvas" ref={canvas} aria-hidden="true"/><button ref={centreButton} className="morph-centre flow-object" data-scene-centre data-detail-name={data.centre} title={data.centre} aria-label={'Explore '+data.centre.toLowerCase()} onClick={()=>props.onOpen(view)}><Orb size={props.small?60:104} color="#99d8ff" decorative><CubeAppIcon size={props.small?40:70}/></Orb><span>{data.centre}</span></button>{Array.from({length:7},(_,i)=>{const node=data.nodes[i];const isCard=view===0&&i>0;const side=view===2&&node?(node.x<30?'label-left':node.x>70?'label-right':node.y<30?'label-above':''):'';return <button key={i} ref={e=>{buttons.current[i]=e}} className={'morph-node flow-object '+(isCard?(i%2?'choice-card':'outcome-card'):side)} data-detail-name={node?.name} aria-label={node?.name} aria-haspopup="dialog" onClick={()=>node&&props.onOpen(view,node)} style={{'--node-color':node?.color??'#9bd7ee'} as CSSProperties}>{node&&<><Orb size={props.small?44:isCard?(i%2?64:53):view===0?96:76} color={node.color} decorative><SemanticIcon name={node.icon} size={props.small?24:34}/></Orb><span className="morph-node-text"><strong>{node.name}</strong>{isCard&&<small>{descriptions[i]}</small>}</span></>}</button>})}</div>;
}
