'use client';
import {useId} from 'react';
import {OriginalGlassIconOrb as Orb} from './original-glass';
import {SemanticIcon,type SemanticIconName} from './semantic-icon';
import {CubeAppIcon} from './evidence-cube';
import type {JourneyNode} from '../data/workflow-journey';
const subjects:JourneyNode[]=[
 {id:'intent',name:'Your request',icon:'chat',color:'#c499ff',x:0,y:0,workflow:'classify-project-work',description:'Clarify the request and selected project context. Interpretation chooses a route; it does not grant permission to execute.'},
 {id:'ask',name:'Ask',icon:'chat',color:'#71ddff',x:0,y:0,workflow:'evidence-lane',description:'Read bounded project evidence to answer the question. Informational reads keep the Plan unchanged.'},
 {id:'read-return',name:'Read-only return',icon:'records',color:'#a8a5ff',x:0,y:0,workflow:'retrieve-project-evidence',description:'Return an attributed answer, with the source coverage and remaining uncertainty visible. A read does not refresh the source.'},
 {id:'revise',name:'Revise',icon:'plan',color:'#80e4bc',x:0,y:0,workflow:'manage-project-plan',description:'Record the semantic change and checkpoint affected work before replacing the affected active or queued task contracts.'},
 {id:'checkpoint',name:'Plan checkpoint',icon:'checks',color:'#83e6cc',x:0,y:0,workflow:'manage-project-plan',description:'An idle task needs an engine checkpoint; admitted work must reach its own safe boundary. Preserve completed task history.'},
 {id:'execute',name:'Execute',icon:'work',color:'#efbe72',x:0,y:0,workflow:'execute-project-plan',description:'Admit the exact next eligible task with the current revision, source route, grants, ready tools and acceptance checks.'},
 {id:'loop',name:'Work loop',icon:'resume',color:'#efbf78',x:0,y:0,workflow:'execute-project-plan',description:'Carry out bounded work, verify its output, record the exit evidence and continue the next eligible task. Failed or uncertain effects need recovery.'}
];
export function WorkflowRequestScene({onOpen,paused,gather=0}:{onOpen:(node?:JourneyNode)=>void;paused:boolean;gather?:number}){const id=useId().replaceAll(':','');const paths=['M105 250 C155 250 175 250 220 250','M300 226 C360 226 340 90 410 90','M300 250 C355 250 370 250 410 250','M300 274 C355 274 350 410 410 410','M625 90 C665 90 680 90 718 90','M625 250 C665 250 680 250 718 250','M625 410 C665 410 680 410 718 410'];return <div className="workflow-request-scene" data-detail-companion data-paused={paused} style={{transform:`perspective(1400px) rotateX(var(--scene-rotate-x,0deg)) rotateY(var(--scene-rotate-y,0deg)) scale(${1-gather*.65})`,transformOrigin:'26% 50%'}}>
 <svg viewBox="0 0 1000 500" preserveAspectRatio="none" aria-hidden="true"><defs><filter id={'glow'+id} x="-50%" y="-100%" width="200%" height="300%"><feGaussianBlur stdDeviation="4"/></filter><marker id={'arrow'+id} markerWidth="9" markerHeight="9" refX="7" refY="4.5" orient="auto"><path d="M0 0 L8 4.5 L0 9 L2 4.5Z" fill="#dcf7ff"/></marker></defs>{paths.map((d,i)=>{const color=['#c499ff','#71ddff','#80e4bc','#efbe72','#8ddfff','#87e8c5','#efbe72'][i];return <g key={d}><path d={d} fill="none" stroke={color} strokeWidth="12" opacity=".26" filter={`url(#glow${id})`}/><path d={d} fill="none" stroke={color} data-optical-route strokeWidth="3" opacity=".3"/><path d={d} fill="none" stroke="#f4fbff" strokeWidth="1.25" markerEnd={`url(#arrow${id})`}/><circle r="3.8" fill="#fff" style={{filter:`drop-shadow(0 0 5px ${color})`}}>{!paused&&<animateMotion dur={`${3.6+i*.28}s`} repeatCount="indefinite" path={d}/>}</circle></g>})}</svg>
 <button className="request-origin flow-object" data-detail-name="Your request" onClick={()=>onOpen(subjects[0])}><Orb size={96} color="#be8eff" decorative><SemanticIcon name="chat" size={42}/></Orb><strong>Your request</strong></button>
 <button className="request-brand flow-object" data-scene-centre data-detail-name="The request route" aria-label="Explore the request route" onClick={()=>onOpen()}><Orb size={112} color="#79cdff" decorative><CubeAppIcon size={76}/></Orb></button>
 {[0,1,2].map(i=><div className={'request-branch request-branch-'+i} key={i}><button className="request-choice flow-object" data-detail-name={subjects[i*2+1].name} onClick={()=>onOpen(subjects[i*2+1])} style={{'--branch-color':subjects[i*2+1].color} as React.CSSProperties}><Orb size={78} color={subjects[i*2+1].color} decorative><SemanticIcon name={subjects[i*2+1].icon as SemanticIconName} size={35}/></Orb><span><strong>{subjects[i*2+1].name}</strong><small>{['Read evidence and answer the question.','Checkpoint and revise the affected work.','Run the eligible task with its tools.'][i]}</small></span></button><button className="request-outcome flow-object" data-detail-name={subjects[i*2+2].name} onClick={()=>onOpen(subjects[i*2+2])} style={{'--branch-color':subjects[i*2+2].color} as React.CSSProperties}><Orb size={53} color={subjects[i*2+2].color} decorative><SemanticIcon name={subjects[i*2+2].icon} size={27}/></Orb><span><strong>{subjects[i*2+2].name}</strong><small>{['Attributed answers, options and limits.','Preserve completed history.','Verify before moving to the next task.'][i]}</small></span></button></div>)}
 </div>}
