"""Curated user explanations mapped to the inspected public action registry."""
import json
from pathlib import Path
APP=Path(__file__).resolve().parents[1]
backend=json.loads((APP/'app/data/backend.json').read_text())
# id | title | group | example | product outcome | concrete limitation | actual representative stages
rows='''evidence-lane|Explore a project|Understand|Show what this project contains and where work stands.|A bounded view of the current Plan, sources and recorded evidence.|A read does not refresh changed files or prove that a tool ran.|workflow_catalog,render_project_panel,lane_search
open-project-session|Open or resume a project|Start|Resume my selected project and show the current Plan.|A checked session with its exact project and saved context.|A missing native identity or mismatched saved session remains unresolved.|client_context,runtime_doctor,session_status,session_resume
execute-project-plan|Carry out the next task|Work|Continue the next eligible task and show its output and checks.|A bounded job, addressed output and recorded verification result.|A queued or failed job is not complete; changed task contracts require a Plan update.|plan_read,delta_enter_planned,delta_status
manage-project-plan|Create or update the Plan|Work|Change the next task to produce a spreadsheet while preserving completed work.|One current ordered Plan with explicit scope and acceptance checks.|A steer waits for an active job to reach a safe boundary; it cannot rewrite completed history.|plan_read,steer_preview,steer_submit,plan_refresh
manage-project-sources|Bring in project sources|Sources|Register this folder and prepare the documents and spreadsheets for my project.|An ordered source record and bounded tasks for the selected files.|Registration is not indexing. Parser coverage and current file checks are reported separately.|source_classify,source_register,source_prepare_tasks,source_materialize
exchange-task-evidence|Exchange evidence between tasks|Connect|Send this result to the selected task under its stated input requirements.|An attributed packet with sender, receiver and input or return contract.|A sealed outgoing packet is not proof of receipt. Receiver acceptance remains separately owned.|task_evidence_expect,task_evidence_send,task_evidence_receive,task_evidence_result
manage-project-memory|Recall project context|Understand|Find the evidence behind the last completed task and its decisions.|Bounded project references with their original owners and evidence links.|Memory stores attributed locators; it does not merge source content or prove present-day freshness.|memory_read,memory_checkpoint,memory_rehydrate
manage-project-lessons|Inspect project lessons|Understand|Show lessons from verified work that are relevant to this task.|Project-local lessons with verification provenance and retained revocation history.|Host recall is separate. Referencing host memory does not create a verified lesson.|learning_read,learning_revoke,learning_read
inspect-project-instructions|Understand applicable instructions|Understand|Show the instruction chain for this project folder.|File provenance, override order and separately identified recall sources.|Observed files do not prove what a particular Codex task actually loaded.|instructions_inspect
configure-project-workflow|Shape the project workflow|Start|Use these selected sources to propose a workflow for a research report.|A proposal tying the requested outcome to source types and relevant checks.|A proposal neither changes the Plan nor grants permission to execute.|project_workflow_configure,plan_read
classify-project-work|Clarify the kind of work|Start|Classify this document review and explain its relevant checks.|A classification with suitable source types, work units and validation gates.|Inferred classifications are labeled; classification alone cannot start work.|project_work_classify,toolchain_resolve
retrieve-project-evidence|Fit evidence into context|Understand|Select the most relevant evidence within a 2000-token estimate.|A deterministic selection of attributed references within explicit budgets.|Token counts are estimates. Selection does not fetch or reverify raw source content.|project_evidence_select,lane_fetch
refresh-project-evidence|Refresh changed evidence|Sources|Refresh the selected spreadsheet after these source changes.|Updated selected source snapshots and requested derived views.|Refresh does not automatically parse every source or render every possible view.|source_prepare_refresh,plan_refresh,source_materialize,lane_view_refresh
inspect-project-connectors|Inspect connections|Connect|Show which connectors this project can use and when their grants expire.|Current connector registrations, scope, versions and configured backend references.|Registration is separate from measured execution readiness.|connector_read,toolchain_resolve
configure-project-connector|Configure a connection|Connect|Configure the selected registered adapter for this exact project resource.|A versioned connector definition with bounded actions, targets and expiry.|Saving configuration cannot install an arbitrary adapter or grant project administration.|connector_read,connector_configure,connector_read
revoke-project-connector|Withdraw a connection|Connect|Revoke this project connector and retain its history.|The exact grant is revoked and its historical receipts remain inspectable.|Revocation does not uninstall the provider, remove project data or revoke unrelated grants.|connector_read,connector_revoke,connector_read
select-project-tools|Inspect and select tools|Work|Check which tools can perform this task on my current machine.|A primary route and declared alternatives with measured readiness requirements.|An unavailable tool stays unavailable. Uncertain effects are not silently retried with another tool.|toolchain_catalog,toolchain_resolve,runtime_status
select-project-storage|Choose project storage|Start|Register this source folder with a separate durable project-state folder.|Distinct source and state roots with separately owned project records.|A saved preference does not migrate data. Ephemeral hosts require a verified durable remote route.|storage_connector_inspect,project_register,storage_status
inspect-project-evidence-map|Explore linked evidence|Understand|Show how this project’s sources and tasks relate to its recorded results.|A bounded attributed map with source, task and selected project references.|Links do not grant access; a recorded relationship does not imply current target access.|project_evidence_map_inspect,project_evidence_map_query,project_evidence_links_read
link-project-evidence-network|Link separate projects|Connect|Connect the selected projects through a separate evidence network.|A hash-reference network while each project keeps its own databases and files.|The coordinator is separate from members. Snapshots are not simultaneous freshness guarantees.|project_evidence_network_create,project_evidence_network_register,project_evidence_network_link,project_evidence_network_verify
handoff-project-work|Transfer work to another client|Continue|Transfer this project at a safe boundary to the selected client.|An exact offer, destination acceptance and attributed continuation context.|A title or client label cannot prove native task identity. Missing required attestation stops transfer.|continuation_context,continuation_offer,continuation_accept,session_resume
recover-project-state|Back up or recover a project|Continue|Create and verify a coherent project backup before recovery.|A checked backup of separate records or a fresh recovery destination.|Offline recovery requires a stopped engine. It preserves the original root and never claims failed work succeeded.|project_recovery_inspect,project_backup,project_backup_verify
close-project-session|Close a project session|Continue|Close this session after the current work reaches a safe boundary.|A recorded session closure and detached capture.|Closing a session does not delete data, stop the shared engine or complete a native Goal.|session_status,session_exit,session_status
run-project-lifecycle|Coordinate end-to-end work|Continue|Take this project from selected sources through a Plan to a verified result.|The owning workflows coordinate entry, planning, work, evidence and closure.|Each step retains its own checks and permissions. A lifecycle request cannot bypass a failed gate.|session_boot,plan_read,delta_enter_planned,delta_status,session_exit'''
result=[]
for row in rows.splitlines():
 id,title,group,example,outcome,limit,stages=row.split('|')
 source=next(s for s in backend['skills'] if s['name']==id)
 actions=stages.split(',')
 assert all(a in backend['actions'] for a in actions), (id,actions)
 result.append(dict(id=id,title=title,group=group,example=example,outcome=outcome,limitation=limit,description=source['description'],stages=[dict(action=a,description=backend['actions'][a]['description'],mutates=backend['actions'][a]['mutates']) for a in actions]))
assert {w['id'] for w in result}=={s['name'] for s in backend['skills']}
(APP/'app/data/workflows.json').write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8')
print('24 curated workflows matched to current actions; stage examples are conditional, not live executions.')
