"""Build Home's public knowledge projection from exact current plugin/Studio source; no runtime execution."""
from pathlib import Path
import json,hashlib,re
APP=Path(__file__).resolve().parents[1];ROOT=APP.parents[1];P=ROOT/'plugins/evidence-lane-plugin'
def read(p):return json.loads((P/p).read_text(encoding='utf-8'))
skills=read('skills/skill-surface-registry.v4.json');ops=read('toolchains/operation-toolchains.v4.json');tools=read('toolchains/shared-toolchain.v4.json');lanes=read('authorities/project_sectors/sector-runtime-registry.v4.json');auth=read('authorities/authority-surface-registry.v4.json');bundle=read('provisioning/full-bundle-plan.v4.json');connection=read('manifests/engine-connection.v4.json')
curated=json.loads((APP/'app/data/workflows.json').read_text(encoding='utf-8'));opmap={o['operation']:o for o in ops['operations']}
projection=[]
for s in skills['skills']:
 w=next(w for w in curated if w['id']==s['name']);ids=sorted({t for a in s['actions'] for r in opmap[a]['routes'] for t in r['tool_ids']})
 projection.append({**w,'ownedActions':s['actions'],'toolIds':ids,'actionCount':len(s['actions'])})
source_names={'local_code':'Local code','github_code':'GitHub code','docs':'Word','data_excel':'Excel','data':'Structured data','ppt':'PowerPoint','tableau':'Tableau','power_bi':'Power BI','pdf_ocr':'PDF & OCR','images_ocr':'Images & media','research':'Research & web','artifacts':'Artifacts','custom':'Custom sources / selected SQLite'}
authority_names={'plan':'Plan','chat_lineage':'Conversation history','canon':'Task evidence exchange','memory':'Project Memory','learning':'Learning','sources':'Sources','receipts':'Receipts','universe':'Project evidence map'}
references=['.codex-plugin/plugin.json','skills/skill-surface-registry.v4.json','sdk/workflows/skill-workflow-registry.v4.json','toolchains/operation-toolchains.v4.json','toolchains/shared-toolchain.v4.json','authorities/authority-surface-registry.v4.json','authorities/project_sectors/sector-runtime-registry.v4.json','provisioning/full-bundle-plan.v4.json','manifests/engine-connection.v4.json','studio/engine-api.contract.v4.json','env/orchestration.policy.v4.json','src/evidence_lane_plugin/engine.py','src/evidence_lane_plugin/adaptive_delta_entry.py','src/evidence_lane_plugin/adaptive_delta_exit.py','src/evidence_lane_plugin/session_authority.py','src/evidence_lane_plugin/plan_runtime.py','src/evidence_lane_plugin/source_intake.py','src/evidence_lane_plugin/connector_governance.py','src/evidence_lane_plugin/project_memory.py','src/evidence_lane_plugin/agent_learning.py']
out={'version':read('.codex-plugin/plugin.json')['version'],'counts':{'workflows':len(projection),'operations':len(opmap),'tools':len(tools['entries']),'sourceLanes':len(lanes['implemented_sectors']),'providers':len(tools['provider_environments']),'installComponents':len(bundle['components'])},'qualification':tools['qualification'],'installedReady':tools['full_bundle_ready'],'workflows':projection,'sources':[{'id':x['lane_id'],'title':source_names[x['lane_id']],'manifest':x['manifest']} for x in lanes['implemented_sectors']],'authorities':[{'id':x['authority_id'],'title':authority_names[x['authority_id']],'path':x['path']} for x in auth['authorities'] if x['authority_id'] in authority_names],'technicalSessionOwner':'Session records are Receipts-owned; the sessions source family is not a ninth business authority.','tools':[{'id':t['tool_id'],'kind':t['kind'],'provisioning':t['provisioning_route'],'external':t['external_configuration_required'],'installation':t['installation_state'],'execution':t['adapter_execution_state']} for t in tools['entries']],'operations':{k:{'profile':v['profile'],'routes':[{'id':r['route_id'],'tools':r['tool_ids'],'systems':r['systems'],'provider':r['provider']} for r in v['routes']],'selection':v['selection'],'fallbackAfterInvocation':v['fallback_after_invocation']} for k,v in opmap.items()},'providers':tools['provider_environments'],'platforms':connection['platforms'],'studioPanels':['Plan','Jobs','Workers','Evidence','Toolchains','Connections','Learning','Compute','Diagnostics'],'references':{p:hashlib.sha256((P/p).read_bytes()).hexdigest() for p in references}}
out['references']['apps/evidence-lane-studio/src/App.tsx']=hashlib.sha256((ROOT/'apps/evidence-lane-studio/src/App.tsx').read_bytes()).hexdigest();out['references']['docs/TOOLCHAIN_EXECUTION_MATRIX.md']=hashlib.sha256((ROOT/'docs/TOOLCHAIN_EXECUTION_MATRIX.md').read_bytes()).hexdigest()
assert out['counts']['workflows']==24 and out['counts']['operations']==295 and out['counts']['sourceLanes']==13
(APP/'app/data/home-knowledge.json').write_text(json.dumps(out,indent=2)+'\n',encoding='utf-8')
print(json.dumps(out['counts']));print('Current-source projection written. No engine, installation or project-data actions executed.')
