#!/usr/bin/env python3
"""Refresh every public GitHub document from current plugin backend contracts."""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
import time
from pathlib import Path
from typing import Any

from validate_public_github_docs import ALLOWED_DOCS, PUBLIC_ROOT_DOCS, ROOT, validate

PLUGIN = ROOT / "plugins" / "evidence-lane-plugin"
START = "<!-- EVIDENCE_LANE_CURRENT_BACKEND_START -->"
END = "<!-- EVIDENCE_LANE_CURRENT_BACKEND_END -->"
PUBLIC_DOC_REFRESH_MARKER = (
    "<!-- evidence-lane-public-docs-full-refresh: 3.0.0 / R265-current-route-v3 -->"
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest().upper()


def _json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise TypeError(f"Expected object: {path}")
    return value


def _write_text_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = text.replace("\r\n", "\n").encode("utf-8")
    last_error: OSError | None = None
    for attempt in range(8):
        handle, raw = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
        temporary = Path(raw)
        try:
            with os.fdopen(handle, "wb") as stream:
                stream.write(payload)
                stream.flush()
                os.fsync(stream.fileno())
            os.replace(temporary, path)
            return
        except OSError as exc:
            last_error = exc
            temporary.unlink(missing_ok=True)
            if attempt == 7:
                break
            time.sleep(0.05 * (attempt + 1))
    assert last_error is not None
    raise last_error


def _remove_backend_block(path: Path) -> None:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    if START in text or END in text:
        if text.count(START) != 1 or text.count(END) != 1:
            raise RuntimeError(f"Malformed backend block: {path}")
        before, remainder = text.split(START, 1)
        _, after = remainder.split(END, 1)
        updated = before.rstrip() + "\n\n" + after.lstrip()
    else:
        updated = text
    updated = updated.rstrip()
    if not updated.startswith("<!-- evidence-lane-public-docs-full-refresh:"):
        updated = PUBLIC_DOC_REFRESH_MARKER + "\n\n" + updated
    _write_text_atomic(path, updated + "\n")


def main() -> int:
    validate()
    plugin_manifest_path = PLUGIN / ".codex-plugin" / "plugin.json"
    public_schema_path = PLUGIN / "schemas" / "public-action-schemas.v001.json"
    skill_registry_path = PLUGIN / "skills" / "skill-surface-registry.v1.json"
    hook_path = PLUGIN / "hooks" / "hooks.json"
    sdk_path = PLUGIN / "sdk" / "sdk-manifest.v1.json"
    mcp_path = PLUGIN / "mcp" / "mcp-manifest.v1.json"
    env_path = PLUGIN / "env" / "authority-manifest.v1.json"
    uop_path = PLUGIN / "uop" / "authority-manifest.v1.json"
    tool_matrix_path = PLUGIN / "toolchains" / "TOOLCHAIN_EXECUTION_MATRIX.md"
    plugin_manifest = _json(plugin_manifest_path)
    common_sources = [
        plugin_manifest_path,
        public_schema_path,
        skill_registry_path,
        hook_path,
        sdk_path,
        mcp_path,
        env_path,
        uop_path,
        tool_matrix_path,
    ]
    docs = [ROOT / name for name in sorted(PUBLIC_ROOT_DOCS)] + [
        ROOT / "docs" / name for name in sorted(ALLOWED_DOCS)
    ]
    # GitHub Markdown is owned by generate_github_docs.py. This refresh binds
    # the already-generated bytes to the public backend without maintaining a
    # second renderer or rewriting TOOLS.md after the linked-doc fixed point.
    rows = [
        {
            "path": path.relative_to(ROOT).as_posix(),
            "bytes": path.stat().st_size,
            "sha256": _sha256(path),
        }
        for path in docs
    ]
    body = {
        "schema": "evidence-lane.public-docs-backend-binding.v1",
        "status": "PASS",
        "plugin_version": plugin_manifest["version"],
        "document_count": len(rows),
        "documents": rows,
        "backend_sources": {
            path.relative_to(ROOT).as_posix(): _sha256(path) for path in common_sources
        },
        "historical_internal_source_count": 0,
        "main_merge_authorized": False,
    }
    output = (
        ROOT
        / "apps"
        / "evidence-lane-app"
        / "app"
        / "_data"
        / "public-docs-backend-binding.json"
    )
    _write_text_atomic(output, json.dumps(body, indent=2, ensure_ascii=False) + "\n")
    print(
        json.dumps(
            {
                "status": "PASS",
                "plugin_version": plugin_manifest["version"],
                "documents": len(rows),
                "binding": output.relative_to(ROOT).as_posix(),
                "binding_sha256": _sha256(output),
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
