"""Read only the hash-bound static asset allowlist generated by Studio's build."""
import hashlib
import json
from pathlib import Path, PurePosixPath

from .errors import LaneError
from .storage import reject_links

ROOT = Path(__file__).parent / 'studio'


def static_asset(route):
    manifest = ROOT / 'assets-manifest.json'
    reject_links(manifest, ROOT)
    if manifest.stat().st_size > 65_536:
        raise LaneError('STUDIO_ASSET_MANIFEST_INVALID', 'The Studio build manifest is invalid.')
    document = json.loads(manifest.read_text(encoding='utf-8'))
    if document.get('schema_version') != 1 or not isinstance(document.get('assets'), dict) or len(document['assets']) > 100:
        raise LaneError('STUDIO_ASSET_MANIFEST_INVALID', 'The Studio build manifest is invalid.')
    entry = document['assets'].get(route)
    if entry is None:
        return None
    relative = PurePosixPath(entry['file'])
    if relative.is_absolute() or '..' in relative.parts or any(':' in part or '\\' in part for part in relative.parts):
        raise LaneError('STUDIO_ASSET_MANIFEST_INVALID', 'The static asset path is invalid.')
    path = ROOT.joinpath(*relative.parts)
    reject_links(path, ROOT)
    if path.stat().st_size != entry['bytes'] or not 0 <= entry['bytes'] <= 8_000_000:
        raise LaneError('STUDIO_ASSET_INTEGRITY', 'A Studio asset differs from the verified build.')
    content = path.read_bytes()
    if hashlib.sha256(content).hexdigest() != entry['sha256']:
        raise LaneError('STUDIO_ASSET_INTEGRITY', 'A Studio asset differs from the verified build.')
    return content, entry['content_type']
