export type PluginSurfaceFamily =
  | "Router"
  | "Lifecycle"
  | "Session"
  | "Mode"
  | "Connector"
  | "Storage"
  | "Canon"
  | "Learning"
  | "Memory"
  | "Instructions"
  | "Universe";

export type PluginSurface = {
  id: string;
  label: string;
  command: string;
  family: PluginSurfaceFamily;
  description: string;
  setting: string;
  produces: string;
  boundary: string;
  primaryControl: boolean;
};

export const pluginSurfaces: readonly PluginSurface[] = [
  {
    id: "evi",
    label: "Evi",
    command: "/evi",
    family: "Router",
    description: "Root router for one persistent Evidence Lane project.",
    setting: "Routes to six primary lifecycle controls or a bounded sidecar.",
    produces: "A visible control choice with the current project boundary.",
    boundary: "State Travel is conditional; it is never an automatic seventh control.",
    primaryControl: false,
  },
  {
    id: "evi-additional-plugin",
    label: "Additional plugin",
    command: "/evi-additional-plugin",
    family: "Connector",
    description: "Adds one bounded host connector or AI toolchain grant.",
    setting: "Purpose, role schema, actions, scope, runtime, and expiry are required.",
    produces: "One auditable connector grant.",
    boundary: "The grant cannot change lifecycle state or widen its own scope.",
    primaryControl: false,
  },
  {
    id: "evi-boot",
    label: "Boot",
    command: "/evi-boot",
    family: "Lifecycle",
    description: "Verifies runtime, ENV/UOP Flash, host class, and durable storage.",
    setting: "Resume the existing session when its accepted authority is valid.",
    produces: "A verified session-entry receipt.",
    boundary: "No candidate, Fuse, or accepted-pointer movement.",
    primaryControl: true,
  },
  {
    id: "evi-build",
    label: "Build",
    command: "/evi-build",
    family: "Lifecycle",
    description: "Bootstraps Source-Intake-backed PV0 or governs one dual Project and Learning HIL.",
    setting: "PV0 has no HIL; a full PV HIL requires two exact human decisions for the same derived PV.",
    produces: "PV0 authority or one Plan-stamped Project proposal plus consolidated Learning weave.",
    boundary: "No candidate directory; only the matching dual approval contract may invoke Fuse.",
    primaryControl: true,
  },
  {
    id: "evi-canon",
    label: "Canon",
    command: "/evi-canon",
    family: "Canon",
    description: "Launches or binds governed top-level tasks and authorized subagents, then governs their Canon exchange.",
    setting: "Bind exact task class, scope, direction, receiver, edge, return contract, and native host receipt.",
    produces: "Typed upstream/downstream/lateral envelopes, native dispatch receipts, receiver decisions, results, or bounded backfire.",
    boundary: "Subagents own no HIL; every backfire is receiver-owned three-way Canon HIL, and Canon never promotes Project Truth or moves a pointer.",
    primaryControl: false,
  },
  {
    id: "evidence-lane-code-lifecycle",
    label: "Code lifecycle",
    command: "/evidence-lane-code-lifecycle",
    family: "Router",
    description: "End-to-end Code-mode lifecycle contract for one universal project.",
    setting: "Formula: plan → sandbox build → test → hash → package.",
    produces: "Linear work, executable gates, candidate evidence, and exact HIL.",
    boundary: "One writer; no main merge, pointer movement, or implicit promotion.",
    primaryControl: false,
  },
  {
    id: "evi-drop-additional-plugin",
    label: "Drop additional plugin",
    command: "/evi-drop-additional-plugin",
    family: "Connector",
    description: "Revokes one active connector or AI-toolchain grant.",
    setting: "Select the exact active grant identity.",
    produces: "An append-only revocation receipt.",
    boundary: "Prior connector history and evidence remain immutable.",
    primaryControl: false,
  },
  {
    id: "evi-exit-boot",
    label: "Exit Boot",
    command: "/evi-exit-boot",
    family: "Session",
    description: "Explicitly closes one persistent session and detaches live capture.",
    setting: "Close the exact active session only.",
    produces: "A sealed session-exit receipt.",
    boundary: "Installation and immutable project evidence are retained.",
    primaryControl: false,
  },
  {
    id: "evi-mode",
    label: "Mode",
    command: "/evi-mode",
    family: "Mode",
    description: "Loads ordered ENV/UOP laws for a known or explicit custom mode.",
    setting: "Each mode carries its own formula, operators, gate, accepted object, and rollback target.",
    produces: "A mode-binding receipt and visible formula.",
    boundary: "Mode selection does not create a candidate or move a pointer.",
    primaryControl: true,
  },
  {
    id: "evi-learning",
    label: "Agent Learning",
    command: "/evi-learning",
    family: "Learning",
    description: "Governs project-isolated AI Learning retrieval and candidate lifecycle.",
    setting: "Retrieve bounded accepted lessons or seal evidence-backed candidates under ENV/UOP.",
    produces: "Learning-only receipts, candidates, decisions, pointers, and revocations.",
    boundary: "Learning cannot overwrite Project Truth, consume Canon authority, or act as the Formula Engine.",
    primaryControl: false,
  },
  {
    id: "evi-instructions",
    label: "Instructions and host recall",
    command: "/evi-instructions",
    family: "Instructions",
    description: "Resolves AGENTS.md instruction scope and bounded host MEMORY.md recall as separate arms.",
    setting: "The automatic lifecycle queries both under ENV/UOP at Delta entry and when scope changes.",
    produces: "Separate instruction source-chain and host-recall locator/hash evidence.",
    boundary: "Neither arm becomes Project Memory, AI Learning, Canon, Plan, HIL, or runtime truth.",
    primaryControl: false,
  },
  {
    id: "evi-memory",
    label: "Project Memory",
    command: "/evi-memory",
    family: "Memory",
    description: "Queries and links bounded Project Memory DB locators through FTS5/BM25.",
    setting: "Project Memory remains independent from AI Learning, Canon, AGENTS.md, and host MEMORY.md.",
    produces: "A bounded locator slice or one typed content-addressed Memory edge.",
    boundary: "Learning-as-Memory compatibility actions are absent from the installed registry.",
    primaryControl: false,
  },
  {
    id: "evi-plugin",
    label: "Plugin",
    command: "/evi-plugin",
    family: "Connector",
    description: "Inspects and governs persistent connector and AI-toolchain sidecars.",
    setting: "Host, capabilities, actions, scope, expiry, and grant state remain visible.",
    produces: "A connector inventory or bounded sidecar action.",
    boundary: "Connector administration is outside lifecycle promotion.",
    primaryControl: false,
  },
  {
    id: "evi-refresh",
    label: "Refresh",
    command: "/evi-refresh",
    family: "Lifecycle",
    description: "Routes three distinct current refresh workflows by trigger.",
    setting: "Source Intake refreshes steer/prompt evidence, adaptive exit refreshes every Delta, and only full-PV HIL refreshes Project Overlay.",
    produces: "A classified source refresh, Delta-exit append receipt, or HIL-only cumulative blast-radius ledger.",
    boundary: "The three paths never alias, create candidate folders, query accepted storage, or imply Fuse.",
    primaryControl: true,
  },
  {
    id: "evi-rollback",
    label: "Rollback",
    command: "/evi-rollback",
    family: "Lifecycle",
    description: "Selects a Plan-stamped full-PV or auto-accepted sub-PV logical state.",
    setting: "Full PV comparison uses cumulative Overlay; sub-PV selection uses its Plan receipt.",
    produces: "An independent logical rollback-cursor receipt.",
    boundary: "Hard ZIP or Git restore is separate, explicit, and creates a new workspace/Plan cycle.",
    primaryControl: true,
  },
  {
    id: "evi-source-intake",
    label: "Source Intake",
    command: "/evi-source-intake",
    family: "Lifecycle",
    description: "Routes authorized sources across 18 canonical lanes and Project Engulf.",
    setting: "Auto-detection is ordered; exact user overrides remain visible.",
    produces: "A source registry and lane-routing receipt with Chat Lineage included.",
    boundary: "Intake classifies sources; it does not accept or promote them.",
    primaryControl: true,
  },
  {
    id: "evi-state-travel",
    label: "State Travel",
    command: "/evi-state-travel",
    family: "Session",
    description: "Preserves and resumes exact unfinished work, or enters accepted context when explicitly requested.",
    setting: "Only user request or genuine context exhaustion makes a verified fresh-host handoff eligible.",
    produces: "A hash-bound pointer, candidate, source, Plan Lane, Delta, resume-row, and host-profile handoff.",
    boundary: "Acceptance is not required for unfinished-work travel; the destination resumes the same verified row without consuming or substituting accepted history.",
    primaryControl: false,
  },
  {
    id: "evi-storage",
    label: "Storage",
    command: "/evi-storage",
    family: "Storage",
    description: "Inspects or selects Evidence Lane primary storage routing.",
    setting: "Local durable SQLite, durable mount, or configured transactional runtime by host class.",
    produces: "An append-only, secret-free storage receipt.",
    boundary: "A connector is a carrier or route, not an alternative source of truth.",
    primaryControl: false,
  },
  {
    id: "evi-universe",
    label: "Project Universe",
    command: "/evi-universe",
    family: "Universe",
    description: "Reads the linked live Project Universe graph through bounded public queries.",
    setting: "Universe is refreshed by adaptive Delta exit and remains linked to, not merged with, the six-way arms.",
    produces: "A bounded Universe locator slice and graph identity.",
    boundary: "No accepted ZIP query, candidate creation, HIL inference, or pointer movement.",
    primaryControl: false,
  },
  {
    id: "evi-fuse",
    label: "Fuse",
    command: "/evi-fuse",
    family: "Lifecycle",
    description: "Keeps Project and Learning HIL decisions separate and promotes only exact dual approval.",
    setting: "Runs only against the currently displayed conjoined human decision boundary.",
    produces: "An exact promotion or non-promotion receipt with unchanged authority roles.",
    boundary: "No text, test, install, commit, or preview can substitute for the two human decisions.",
    primaryControl: false,
  },
  {
    id: "evi-formula",
    label: "Formula Engine",
    command: "/evi-formula",
    family: "Mode",
    description: "Compiles and routes one bounded ENV/UOP formula with exact effects and budgets.",
    setting: "Uses the locked executable ENV/UOP action plane outside Project Truth.",
    produces: "A compiled formula and operator-route receipt.",
    boundary: "Formula execution cannot infer HIL, change a pointer, or become a generic math label.",
    primaryControl: false,
  },
  {
    id: "evi-brain-scaling",
    label: "Brain Scaling",
    command: "/evi-brain-scaling",
    family: "Memory",
    description: "Selects deterministic hash-addressed indexed slices within exact context budgets.",
    setting: "Runs over an already registered authority and its reusable indexes.",
    produces: "A bounded ordered slice receipt.",
    boundary: "It neither trains a model nor merges authority payloads.",
    primaryControl: false,
  },
  {
    id: "evi-project-recipe",
    label: "Project Recipe",
    command: "/evi-project-recipe",
    family: "Router",
    description: "Compiles the project-type Source Intake and lane execution recipe.",
    setting: "Runs at initial registration or explicit project reclassification, not State Travel.",
    produces: "An ordered Source Intake, ENV/UOP, lane-work, validation, and Delta recipe.",
    boundary: "A recipe is not Mode, a stored lane, a candidate, or approval.",
    primaryControl: false,
  },
  {
    id: "evi-toolchain",
    label: "Full AI Toolchain",
    command: "/evi-toolchain",
    family: "Connector",
    description: "Resolves the exact conditional Codex toolchain for one lane and action class.",
    setting: "Uses the 94-requirement matrix and the active Codex host capability profile.",
    produces: "An ordered primary and eligible-fallback route receipt.",
    boundary: "Presence never runs every tool and the deferred ChatGPT plane is not mixed in.",
    primaryControl: false,
  },
  {
    id: "evi-bigger-universe",
    label: "Bigger Universe",
    command: "/evi-bigger-universe",
    family: "Universe",
    description: "Registers and explicitly links hash-only project mini-brains across projects.",
    setting: "Federates above distinct per-project Universe authorities.",
    produces: "Changed-head and explicit cross-project edge receipts.",
    boundary: "Raw payloads and Project Truth never merge across projects.",
    primaryControl: false,
  },
] as const;

export const primaryLifecycleSurfaceIds = pluginSurfaces
  .filter((surface) => surface.primaryControl)
  .map((surface) => surface.id);
