export const primaryNavigation = [
  { href: "/architecture", label: "Architecture" },
  { href: "/lanes", label: "Lanes" },
  { href: "/operators", label: "Operators" },
  { href: "/studio", label: "Prompt Studio" },
  { href: "/proof", label: "Proof" },
  { href: "/provenance", label: "Provenance" },
  { href: "/connect", label: "Connect" },
] as const;

export const promptSuggestions = [
  "What problem does Evidence Lane solve?",
  "How are Build, Refresh, and Fuse different?",
  "What does one lane emit?",
  "How does the ChatGPT connector differ from Codex?",
] as const;

export const promptKnowledge = [
  {
    id: "problem",
    title: "The state-loss problem",
    keywords: ["problem", "solve", "memory", "forget", "context", "summary", "state", "handoff", "ephemeral"],
    answer: "Evidence Lane preserves exact, inspectable project state across AI tasks: authorized files, hashes, searchable SQLite facts, topology, pointers, receipts, visible steers, and unresolved human decisions. It replaces reconstructed conversational memory with a governed evidence package.",
    sources: [
      { label: "Problem framing", href: "/#problem" },
      { label: "Provenance", href: "/provenance" },
    ],
  },
  {
    id: "lifecycle",
    title: "Build, Refresh, Fuse",
    keywords: ["build", "refresh", "fuse", "approve", "candidate", "hil", "rollback", "pointer", "gate"],
    answer: "Build creates and validates an unaccepted candidate. Refresh rebuilds changed evidence while reusing unchanged bytes. Fuse is a separate promotion action that is impossible without exact APPROVE; it promotes the already sealed candidate without rebuilding it. Tests never substitute for the human gate.",
    sources: [
      { label: "Architecture", href: "/architecture" },
      { label: "Proof boundary", href: "/proof" },
    ],
  },
  {
    id: "lane-output",
    title: "Lane package outputs",
    keywords: ["lane", "emit", "output", "file", "sqlite", "mmd", "dot", "receipt", "topology", "parser", "chunker"],
    answer: "Each canonical lane builds a queryable SQLite sector, human-readable Mermaid topology, machine-comparable DOT topology, and lifecycle receipts. The sealed package also carries exact pointer and manifest evidence; the website animation focuses on the four files most useful for inspection.",
    sources: [
      { label: "18-lane catalog", href: "/lanes" },
      { label: "Architecture", href: "/architecture" },
    ],
  },
  {
    id: "hosts",
    title: "Codex and ChatGPT hosts",
    keywords: ["chatgpt", "codex", "connector", "mcp", "vercel", "tunnel", "install", "host", "marketplace"],
    answer: "Codex installs the plugin natively from the governed Git package. ChatGPT reaches the same engine through an HTTPS MCP edge, either a verified private tunnel or the Vercel adapter. Website health and connector identity are tested separately; a connection name alone is not release proof.",
    sources: [
      { label: "Connect", href: "/connect" },
      { label: "Live proof", href: "/proof" },
    ],
  },
  {
    id: "lanes",
    title: "Why eighteen lanes",
    keywords: ["18", "eighteen", "lanes", "source", "document", "code", "image", "pdf", "research", "lineage"],
    answer: "The registry separates eighteen source classes because code, chats, plans, documents, tables, slides, PDFs, images, packages, research, and existing SQLite brains need different parsers, chunk boundaries, retrieval tables, and mutation rules. Every route still enters one shared serial lifecycle and human gate.",
    sources: [
      { label: "Lane catalog", href: "/lanes" },
      { label: "System architecture", href: "/architecture" },
    ],
  },
  {
    id: "topology",
    title: "Topology proof",
    keywords: ["topology", "graph", "mermaid", "dot", "entity", "repo", "commit", "symbol", "route", "dependency"],
    answer: "Topology is evidence only when it reconciles with the lane database. Code lanes must expose the exact logical Repo, Commit, File, Symbol, Route, Dependency, and Artifact contract in both Mermaid and DOT; a generic but syntactically valid graph fails closed.",
    sources: [
      { label: "Architecture", href: "/architecture" },
      { label: "Proof rules", href: "/proof" },
    ],
  },
  {
    id: "privacy",
    title: "Visible lineage and privacy",
    keywords: ["privacy", "secret", "reasoning", "chain", "thought", "lineage", "prompt", "redact", "credentials"],
    answer: "Evidence Lane retains visible prompts, steers, assistant output, tool calls, file and test events, and available usage metrics. It excludes hidden chain-of-thought and redacts secrets before indexing. Connector credentials and private runtime state never become lane evidence.",
    sources: [
      { label: "Proof boundary", href: "/proof" },
      { label: "Provenance", href: "/provenance" },
    ],
  },
] as const;
export const controls = [
  {
    name: "Boot",
    detail: "Atomically verifies runtime, locked Flash, host class, and durable storage before a governed session opens.",
    result: "Verified session entry",
    guardrail: "No candidate and no pointer movement",
  },
  {
    name: "Rollback",
    detail: "Moves only an accepted pointer across immutable accepted versions; it does not rewrite evidence.",
    result: "Accepted pointer transition",
    guardrail: "Live source is never rewritten",
  },
  {
    name: "Build",
    detail: "Seals an unaccepted candidate, validates its evidence package, and stops at the six-way human gate.",
    result: "Immutable candidate package",
    guardrail: "Candidate remains unaccepted",
  },
  {
    name: "Refresh",
    detail: "Re-indexes changed sections while reusing unchanged content-addressed chunks and prior history.",
    result: "Exact source delta and next candidate",
    guardrail: "Complete final source is rechecked",
  },
  {
    name: "Mode",
    detail: "Applies ordered operating-mode intersections without changing source truth or lifecycle authority.",
    result: "Visible mode classification receipt",
    guardrail: "Lifecycle state is restored unchanged",
  },
  {
    name: "Source Intake",
    detail: "Auto-detects or explicitly routes governed sources across the canonical lane registry.",
    result: "Ordered lane-routing receipt",
    guardrail: "Chat Lineage is always included",
  },
] as const;

export const laneToolchains = [
  {
    id: "discussion",
    name: "Discussion",
    reason: "Visible decisions, questions, and scoped conversation evidence.",
    source: "Notes, meetings, and conversation exports",
    parser: "discussion_structured_v1",
    chunker: "semantic_blocks_v1",
    retrieval: "discussion_fts",
    story: ["Detect turns", "Extract decisions and deltas", "Index hard gates"],
  },
  {
    id: "analysis",
    name: "Analysis",
    reason: "Traceable findings, comparisons, assumptions, and unknowns.",
    source: "Audits, analyses, and decision records",
    parser: "analysis_structured_v1",
    chunker: "semantic_blocks_v1",
    retrieval: "analysis_fts",
    story: ["Separate claims", "Bind supporting evidence", "Expose risks and unknowns"],
  },
  {
    id: "plan",
    name: "Plan",
    reason: "Ordered tasks, dependencies, gates, and completion states.",
    source: "Project, implementation, and task plans",
    parser: "plan_structured_v1",
    chunker: "semantic_blocks_v1",
    retrieval: "plan_fts",
    story: ["Read phases", "Link dependencies", "Preserve acceptance criteria"],
  },
  {
    id: "mode",
    name: "Mode",
    reason: "Known operating intersections and explicit custom-mode schemas.",
    source: "Operating rules, policies, and control prompts",
    parser: "mode_contract_v1",
    chunker: "rule_blocks_v1",
    retrieval: "mode_fts",
    story: ["Classify in order", "Intersect allowed actions", "Restore lifecycle state"],
  },
  {
    id: "local_code",
    name: "Local code",
    reason: "Tracked local source, symbols, dependencies, tests, and builds.",
    source: "Authorized local folders and Git worktrees",
    parser: "local_code_snapshot_v2",
    chunker: "tiered_git_history_v2_incremental",
    retrieval: "code_chunk_fts",
    story: ["Hash tracked files", "Project seven logical entities", "Reconcile SQLite, MMD, and DOT"],
  },
  {
    id: "github_code",
    name: "GitHub code",
    reason: "Repository files, full Git history, refs, authorship, and changes.",
    source: "Authorized GitHub repositories and remotes",
    parser: "github_code_reverse_history_v2",
    chunker: "tiered_git_history_v2_incremental",
    retrieval: "code_chunk_fts",
    story: ["Walk reachable history", "Store content-addressed blobs", "Project seven logical entities"],
  },
  {
    id: "docs",
    name: "Documents",
    reason: "Structured text, sections, tables, claims, and document lineage.",
    source: "Documents, Markdown, HTML, and XML",
    parser: "document_structure_v1",
    chunker: "document_hierarchy_v1",
    retrieval: "doc_fts",
    story: ["Recover hierarchy", "Extract tables and images", "Index cited sections"],
  },
  {
    id: "data_excel",
    name: "Data / Excel",
    reason: "Tables, formulas, data quality, schemas, and workbook relationships.",
    source: "Workbooks, CSV, JSON, and Parquet",
    parser: "office_data_structural_v1",
    chunker: "table_structure_v1",
    retrieval: "data_fts",
    story: ["Inspect schema", "Trace formulas", "Sample rows with structure"],
  },
  {
    id: "ppt",
    name: "Presentations",
    reason: "Slides, narrative sequence, visual assets, and speaker evidence.",
    source: "PowerPoint and OpenDocument decks",
    parser: "presentation_structure_v1",
    chunker: "slide_structure_v1",
    retrieval: "ppt_fts",
    story: ["Read slide order", "Extract shapes and notes", "Bind visual references"],
  },
  {
    id: "pdf_ocr",
    name: "PDF / OCR",
    reason: "Page-aware text, OCR output, layout observations, and citations.",
    source: "Native and scanned PDF documents",
    parser: "pdf_ocr_structural_v2",
    chunker: "page_block_v1",
    retrieval: "pdf_fts",
    story: ["Prefer native text", "Run OCR when needed", "Preserve page locators"],
  },
  {
    id: "images_ocr",
    name: "Images / OCR",
    reason: "Visual descriptions, extracted text, hashes, and source context.",
    source: "Raster images and scanned evidence",
    parser: "image_ocr_structural_v2",
    chunker: "ocr_region_v1",
    retrieval: "image_ocr_fts",
    story: ["Hash exact pixels", "Detect OCR regions", "Flag review areas"],
  },
  {
    id: "artifacts",
    name: "Artifacts",
    reason: "Build outputs, packages, reports, hashes, and verification receipts.",
    source: "Reports, notebooks, manifests, and structured outputs",
    parser: "artifact_structure_v1",
    chunker: "artifact_blocks_v1",
    retrieval: "artifact_fts",
    story: ["Classify artifact", "Extract inspectable text", "Bind relations and review"],
  },
  {
    id: "custom",
    name: "Custom",
    reason: "User-defined evidence classes governed by an explicit lane schema.",
    source: "Named custom files and folders",
    parser: "custom_best_effort_v1",
    chunker: "bounded_text_v1",
    retrieval: "custom_fts",
    story: ["Apply explicit route", "Use bounded extraction", "Fail visibly on unsupported input"],
  },
  {
    id: "brain_loader",
    name: "Brain loader",
    reason: "Existing SQLite brains and sealed packages treated as sources.",
    source: "SQLite PV packages, folders, and databases",
    parser: "brain_package_loader_v1",
    chunker: "package_member_v1",
    retrieval: "brain_loader_fts",
    story: ["Verify package members", "Inspect manifests and pointers", "Load as candidate evidence"],
  },
  {
    id: "research",
    name: "Research",
    reason: "Source-backed findings with citations, dates, and uncertainty.",
    source: "Research documents, datasets, and notes",
    parser: "research_evidence_v1",
    chunker: "claim_evidence_v1",
    retrieval: "research_fts",
    story: ["Frame questions", "Bind evidence and citations", "Keep limitations visible"],
  },
  {
    id: "project_engulf",
    name: "Project Engulf",
    reason: "Project-wide inventory and routing without automatic acceptance.",
    source: "Authorized project folders and archives",
    parser: "project_engulf_v1",
    chunker: "project_structure_v1",
    retrieval: "project_engulf_fts",
    story: ["Inventory the project", "Map components and conflicts", "Route sectors without acceptance"],
  },
  {
    id: "sqlite_brain",
    name: "SQLite brain",
    reason: "Queryable sector facts, FTS, foreign keys, history, and manifests.",
    source: "SQLite databases and brain packages",
    parser: "sqlite_brain_inspector_v1",
    chunker: "sqlite_schema_row_v1",
    retrieval: "loaded_sqlite_brain_fts",
    story: ["Run integrity checks", "Map schema and foreign keys", "Expose compatibility evidence"],
  },
  {
    id: "chat_lineage",
    name: "Chat Lineage",
    reason: "Visible prompts, steers, assistant output, tools, files, tests, and hashes.",
    source: "Chat exports and append-only lineage packets",
    parser: "chat_lineage_state_travel_v57",
    chunker: "prepare_response_commit_v1",
    retrieval: "turn_fts",
    story: ["Prepare visible event", "Redact secrets", "Commit an idempotent hash-chain entry"],
  },
] as const;

export const lanes = laneToolchains.map(({ name, reason }) => [name, reason] as const);

export const painLedger = [
  {
    title: "Task windows end before the project does",
    observation: "A new Codex or ChatGPT task does not inherit exact files, hashes, accepted versions, steers, and gates by implication.",
    failure: "A polished handoff can sound complete while resuming from the wrong bytes or decision.",
    response: "Resume from a hash-bound accepted PV and preserve the exact pending candidate and HIL.",
  },
  {
    title: "Evidence fragments across tools",
    observation: "Git, chat, files, OCR, data, builds, and deployment checks produce different partial views of the same project.",
    failure: "The model fills missing relationships with plausible narrative instead of inspectable evidence.",
    response: "Route every source into one of 18 lane contracts and reconcile SQLite, Mermaid, DOT, and receipts.",
  },
  {
    title: "A passing check is narrower than a release decision",
    observation: "Builds and tests prove only the commands that actually executed against the bound source identity.",
    failure: "Continued work, green CI, or a visible preview is misread as human acceptance.",
    response: "Render a lane-specific six-way HIL; only exact APPROVE can authorize Fuse.",
  },
  {
    title: "Hosts do not share one storage reality",
    observation: "A stable PC, durable VM, ephemeral Codex VM, and ChatGPT MCP host have different continuity boundaries.",
    failure: "A convenient connector becomes an unverified alternative source of truth.",
    response: "Select durable local or mounted runtime authority by host class and carry only sealed entry/exit evidence.",
  },
] as const;

export const proofMetrics = [
  ["18", "canonical lanes", "Every routed source resolves to one inspectable lane contract."],
  ["15", "plugin surfaces", "Six lifecycle controls plus nine explicit routers and sidecars."],
  ["6", "everyday controls", "Boot, Rollback, Build, Refresh, Mode, and Source Intake."],
  ["1", "promotion token", "Only exact, case-sensitive APPROVE can authorize Fuse."],
] as const;

export const artifactContract = [
  ["SQLite", "Integrity, foreign keys, FTS, facts, history, and content-addressed chunks."],
  ["MMD", "Human-readable semantic topology reconciled back to the lane database."],
  ["DOT", "Machine-comparable graph topology with the same node and edge identity."],
  ["Receipt", "Source policy, pointer, refresh, actor, tool, build, test, and classification facts."],
] as const;

export const proofRules = [
  ["Tracked source only", "Git intake starts from the repository index, not arbitrary working-tree files."],
  ["Secret-safe before indexing", ".env, runtime state, credentials, private keys, and detected secret content are excluded before SQLite, CAS, FTS, or history insertion."],
  ["Graph reconciliation", "SQLite facts, Mermaid nodes and edges, and DOT nodes and edges must agree by identity and declared counts."],
  ["Candidate isolation", "Build and Refresh produce candidate overlays. Accepted sector truth changes only after an authorized Fuse."],
  ["Visible lineage only", "Prompts, steers, visible output, tools, files, tests, and available telemetry are retained; hidden chain-of-thought is never an input."],
] as const;

export const credits = [
  ["Praveen Rathee", "Independent product direction, architecture, funded hardware and services, source authority, testing, and human acceptance."],
  ["OpenAI ChatGPT", "Research partner, red-team and blue-team questioning, product critique, analysis, and decision support."],
  ["OpenAI Codex", "Implementation, debugging, test construction, forensic verification, documentation, and release evidence under human control."],
  ["Google Gemini", "Reasoning dialogue and comparative questioning used during research."],
  ["Anthropic Claude", "Independent Fable-plugin exploration and comparative implementation feedback."],
] as const;
