export const upstreamReferences = [
  {
    name: "GitHub Agentic Workflows",
    repository: "https://github.com/github/gh-aw",
    sourceUrl: "https://github.com/github/gh-aw/tree/5107b7bd547ce124f69084dc623e45a539cd17f5",
    commit: "5107b7bd547ce124f69084dc623e45a539cd17f5",
    tree: "1fa5cd684c6906a2f7bca8468097292fe4f6a40a",
    license: "MIT",
    category: "Open-source reference",
    role: "Safe workflow compilation, least-authority Actions, output, and cost-control contracts.",
    use: "Separated Actions runs, coding-agent sessions, remote Git actions, deployments, PVs, and HIL authority; kept local workflows project-authored and pinned.",
    boundary: "No upstream workflow file is represented as Evidence Lane code; Actions evidence never proves an agent session or HIL approval.",
    verdict: "Pursue selective contracts",
  },
  {
    name: "GitHub Agentic Workflows MCP Gateway",
    repository: "https://github.com/github/gh-aw-mcpg",
    sourceUrl: "https://github.com/github/gh-aw-mcpg/tree/0edcc73107c5a08b5bd8cfd489e68400b5ef95db",
    commit: "0edcc73107c5a08b5bd8cfd489e68400b5ef95db",
    tree: "58482ae9b60a14327f48f77e71ffd2d1930cf8ea",
    license: "MIT",
    category: "Open-source reference",
    role: "MCP isolation, input validation, bounded transport, timeout, and audit patterns.",
    use: "Applied fail-closed origin validation, literal-host rejection, bounded bodies, exact release identity, and sanitized health responses.",
    boundary: "The Evidence Lane adapter is project-authored; it neither embeds this gateway nor claims feature parity.",
    verdict: "Pursue selective patterns",
  },
  {
    name: "GitHub Copilot SDK",
    repository: "https://github.com/github/copilot-sdk",
    sourceUrl: "https://github.com/github/copilot-sdk/tree/4e95deee58f2712a9e75e66a1ffba4460cc9a1d5",
    commit: "4e95deee58f2712a9e75e66a1ffba4460cc9a1d5",
    tree: "3cb5e3b004cc224a538bc17078b651cbe5fa2509",
    license: "MIT",
    category: "Open-source reference",
    role: "Agent-session identity, lifecycle hooks, tool authorization, audit, and redaction patterns.",
    use: "Kept Actions and coding-agent evidence as different classes and redacted bounded agent output before remote-receipt persistence.",
    boundary: "Only a real GitHub session identifier can prove a Copilot coding-agent session.",
    verdict: "Pursue selective contracts",
  },
  {
    name: "GitHub Agentic Workflows threat detection",
    repository: "https://github.com/github/gh-aw-threat-detection",
    sourceUrl: "https://github.com/github/gh-aw-threat-detection/tree/09cc2eed706368655776af394eab7146629f905a",
    commit: "09cc2eed706368655776af394eab7146629f905a",
    tree: "88003d9a48ba64c31f67cea827fe5ff726c472cf",
    license: "MIT",
    category: "Open-source reference",
    role: "Post-output threat and infrastructure classification research.",
    use: "Added a narrow advisory classifier and stored only a redacted output projection with threat and infrastructure status separated.",
    boundary: "Local scanning is post-execution and advisory; it is not prevention or a security guarantee.",
    verdict: "Fix-then-pursue advisory only",
  },
  {
    name: "GitHub Agentic Workflows harness",
    repository: "https://github.com/github/gh-aw-harness",
    sourceUrl: "https://github.com/github/gh-aw-harness/tree/75ed171c12321e0cf4249a732c9860386bdc46a0",
    commit: "75ed171c12321e0cf4249a732c9860386bdc46a0",
    tree: "c0161d9c6f8a0b50aa00a34c0162b8ac3fbeb01d",
    license: "MIT",
    category: "Open-source execution-harness reference",
    role: "Repeatable registered-fixture execution with explicit outcomes and deterministic receipts.",
    use: "Implemented bounded in-process handlers, fixed JSON fixtures, explicit PASS/FAIL/ERROR expectations, post-output inspection, and sealed run receipts.",
    boundary: "No upstream code import, arbitrary command input, or SQLite continuity role; the execution harness and the memory harness remain distinct.",
    verdict: "Pursue bounded testable execution contract",
  },
  {
    name: "Open WebUI",
    repository: "https://github.com/open-webui/open-webui",
    sourceUrl: "https://github.com/open-webui/open-webui/tree/01f4282f1ffe0d6212f58d3afbeae21fffd0c4be",
    commit: "01f4282f1ffe0d6212f58d3afbeae21fffd0c4be",
    tree: "89b6c6e20fd32f8df36309d2ffffc7c9e6043522",
    license: "Open WebUI License",
    category: "Public source conceptual reference",
    role: "User-stated conceptual reference for inspectable AI application and review surfaces.",
    use: "Credited as conceptual product research only.",
    boundary: "No code import is claimed; byte reuse requires file-level provenance, rights review, and a separately accepted Git Delta.",
    verdict: "Fix-then-pursue conceptual credit only",
  },
  {
    name: "Graphify",
    repository: "https://github.com/Graphify-Labs/graphify",
    sourceUrl: "https://github.com/Graphify-Labs/graphify/tree/00efd6e7969837ae4a9f11d8d504dcd3b20b09df",
    commit: "00efd6e7969837ae4a9f11d8d504dcd3b20b09df",
    tree: "d1512b0250570474ee45b4169ba2d3b1b35376fa",
    license: "Apache-2.0 and MIT notices observed",
    category: "Pinned supplied source reference",
    role: "Stable graph identities, extracted-versus-inferred provenance, diff coverage, and affected-subgraph concepts.",
    use: "Adapted project-authored identity, graph-diff, coverage, and impact contracts with conformance tests.",
    boundary: "No Neo4j, LLM, server, installer, UI, or wholesale source transplant; V5.9 is the SQLite Brain Builder identity, not a Graphify version.",
    verdict: "Pursue bounded graph contracts",
  },
  {
    name: "GitHub CodeQL source",
    repository: "https://github.com/github/codeql",
    sourceUrl: "https://github.com/github/codeql/tree/74c8994c9fa3ca4551c01879ef9f74e3e09e791a",
    commit: "74c8994c9fa3ca4551c01879ef9f74e3e09e791a",
    tree: "06e9890166e4ad4bd015439016a137f8f4099ca8",
    license: "Source MIT; CLI separately licensed",
    category: "Pinned supplied source reference",
    role: "Negative-test and static-analysis research model.",
    use: "Informed project-authored security negative cases and honest NOT_RUN_LOCAL receipts.",
    boundary: "The CLI was not installed or run, so Evidence Lane makes no CodeQL scan claim and does not bundle the CLI.",
    verdict: "Pursue negative-test guidance only",
  },
  {
    name: "GitHub MCP Server",
    repository: "https://github.com/github/github-mcp-server",
    sourceUrl: "https://github.com/github/github-mcp-server/tree/3778a41476e31a072430cfee7c5d31c5f72def60",
    commit: "3778a41476e31a072430cfee7c5d31c5f72def60",
    tree: "ae97fb877726d54334bebcaaa640e58bab3ca84e",
    license: "MIT",
    category: "Pinned supplied source reference",
    role: "Read-only toolset bounds, validation, and connector-routing research.",
    use: "Strengthened ordered connector guards, capability checks, preferred-connector selection, and ambiguity failure.",
    boundary: "Evidence Lane does not embed or run a second MCP server and does not inherit its authority.",
    verdict: "Pursue connector-boundary patterns",
  },
  {
    name: "GitHub Branch Deploy",
    repository: "https://github.com/github/branch-deploy",
    sourceUrl: "https://github.com/github/branch-deploy/tree/7ad5ec6a7e19e3e341846e4d33c4ed779b3e8036",
    commit: "7ad5ec6a7e19e3e341846e4d33c4ed779b3e8036",
    tree: "5a901697cd7671a61db70f7f27787c6ba257deb8",
    license: "MIT",
    category: "Pinned supplied source reference",
    role: "No-op, commit-safety, and explicit deployment-action research.",
    use: "Applied exact-SHA remote-action preparation, no-op detection, and commit-bound deployment receipts.",
    boundary: "No auto-merge, main push, production promotion, or implicit HIL approval is adopted.",
    verdict: "Pursue guarded deployment patterns",
  },
  {
    name: "GitHub Local Action",
    repository: "https://github.com/github/local-action",
    sourceUrl: "https://github.com/github/local-action/tree/b9351d8a8f1e6eed27646f4d892b49a3847ba180",
    commit: "b9351d8a8f1e6eed27646f4d892b49a3847ba180",
    tree: "77093c3aeb8b01bcc35f24c7160596b725a7421d",
    license: "MIT",
    category: "Pinned supplied source reference",
    role: "Disposable fixture and secret-safe one-shot execution research.",
    use: "Applied temporary fixture workspaces, registered-secret suppression, and log redaction to project-authored tests.",
    boundary: "No arbitrary JavaScript execution, persistent local runner, or host-secret inheritance.",
    verdict: "Pursue bounded fixture patterns",
  },
] as const;

export const documentationReferences = [
  {
    name: "OpenAI plugin MCP server guidance",
    href: "https://developers.openai.com/plugins/build/mcp-server",
    use: "Verified focused tool metadata, input/output schemas, structured results, accurate safety annotations, stable HTTPS MCP transport, and tools that remain useful without custom UI.",
    boundary: "Guidance defines a compatibility and review contract; it does not make the public endpoint ready or grant deployment, publication, or HIL authority.",
  },
  {
    name: "OpenAI ChatGPT UI and MCP Apps guidance",
    href: "https://developers.openai.com/plugins/build/chatgpt-ui",
    use: "Verified standards-first MCP Apps resources, ui/resourceUri metadata, bridge behavior, capability-detected ChatGPT extensions, and supported inline or fullscreen interactive panels.",
    boundary: "ChatGPT controls its surrounding interface; Evidence Lane supplies portable resources and structured tool results rather than claiming pixel-identical host chrome.",
  },
  {
    name: "OpenAI MCP plugin review requirements",
    href: "https://developers.openai.com/plugins/deploy/app-review",
    use: "Verified public HTTPS, tool-scan metadata, annotations, linked UI resources, CSP, legal metadata, test prompts, and review prerequisites.",
    boundary: "A local test or Vercel page is not publication. The public connector remains unsubmitted and fail-closed until its durable endpoint and exact release identity pass review-ready verification.",
  },
  {
    name: "OpenAI Codex product documentation",
    href: "https://openai.com/index/introducing-codex/",
    use: "Codex host capability and product-boundary research.",
    boundary: "Documentation reference only; no documentation text is project source authority.",
  },
  {
    name: "OpenAI Codex plan guide",
    href: "https://help.openai.com/en/articles/11369540-using-codex-with-your-chatgpt-plan",
    use: "Separated Codex Plan mode, Goal, and task-panel behavior from the plugin's canonical Plan Lane.",
    boundary: "ChatGPT does not acquire Codex composer controls through this plugin.",
  },
  {
    name: "Model Context Protocol and MCP Apps guidance",
    href: "https://modelcontextprotocol.io/",
    use: "Portable tool contracts, structured results, resource metadata, and supported interactive-panel boundaries.",
    boundary: "Host UI chrome and publication review remain controlled by the host.",
  },
  {
    name: "GitHub Copilot coding-agent documentation",
    href: "https://docs.github.com/en/copilot/how-tos/copilot-on-github/use-copilot-agents/overview",
    use: "Distinguished Actions runs from real coding-agent sessions and their identifiers.",
    boundary: "A workflow run is not relabeled as a coding-agent session.",
  },
  {
    name: "GitHub CodeQL configuration documentation",
    href: "https://docs.github.com/en/code-security/how-tos/find-and-fix-code-vulnerabilities/configure-code-scanning/configure-code-scanning",
    use: "Code-scanning configuration and honest scan-status research.",
    boundary: "No scan claim exists without an executable CodeQL receipt.",
  },
  {
    name: "OpenRouter free-model router",
    href: "https://openrouter.ai/docs/guides/routing/routers/free-router",
    use: "Optional zero-cost route for visibly non-project general questions after a governed corpus no-hit.",
    boundary: "No project context, no paid fallback, no evidence authority, and unavailable until separately enabled with a host-managed key.",
  },
] as const;
