export const upstreamReferences = [
  {
    name: "GitHub Agentic Workflows",
    repository: "https://github.com/github/gh-aw",
    commit: "5107b7bd547ce124f69084dc623e45a539cd17f5",
    tree: "1fa5cd684c6906a2f7bca8468097292fe4f6a40a",
    license: "MIT",
    category: "Open-source reference",
    role: "Safe workflow compilation, least-authority Actions, output, and cost-control contracts.",
    boundary: "Selective contracts only; Actions evidence never proves an agent session or HIL approval.",
    verdict: "Pursue selective contracts",
  },
  {
    name: "GitHub Agentic Workflows MCP Gateway",
    repository: "https://github.com/github/gh-aw-mcpg",
    commit: "0edcc73107c5a08b5bd8cfd489e68400b5ef95db",
    tree: "58482ae9b60a14327f48f77e71ffd2d1930cf8ea",
    license: "MIT",
    category: "Open-source reference",
    role: "MCP isolation, input validation, bounded transport, timeout, and audit patterns.",
    boundary: "The Evidence Lane adapter is project-authored and makes no feature-parity claim.",
    verdict: "Pursue selective patterns",
  },
  {
    name: "GitHub Copilot SDK",
    repository: "https://github.com/github/copilot-sdk",
    commit: "4e95deee58f2712a9e75e66a1ffba4460cc9a1d5",
    tree: "3cb5e3b004cc224a538bc17078b651cbe5fa2509",
    license: "MIT",
    category: "Open-source reference",
    role: "Agent-session identity, lifecycle hooks, tool authorization, audit, and redaction patterns.",
    boundary: "Only a real GitHub session identifier can prove a Copilot coding-agent session.",
    verdict: "Pursue selective contracts",
  },
  {
    name: "GitHub Agentic Workflows threat detection",
    repository: "https://github.com/github/gh-aw-threat-detection",
    commit: "09cc2eed706368655776af394eab7146629f905a",
    tree: "88003d9a48ba64c31f67cea827fe5ff726c472cf",
    license: "MIT",
    category: "Open-source reference",
    role: "Post-output threat and infrastructure classification research.",
    boundary: "Local scanning is advisory and post-execution; it is not prevention or a security guarantee.",
    verdict: "Fix-then-pursue advisory only",
  },
  {
    name: "GitHub Agentic Workflows harness",
    repository: "https://github.com/github/gh-aw-harness",
    commit: "75ed171c12321e0cf4249a732c9860386bdc46a0",
    tree: "c0161d9c6f8a0b50aa00a34c0162b8ac3fbeb01d",
    license: "MIT",
    category: "Open-source research reference",
    role: "Future repeatable agentic-workflow harness research.",
    boundary: "The audited repository is intentionally minimal; no production harness contract was adopted.",
    verdict: "Park production use",
  },
  {
    name: "Open WebUI",
    repository: "https://github.com/open-webui/open-webui",
    commit: "01f4282f1ffe0d6212f58d3afbeae21fffd0c4be",
    tree: "89b6c6e20fd32f8df36309d2ffffc7c9e6043522",
    license: "Open WebUI License",
    category: "Public source conceptual reference",
    role: "User-stated conceptual influence for inspectable AI application and review surfaces.",
    boundary: "No current code import is claimed; byte reuse requires exact provenance and rights review.",
    verdict: "Fix-then-pursue conceptual credit only",
  },
] as const;
